Repository kubernetes-sigs/node-feature-discovery, pull requests merged in 2018-06, with the labels that each got.

#107 Update owners file
  OWNERS
Labels: cncf-cla: yes, size/XS

#126 Add RBAC policy
  README.md
  node-feature-discovery-daemonset.json.template
  node-feature-discovery-job.json.template
  rbac.yaml
Labels: cncf-cla: yes, size/M

#134 Template fixes
  node-feature-discovery-daemonset.json.template
Labels: cncf-cla: yes, size/S

#124 Update the container image tags in the templates to v0.2.0
  README.md
  node-feature-discovery-daemonset.json.template
  node-feature-discovery-job.json.template
Labels: cncf-cla: yes, lgtm, size/XS
