Repository kubernetes-sigs/node-feature-discovery, pull requests merged in 2019-05, with the labels that each got.

#238 Add Ethyling to OWNERS file
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#240 apihelpers: drop unused fields from K8sHelpers
  pkg/apihelper/k8shelpers.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#150 Simplify logging
  source/kernel/kernel.go
  source/local/local.go
  source/network/network.go
  source/pci/pci.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#100 Update dockerignore
  .dockerignore
Labels: approved, cncf-cla: yes, lgtm, size/XS

#242 README: fix two outdated hyperlinks
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#241 nfd-master: fix --label-whitelist
  pkg/nfd-master/nfd-master-internal_test.go
  pkg/nfd-master/nfd-master.go
  pkg/nfd-worker/nfd-worker_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#244 Update deps after dropping glog
  Gopkg.lock
Labels: approved, cncf-cla: yes, lgtm, size/S

#217 sources: move all cpu related features under the cpu source
  README.md
  cmd/nfd-worker/main.go
  cmd/nfd-worker/main_test.go
  demo/helper-scripts/demo-pod-with-discovery.yaml.cloverleaf.template
  demo/helper-scripts/demo-pod-with-discovery.yaml.parsec.template
  pkg/nfd-worker/nfd-worker.go
  source/cpu/cpu.go
  source/cpu/cpuid_amd64.go
  source/cpu/cpuid_arm64.go
  source/cpu/pstate.go
  source/cpu/rdt_amd64.go
  source/cpu/rdt_stub.go
  source/cpuid/cpuid_amd64.go
  source/rdt/rdt_stub.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#246 Dockerfile: verbose dep ensure
  Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#243 Better document the difference between latest release and master branch
  README.md
  label-nodes.sh
  nfd-daemonset-combined.yaml.template
  nfd-master.yaml.template
  nfd-worker-daemonset.yaml.template
  nfd-worker-job.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/M

#224 source/cpu: make cpuid configurable
  README.md
  nfd-worker.conf.example
  pkg/nfd-worker/nfd-worker.go
  source/cpu/cpu.go
  source/cpu/cpuid_arm64.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#231 Allow to change labels namespace
  README.md
  cmd/nfd-master/main.go
  pkg/nfd-master/nfd-master-internal_test.go
  pkg/nfd-master/nfd-master.go
  pkg/nfd-worker/nfd-worker.go
  source/local/local.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#248 Change the sed delimiter in deployment instructions
  README.md
  label-nodes.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#249 README: miscellaneous corrections
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#251 README: update the outdated usage demo
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#250 Use v0.4.0 release in README and deployment templates and script
  README.md
  label-nodes.sh
  nfd-daemonset-combined.yaml.template
  nfd-master.yaml.template
  nfd-worker-daemonset.yaml.template
  nfd-worker-job.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/M

#257 Remove inactive approvers from OWNERS
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS
