Repository kubernetes-sigs/node-feature-discovery, pull requests merged in 2019-02, with the labels that each got.

#216 Update README.md
  README.md
Labels: cncf-cla: yes, size/XS

#211 source/system: advertise major and minor OS version
  README.md
  source/system/system.go
Labels: approved, cncf-cla: yes, size/M

#179 README: corrections regarding pci feature source
  README.md
Labels: cncf-cla: yes, size/XS

#172 Document pstate and network feature sources better
  README.md
Labels: approved, cncf-cla: yes, size/XS

#163 README: minor correction of wording
  README.md
Labels: cncf-cla: yes, size/XS

#201 Correct links to template specs in the release documentation
  RELEASE.md
Labels: approved, cncf-cla: yes, size/XS

#199 Add validation for feature label values
  main.go
Labels: approved, cncf-cla: yes, size/S

#219 Use k8s apimachinery for label validation
  main.go
Labels: approved, cncf-cla: yes, size/S
