Repository kubernetes-sigs/node-feature-discovery, pull requests merged in 2019-06, with the labels that each got.

#256 Makefile: create default yamls, configurable namespace, docker-push
  Makefile
  README.md
  label-nodes.sh
  nfd-daemonset-combined.yaml.template
  nfd-master.yaml.template
  nfd-worker-daemonset.yaml.template
  nfd-worker-job.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/L

#197 Support non-binary kconfig options in kernel feature source
  source/kernel/kernel.go
Labels: approved, cncf-cla: yes, lgtm, lifecycle/stale, size/S

#258 kernel: fix undefined symbol error
  source/kernel/kernel.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#254 source/memory: detect NVDIMM DAX mode
  README.md
  source/memory/memory.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#160 travis: add deploy step to automatically push docker image
  .travis.yml
  Makefile
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#161 Use pod anti-affinity in the worker Job template spec
  label-nodes.sh
  nfd-worker-job.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/S

#259 travis: enable pushing of release images
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#181 Add simple e2e test
  Gopkg.lock
  Gopkg.toml
  Makefile
  README.md
  test/e2e/e2e.go
  test/e2e/e2e_test.go
  test/e2e/node_feature_discovery.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL
