Repository kubernetes-sigs/node-feature-discovery, pull requests merged in 2019-03, with the labels that each got.

#220 Add kad as reviewer in OWNERS file
  OWNERS
Labels: cncf-cla: yes, size/XS

#225 Add zvonkok to OWNERS file as a reviewer
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#214 source/memory: detect presence of NVDIMM devices
  README.md
  source/memory/memory.go
Labels: approved, cncf-cla: yes, size/M
