Repository kubernetes-sigs/node-feature-discovery, pull requests merged in 2019-04, with the labels that each got.

#228 Allow to get labels by reading files in local source
  README.md
  source/local/local.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#235 source/cpu: detect SST-BF
  README.md
  pkg/cpuid/cpuid_amd64.go
  pkg/cpuid/cpuid_amd64.s
  source/cpu/cpu.go
  source/cpu/power_amd64.go
  source/cpu/power_stub.go
  source/rdt/rdt_amd64.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#236 Mount source.d and features.d in template YAMLs
  README.md
  nfd-daemonset-combined.yaml.template
  nfd-worker-daemonset.yaml.template
  nfd-worker-job.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/M

#218 README: move description of hooks to the end of the feature source list
  README.md
Labels: approved, cncf-cla: yes, size/L

#223 Makefile: reorganise container image variables
  Makefile
  README.md
Labels: approved, cncf-cla: yes, size/M

#184 travis: run in minimal environment and drop sudo
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS
