Repository kubernetes-sigs/node-feature-discovery, pull requests merged in 2020-05, with the labels that each got.

#309 Proposal kernel.go: Replace forbidden symbols and check format
  source/kernel/kernel.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#316 README: document node annotations
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#311 Update gitignore and dockerignore
  .dockerignore
  .gitignore
Labels: approved, cncf-cla: yes, lgtm, size/S

#312 go.mod: tidy
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M

#314 Check gofmt
  .travis.yml
  Makefile
  source/cpu/cpuid_ppc64le.go
  source/cpu/cpuid_s390x.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#320 source/custom: minor change in usb rule for gofmt
  source/custom/rules/usb_id_rule.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#315 Verify golangci-lint
  .travis.yml
  Makefile
  cmd/nfd-master/main.go
  cmd/nfd-worker/main.go
  pkg/cpuid/cpuid_amd64.go
  pkg/cpuid/cpuid_amd64.s
  pkg/nfd-master/nfd-master-internal_test.go
  pkg/nfd-master/nfd-master.go
  pkg/nfd-worker/nfd-worker-internal_test.go
  pkg/nfd-worker/nfd-worker.go
  source/custom/custom.go
  source/custom/rules/pci_id_rule.go
  source/custom/rules/usb_id_rule.go
  source/custom/static_features.go
  source/internal/pci_utils.go
  source/internal/usb_utils.go
  source/kernel/kernel.go
  source/local/local.go
  source/panic_fake/fake_panic.go
  source/source.go
  test/e2e/node_feature_discovery.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#318 source: parametrise host directory paths
  Dockerfile
  Makefile
  source/config.go
  source/cpu/cpu.go
  source/cpu/power_amd64.go
  source/cpu/pstate.go
  source/internal/pci_utils.go
  source/iommu/iommu.go
  source/kernel/kernel.go
  source/kernel/selinux.go
  source/memory/memory.go
  source/network/network.go
  source/storage/storage.go
  source/system/system.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#307 nfd-worker: fix --label-whitelist
  README.md
  cmd/nfd-master/main.go
  cmd/nfd-worker/main.go
  pkg/nfd-worker/nfd-worker-internal_test.go
  pkg/nfd-worker/nfd-worker.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#304 Rework config handling
  README.md
  pkg/apihelper/mock_APIHelpers.go
  pkg/labeler/mock_LabelerClient.go
  pkg/nfd-worker/nfd-worker-internal_test.go
  pkg/nfd-worker/nfd-worker.go
  source/cpu/cpu.go
  source/custom/custom.go
  source/fake/fake.go
  source/iommu/iommu.go
  source/kernel/kernel.go
  source/local/local.go
  source/memory/memory.go
  source/mock_FeatureSource.go
  source/network/network.go
  source/panic_fake/fake_panic.go
  source/pci/pci.go
  source/source.go
  source/storage/storage.go
  source/system/system.go
  source/usb/usb.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#317 source/network: run discovery under /host-sys
  nfd-daemonset-combined.yaml.template
  nfd-worker-daemonset.yaml.template
  nfd-worker-job.yaml.template
  source/network/network.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#322 cpu: Add support for ARM/Aarch32 cpuid
  README.md
  source/cpu/cpuid_arm.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#323 README: document E2E_TEST_CONFIG Makefile variable
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#319 Use release v0.6.0 in deployment templates and README
  README.md
  nfd-daemonset-combined.yaml.template
  nfd-master.yaml.template
  nfd-worker-daemonset.yaml.template
  nfd-worker-job.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/S
