Repository kubernetes-sigs/node-feature-discovery, pull requests merged in 2020-08, with the labels that each got.

#330 Update builder image to Go 1.13.12
  .travis.yml
  Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#335 scripts: add scripts for kubernetest test-infra jobs
  .travis.yml
  scripts/test-infra/build-image.sh
  scripts/test-infra/verify.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#324 Small improvements in e2e tests
  test/e2e/node_feature_discovery.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#337 cloudbuild.yaml: use correct tags
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#313 Slight rework of building
  Dockerfile
  Makefile
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#342 Update go to 1.14.2
  .travis.yml
  Dockerfile
  go.mod
Labels: approved, cncf-cla: yes, lgtm, size/XS

#341 scripts/test-infra: add script for end-to-end testing
  .travis.yml
  Makefile
  scripts/test-infra/test-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#329 Update go dep golang.org/x/text
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/S

#338 cloudbuild.yaml: fix docker build arguments
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S
