Repository kubernetes-sigs/node-feature-discovery, pull requests merged in 2020-03, with the labels that each got.

#292 test/e2e: more comprehensive per-node testing
  .travis.yml
  Makefile
  pkg/nfd-master/nfd-master-internal_test.go
  pkg/nfd-master/nfd-master.go
  test/e2e/e2e-test-config.exapmle.yaml
  test/e2e/node_feature_discovery.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#295 Update gitignore to include yaml files generated from template
  .gitignore
Labels: approved, cncf-cla: yes, lgtm, size/XS

#294 Change nfd-master deployment mechanism from daemonset to deployment
  README.md
  nfd-master.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/S

#291 master: add extended resource support
  README.md
  cmd/nfd-master/main.go
  nfd-master.yaml.template
  pkg/apihelper/apihelpers.go
  pkg/apihelper/k8shelpers.go
  pkg/apihelper/mock_APIHelpers.go
  pkg/nfd-master/nfd-master-internal_test.go
  pkg/nfd-master/nfd-master.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#290 Support custom features
  README.md
  cmd/nfd-worker/main.go
  cmd/nfd-worker/main_test.go
  nfd-worker.conf.example
  pkg/nfd-worker/nfd-worker.go
  source/custom/custom.go
  source/custom/rules/loaded_kmod_rule.go
  source/custom/rules/pci_id_rule.go
  source/custom/rules/rule.go
  source/custom/static_features.go
  source/internal/pci_utils.go
  source/pci/pci.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#298 version: allow undefined version
  cmd/nfd-master/main.go
  cmd/nfd-worker/main.go
  pkg/version/version.go
Labels: approved, cncf-cla: yes, lgtm, size/S
