Repository kubernetes-sigs/node-feature-discovery, pull requests merged in 2020-11, with the labels that each got.

#381 docs: fix broken refs
  Makefile
  docs/advanced/developer-guide.md
  docs/get-started/deployment-and-usage.md
  docs/get-started/features.md
  docs/get-started/index.md
  scripts/github/update-gh-pages.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#382 release-0.6: fix broken refs in documentation
  Makefile
  docs/advanced/index.md
  docs/contributing/index.md
  docs/get-started/deployment-and-usage.md
  docs/get-started/examples-and-demos.md
  docs/get-started/features.md
  docs/get-started/index.md
  docs/get-started/quick-start.md
  scripts/github/update-gh-pages.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#370 Link to correct Github blobs, use staging images in deployment templates
  docs/_config.yml
  docs/advanced/developer-guide.md
  docs/contributing/index.md
  docs/get-started/deployment-and-usage.md
  docs/get-started/examples-and-demos.md
  docs/get-started/features.md
  docs/get-started/index.md
  docs/get-started/quick-start.md
  nfd-daemonset-combined.yaml.template
  nfd-master.yaml.template
  nfd-worker-daemonset.yaml.template
  nfd-worker-job.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/M

#383 scripts/update-gh-pages: redirect to "stable" documentation
  scripts/github/update-gh-pages.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#385 Update k8s dependencies to 1.19.4
  Makefile
  go.mod
  go.sum
  pkg/apihelper/k8shelpers.go
  test/e2e/e2e.go
  test/e2e/e2e_test.go
  test/e2e/node_feature_discovery.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#388 test/data: update test certs and keys
  test/data/ca.crt
  test/data/nfd-test-master.crt
  test/data/nfd-test-worker.crt
Labels: approved, cncf-cla: yes, lgtm, size/M

#389 Go 1.15
  Dockerfile
  go.mod
Labels: approved, cncf-cla: yes, lgtm, size/XS

#391 OWNERS: drop balajismaniam
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#369 Replace RELEASE.md with an issue template
  .github/ISSUE_TEMPLATE/new-release.md
  RELEASE.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#340 test/e2e: interpret node names in config as regexps
  test/e2e/e2e-test-config.exapmle.yaml
  test/e2e/node_feature_discovery.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#392 Update SECURITY_CONTACTS
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#395 Make all mounts in deployment templates read-only
  nfd-daemonset-combined.yaml.template
  nfd-worker-daemonset.yaml.template
  nfd-worker-job.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/XS

#396 docs: improve documentation of the custom source
  docs/get-started/features.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#397 scripts: add prepare-release.xh
  .github/ISSUE_TEMPLATE/new-release.md
  scripts/prepare-release.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#393 Fix a thing or two under test
  .gitignore
  test/e2e/e2e-test-config.example.yaml
  test/e2e/node_feature_discovery.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#399 docs: specify container image in config
  .github/ISSUE_TEMPLATE/new-release.md
  docs/_config.yml
  docs/advanced/developer-guide.md
  docs/advanced/master-commandline-reference.md
  docs/advanced/worker-commandline-reference.md
  scripts/prepare-release.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#400 Sync ClusterRole in deployment templates
  nfd-daemonset-combined.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/XS

#401 Container base image version bump
  Dockerfile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#356 nfd-worker: add special handling for --sources=all
  cmd/nfd-worker/main.go
  cmd/nfd-worker/main_test.go
  docs/advanced/developer-guide.md
  docs/advanced/worker-commandline-reference.md
  pkg/nfd-worker/nfd-worker.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#386 Add nfd-worker-conf ConfigMap to deployment templates
  Makefile
  docs/get-started/deployment-and-usage.md
  nfd-daemonset-combined.yaml.template
  nfd-worker-daemonset.yaml.template
  nfd-worker-job.yaml.template
  scripts/test-infra/verify.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#402 kernel: more agressively sanitize full kernel version
  source/kernel/kernel.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#403 test/e2e: fix e2e-config node matching
  test/e2e/node_feature_discovery.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#336 nfd-master: patch node object instead of rewriting it
  cmd/nfd-master/main.go
  go.mod
  go.sum
  pkg/apihelper/apihelpers.go
  pkg/apihelper/jsonpatch.go
  pkg/apihelper/k8shelpers.go
  pkg/apihelper/mock_APIHelpers.go
  pkg/nfd-master/nfd-master-internal_test.go
  pkg/nfd-master/nfd-master.go
  test/e2e/node_feature_discovery.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#405 gitignore: add bin/
  .gitignore
Labels: approved, cncf-cla: yes, lgtm, size/XS

#404 be a bit more verbose on a required KUBECONFIG env var
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS
