Repository kubernetes-sigs/node-feature-discovery, pull requests merged in 2020-12, with the labels that each got.

#408 scripts/update-gh-pages: only update docs if version has been released
  .github/workflows/gh-pages.yml
  scripts/github/update-gh-pages.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#410 Fix auto-generation of nfd-prune.yaml
  nfd-prune.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/XS

#409 scripts/update-gh-pages: fix generated commit message
  scripts/github/update-gh-pages.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#411 docs: more options in uninstallation instructions
  docs/get-started/deployment-and-usage.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#412 Add namespace and RBAC rules to nfd-prune.yaml.template
  docs/get-started/deployment-and-usage.md
  nfd-prune.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/M

#406 go.mod: update klauspost/cpuid
  docs/get-started/features.md
  go.mod
  go.sum
  source/internal/cpuidutils/cpuid_amd64.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#414 Update references to v0.7.0
  README.md
  docs/_config.yml
  nfd-daemonset-combined.yaml.template
  nfd-master.yaml.template
  nfd-prune.yaml.template
  nfd-worker-daemonset.yaml.template
  nfd-worker-job.yaml.template
  test/e2e/node_feature_discovery.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#415 github: update new-release issue template
  .github/ISSUE_TEMPLATE/new-release.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#416 Cherry-pick: github: update new-release issue template
  .github/ISSUE_TEMPLATE/new-release.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#417 scripts/update-gh-pages: add more details when stopping
  scripts/github/update-gh-pages.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#419 github: workflow fixes
  .github/workflows/gh-pages.yml
  scripts/github/update-gh-pages.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#420 README: update references to v0.7.0
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#421 go.mod: update to klauspost/cpuid/v2@v2.0.2
  go.mod
  go.sum
  source/internal/cpuidutils/cpuid_amd64.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S
