Repository kubernetes-sigs/node-feature-discovery, pull requests merged in 2020-02, with the labels that each got.

#282 go.mod: update kubernetes and its deps to v1.17.2
  go.mod
  go.sum
  pkg/apihelper/k8shelpers.go
  test/e2e/e2e.go
  test/e2e/e2e_test.go
  test/e2e/node_feature_discovery.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#280 Update go version in Dockerfile
  .travis.yml
  Dockerfile
  go.mod
Labels: approved, cncf-cla: yes, lgtm, size/XS

#284 README: note on avoiding a race condition with hooks
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#285 README: better document the usage of hooks and feature files
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#288 pci: add sriov.capable attribute
  README.md
  source/pci/pci.go
Labels: approved, cncf-cla: yes, lgtm, size/M
