Repository kubernetes-sigs/node-feature-discovery, pull requests merged in 2020-09, with the labels that each got.

#344 scripts: fix verify.sh
  scripts/test-infra/verify.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#343 cloudbuild.yaml: build using make
  Makefile
  README.md
  cloudbuild.yaml
  scripts/test-infra/push-image.sh
  scripts/test-infra/test-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#345 scripts: hand-construct a reproducible version
  scripts/test-infra/push-image.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#346 cloudbuild.yaml: set _GIT_TAG in env
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#347 scripts: configure docker authentication in push-image.sh
  scripts/test-infra/push-image.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#348 cloudbuild.yaml: set correct container image registry
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#339 scripts/test-infra: add build.sh
  scripts/test-infra/build.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#350 OWNERS: add ArangoGutierrez as a reviewer
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#352 Add prow badge
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#326 nfd-master: implement --prune flag
  README.md
  cmd/nfd-master/main.go
  pkg/apihelper/apihelpers.go
  pkg/apihelper/k8shelpers.go
  pkg/apihelper/mock_APIHelpers.go
  pkg/nfd-master/nfd-master.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#354 README: add Community section
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#349 scripts: update golangci-lint to v1.30.0 in verify.sh
  scripts/test-infra/verify.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#351 Fix Makefile to take vaules from ENV VAR values
  Makefile
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#355 Fix up Makefile variable initialization and documentation
  Makefile
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#357 README: drop References and unused links
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#358 Fix demo
  demo/README.md
  demo/helper-scripts/aggregate-logs-and-plot.sh
  demo/helper-scripts/clean-up.sh
  demo/helper-scripts/demo-pod-with-discovery.yaml.cloverleaf.template
  demo/helper-scripts/demo-pod-without-discovery.yaml.template
  demo/helper-scripts/run-with-discovery.sh
  demo/helper-scripts/run-without-discovery.sh
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/L

#359 Drop TravisCI integration
  .travis.yml
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#360 Drop gcloud auth for image pushing
  scripts/test-infra/push-image.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#334 custom: Add rules for kconfig and cpuid
  README.md
  source/cpu/cpu.go
  source/custom/custom.go
  source/custom/rules/cpuid_rule.go
  source/custom/rules/kconfig_rule.go
  source/internal/cpuidutils/cpuid_amd64.go
  source/internal/cpuidutils/cpuid_arm.go
  source/internal/cpuidutils/cpuid_arm64.go
  source/internal/cpuidutils/cpuid_ppc64le.go
  source/internal/cpuidutils/cpuid_s390x.go
  source/internal/kernelutils/kernel_kconfig.go
  source/internal/kernelutils/kernel_version.go
  source/kernel/kernel.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#362 Polish test-infra scripts a bit
  scripts/test-infra/build-image.sh
  scripts/test-infra/build.sh
  scripts/test-infra/push-image.sh
  scripts/test-infra/test-e2e.sh
  scripts/test-infra/verify.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#364 scripts: one more variable override fix in test-e2e.sh
  scripts/test-infra/test-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#363 Enable issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/support.md
Labels: approved, cncf-cla: yes, lgtm, size/M, tide/merge-method-squash
