Repository kubernetes-sigs/node-feature-discovery, pull requests merged in 2021-02, with the labels that each got.

#430 Set imagePullPolicy in the deployment templates to Always
  nfd-daemonset-combined.yaml.template
  nfd-master.yaml.template
  nfd-prune.yaml.template
  nfd-worker-daemonset.yaml.template
  nfd-worker-job.yaml.template
  scripts/prepare-release.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#434 Change the worker conf update mechanism of templates
  Makefile
  nfd-daemonset-combined.yaml.template
  nfd-worker-daemonset.yaml.template
  nfd-worker-job.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/S

#436 scripts/test-infra: update golangci-lint to v1.36.0
  scripts/test-infra/verify.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#435 Replace improper usage of filepath.Join with path.Join
  pkg/apihelper/jsonpatch.go
  pkg/nfd-master/nfd-master.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#438 Update gogo/protobuf and golang.org/x/text
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/S

#432 nfd-worker: use fsnotify for watching for config file changes
  go.mod
  pkg/nfd-worker/nfd-worker.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#431 nfd-master: implement --instance flag
  cmd/nfd-master/main.go
  docs/advanced/master-commandline-reference.md
  docs/get-started/introduction.md
  pkg/nfd-master/nfd-master-internal_test.go
  pkg/nfd-master/nfd-master.go
  test/e2e/node_feature_discovery.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#441 Update OWNERS file
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#433 nfd-worker: add core config
  cmd/nfd-worker/main.go
  cmd/nfd-worker/main_test.go
  docs/advanced/worker-commandline-reference.md
  docs/advanced/worker-configuration-reference.md
  docs/get-started/deployment-and-usage.md
  nfd-daemonset-combined.yaml.template
  nfd-worker-daemonset.yaml.template
  nfd-worker-job.yaml.template
  nfd-worker.conf.example
  pkg/nfd-worker/nfd-worker-internal_test.go
  pkg/nfd-worker/nfd-worker.go
  pkg/nfd-worker/nfd-worker_test.go
  source/fake/fake.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#423 Add helm chart for NFD
  Makefile
  deployment/node-feature-discovery/.helmignore
  deployment/node-feature-discovery/Chart.yaml
  deployment/node-feature-discovery/templates/_helpers.tpl
  deployment/node-feature-discovery/templates/clusterrole.yaml
  deployment/node-feature-discovery/templates/clusterrolebinding.yaml
  deployment/node-feature-discovery/templates/master.yaml
  deployment/node-feature-discovery/templates/nfd-worker-conf.yaml
  deployment/node-feature-discovery/templates/service.yaml
  deployment/node-feature-discovery/templates/serviceaccount.yaml
  deployment/node-feature-discovery/templates/worker.yaml
  deployment/node-feature-discovery/values.yaml
  docs/get-started/deployment-and-usage.md
  nfd-daemonset-combined.yaml.template
  nfd-master.yaml.template
  nfd-prune.yaml.template
  nfd-worker-daemonset.yaml.template
  nfd-worker-job.yaml.template
  scripts/prepare-release.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#443 Add NFD master '--instance' flag support to Helm chart
  deployment/node-feature-discovery/templates/master.yaml
  deployment/node-feature-discovery/values.yaml
  docs/get-started/deployment-and-usage.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#446 Fix daemonset deployment template
  nfd-worker-daemonset.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/XS

#447 Fix NFD master chart template
  deployment/node-feature-discovery/templates/master.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#444 Switch to flags package in command line arg parsing
  cmd/nfd-master/main.go
  cmd/nfd-master/main_test.go
  cmd/nfd-worker/main.go
  cmd/nfd-worker/main_test.go
  docs/advanced/developer-guide.md
  go.mod
  pkg/nfd-master/nfd-master-internal_test.go
  pkg/nfd-master/nfd-master.go
  pkg/nfd-master/nfd-master_test.go
  pkg/nfd-worker/nfd-worker-internal_test.go
  pkg/nfd-worker/nfd-worker.go
  pkg/nfd-worker/nfd-worker_test.go
  pkg/utils/flags.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#429 Added nodename rule to custom source
  deployment/node-feature-discovery/values.yaml
  docs/get-started/features.md
  nfd-daemonset-combined.yaml.template
  nfd-worker-daemonset.yaml.template
  nfd-worker-job.yaml.template
  nfd-worker.conf.example
  source/custom/custom.go
  source/custom/directory_features.go
  source/custom/rules/nodename_rule.go
  test/e2e/node_feature_discovery.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#449 docs: align docs with the single-dash command line flags
  docs/advanced/developer-guide.md
  docs/advanced/master-commandline-reference.md
  docs/advanced/worker-commandline-reference.md
  docs/get-started/deployment-and-usage.md
  docs/get-started/features.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#451 docs: enable markdown linting
  Makefile
  docs/advanced/architecture.md
  docs/advanced/customization-guide.md
  docs/advanced/developer-guide.md
  docs/advanced/e2e-configuration-reference.md
  docs/advanced/master-commandline-reference.md
  docs/advanced/worker-commandline-reference.md
  docs/advanced/worker-configuration-reference.md
  docs/get-started/deployment-and-usage.md
  docs/get-started/examples-and-demos.md
  docs/get-started/features.md
  docs/get-started/introduction.md
  docs/mdl-style.rb
  scripts/test-infra/mdlint.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#445 nfd-master: switch to klog
  cmd/nfd-master/main.go
  docs/advanced/master-commandline-reference.md
  go.mod
  pkg/nfd-master/nfd-master-internal_test.go
  pkg/nfd-master/nfd-master.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#450 nfd-worker: switch to klog
  cmd/nfd-worker/main.go
  cmd/nfd-worker/main_test.go
  deployment/node-feature-discovery/values.yaml
  docs/advanced/worker-commandline-reference.md
  docs/advanced/worker-configuration-reference.md
  nfd-daemonset-combined.yaml.template
  nfd-worker-daemonset.yaml.template
  nfd-worker-job.yaml.template
  nfd-worker.conf.example
  pkg/nfd-worker/nfd-worker.go
  pkg/utils/flags.go
  source/cpu/cpu.go
  source/custom/custom.go
  source/custom/directory_features.go
  source/custom/rules/nodename_rule.go
  source/internal/kernelutils/kernel_kconfig.go
  source/internal/pci_utils.go
  source/internal/usb_utils.go
  source/kernel/kernel.go
  source/local/local.go
  source/memory/memory.go
  source/network/network.go
  source/pci/pci.go
  source/system/system.go
  source/usb/usb.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#452 test/e2e: make openshift bits optional
  Makefile
  docs/advanced/developer-guide.md
  test/e2e/node_feature_discovery.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#453 Logging fixes
  cmd/nfd-master/main.go
  cmd/nfd-worker/main.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#455 scripts/test-infra: enable helm linting
  Makefile
  scripts/test-infra/verify.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS
