Repository kubernetes-sigs/node-feature-discovery, pull requests merged in 2021-11, with the labels that each got.

#593 resourcemonitor: aggregate and provide the memory and hugepages information
  pkg/resourcemonitor/noderesourcesaggregator.go
  pkg/resourcemonitor/noderesourcesaggregator_test.go
  pkg/resourcemonitor/podresourcesscanner.go
  pkg/resourcemonitor/podresourcesscanner_test.go
  pkg/resourcemonitor/types.go
  pkg/utils/memory_resources.go
  pkg/utils/memory_resources_test.go
Labels: lgtm, cncf-cla: yes, size/XL, approved, ok-to-test

#641 pkg/resourcemonitor: fix typo in comment
  pkg/resourcemonitor/podresourcesscanner.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#642 pkg/api/feature: small improvements
  pkg/api/feature/feature.go
  pkg/api/feature/types.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#643 test/e2e: make e2e tests run on single-node cluster
  test/e2e/node_feature_discovery.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#644 test/e2e: drop /boot mount
  test/e2e/node_feature_discovery.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#645 Topology-updater introduction typo fix
  docs/get-started/introduction.md
Labels: lgtm, cncf-cla: yes, size/XS, approved, ok-to-test

#640 deployment: Implicitly generate the worker ConfigMap name
  deployment/helm/node-feature-discovery/templates/nfd-worker-conf.yaml
  deployment/helm/node-feature-discovery/templates/worker.yaml
  deployment/helm/node-feature-discovery/values.yaml
  docs/get-started/deployment-and-usage.md
Labels: lgtm, cncf-cla: yes, size/S, approved, ok-to-test

#648 More topology updater documentation typo fixes
  docs/advanced/topology-updater-commandline-reference.md
  docs/get-started/introduction.md
Labels: lgtm, cncf-cla: yes, size/XS, approved, ok-to-test

#639 source/custom: expression based label rules
  source/custom/custom.go
  source/custom/expression/expression.go
  source/custom/expression/expression_test.go
  source/custom/rules/cpuid_rule.go
  source/custom/rules/kconfig_rule.go
  source/custom/rules/loaded_kmod_rule.go
  source/custom/rules/nodename_rule.go
  source/custom/rules/pci_id_rule.go
  source/custom/rules/rule.go
  source/custom/rules/usb_id_rule.go
  source/custom/static_features.go
Labels: lgtm, cncf-cla: yes, size/XXL, approved

#464 More extensive and expressive custom rules
  deployment/components/worker-config/nfd-worker.conf.example
  deployment/helm/node-feature-discovery/values.yaml
  source/custom/custom.go
  source/custom/custom_test.go
  source/custom/directory_features.go
  source/custom/expression/expression.go
  source/custom/static_features.go
Labels: lgtm, cncf-cla: yes, size/XL, approved

#652 NFD-Topology-Updater: Bump NRT API to version v0.0.12
  cmd/nfd-master/main.go
  deployment/base/noderesourcetopologies-crd/noderesourcetopologies.yaml
  deployment/helm/node-feature-discovery/templates/master.yaml
  deployment/helm/node-feature-discovery/templates/topologyupdater-crds.yaml
  deployment/helm/node-feature-discovery/values.yaml
  docs/advanced/developer-guide.md
  docs/get-started/deployment-and-usage.md
  go.mod
  go.sum
  pkg/nfd-master/nfd-master.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#653 specify CRD for custom labeling rules
  Makefile
  deployment/base/nfd-crds/cr-sample.yaml
  deployment/base/nfd-crds/kustomization.yaml
  deployment/base/nfd-crds/nodefeaturerule-crd.yaml
  deployment/helm/node-feature-discovery/manifests/nodefeaturerule-crd.yaml
  deployment/helm/node-feature-discovery/templates/nodefeaturerule-crd.yaml
  deployment/helm/node-feature-discovery/values.yaml
  deployment/overlays/default-combined/kustomization.yaml
  deployment/overlays/default-job/kustomization.yaml
  deployment/overlays/default/kustomization.yaml
  deployment/overlays/master-worker-topologyupdater/kustomization.yaml
  docs/get-started/deployment-and-usage.md
  go.mod
  pkg/apis/nfd/v1alpha1/doc.go
  pkg/apis/nfd/v1alpha1/expression.go
  pkg/apis/nfd/v1alpha1/expression_test.go
  pkg/apis/nfd/v1alpha1/types.go
  pkg/apis/nfd/v1alpha1/zz_generated.deepcopy.go
  source/custom/custom.go
  source/custom/custom_test.go
  source/custom/expression/expression_test.go
  source/custom/rules/cpuid_rule.go
  source/custom/rules/kconfig_rule.go
  source/custom/rules/loaded_kmod_rule.go
  source/custom/rules/nodename_rule.go
  source/custom/rules/pci_id_rule.go
  source/custom/rules/usb_id_rule.go
  source/custom/static_features.go
Labels: lgtm, cncf-cla: yes, size/XXL, approved

#654 source/custom: move rule matching to pkg/apis/nfd
  pkg/apis/nfd/v1alpha1/rule.go
  pkg/apis/nfd/v1alpha1/rule_test.go
  source/custom/custom.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#657 pkg/apis/nfd: drop excess field from the CRD
  deployment/base/nfd-crds/nodefeaturerule-crd.yaml
  deployment/helm/node-feature-discovery/manifests/nodefeaturerule-crd.yaml
  pkg/apis/nfd/v1alpha1/types.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#659 Update the link of slack channel
  docs/contributing/index.md
Labels: lgtm, cncf-cla: yes, size/XS, approved, needs-ok-to-test

#655 Add code for interacting with CRD API
  Makefile
  pkg/apis/nfd/v1alpha1/register.go
  pkg/apis/nfd/v1alpha1/types.go
  pkg/apis/nfd/v1alpha1/zz_generated.deepcopy.go
  pkg/generated/clientset/versioned/clientset.go
  pkg/generated/clientset/versioned/doc.go
  pkg/generated/clientset/versioned/fake/clientset_generated.go
  pkg/generated/clientset/versioned/fake/doc.go
  pkg/generated/clientset/versioned/fake/register.go
  pkg/generated/clientset/versioned/scheme/doc.go
  pkg/generated/clientset/versioned/scheme/register.go
  pkg/generated/clientset/versioned/typed/nfd/v1alpha1/doc.go
  pkg/generated/clientset/versioned/typed/nfd/v1alpha1/fake/doc.go
  pkg/generated/clientset/versioned/typed/nfd/v1alpha1/fake/fake_nfd_client.go
  pkg/generated/clientset/versioned/typed/nfd/v1alpha1/fake/fake_nodefeaturerule.go
  pkg/generated/clientset/versioned/typed/nfd/v1alpha1/generated_expansion.go
  pkg/generated/clientset/versioned/typed/nfd/v1alpha1/nfd_client.go
  pkg/generated/clientset/versioned/typed/nfd/v1alpha1/nodefeaturerule.go
  pkg/generated/informers/externalversions/factory.go
  pkg/generated/informers/externalversions/generic.go
  pkg/generated/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/generated/informers/externalversions/nfd/interface.go
  pkg/generated/informers/externalversions/nfd/v1alpha1/interface.go
  pkg/generated/informers/externalversions/nfd/v1alpha1/nodefeaturerule.go
  pkg/generated/listers/nfd/v1alpha1/expansion_generated.go
  pkg/generated/listers/nfd/v1alpha1/nodefeaturerule.go
Labels: lgtm, cncf-cla: yes, size/XXL, approved

#608 deployment: clean up base/topologyupdater-daemonset
  deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
  deployment/components/topology-updater/kustomization.yaml
  deployment/components/topology-updater/sleep-interval-flag.yaml
  deployment/components/topology-updater/topologyupdater-mounts.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved, Hacktoberfest

#633 topologyupdater: logs relevant message when feature-gate is disabled.
  cmd/nfd-topology-updater/main.go
  pkg/nfd-client/topology-updater/nfd-topology-updater.go
  pkg/resourcemonitor/noderesourcesaggregator.go
Labels: lgtm, cncf-cla: yes, size/S, approved, ok-to-test

#656 nfd-master: implement controller for NodeFeatureRule CRs
  cmd/nfd-master/main.go
  deployment/base/rbac/master-clusterrole.yaml
  deployment/helm/node-feature-discovery/templates/clusterrole.yaml
  deployment/helm/node-feature-discovery/templates/master.yaml
  deployment/helm/node-feature-discovery/values.yaml
  docs/advanced/master-commandline-reference.md
  docs/get-started/deployment-and-usage.md
  pkg/apihelper/k8shelpers.go
  pkg/nfd-client/topology-updater/nfd-topology-updater.go
  pkg/nfd-master/nfd-master.go
  pkg/nfd-master/nodefeaturerule-controller.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#649 source/storage: implement FeatureSource
  deployment/base/nfd-crds/cr-sample.yaml
  deployment/components/worker-config/nfd-worker.conf.example
  deployment/helm/node-feature-discovery/values.yaml
  source/storage/storage.go
  source/storage/storage_test.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#664 Revert "test/e2e: drop /boot mount"
  test/e2e/node_feature_discovery.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#553 CRD-based custom node labeling
  pkg/nfd-master/nfd-master.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#660 source/network: implement FeatureSource
  deployment/base/nfd-crds/cr-sample.yaml
  deployment/components/worker-config/nfd-worker.conf.example
  deployment/helm/node-feature-discovery/values.yaml
  source/network/network.go
  source/network/network_test.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#661 source/memory: implement FeatureSource
  deployment/base/nfd-crds/cr-sample.yaml
  deployment/components/worker-config/nfd-worker.conf.example
  deployment/helm/node-feature-discovery/values.yaml
  source/memory/memory.go
  source/memory/memory_test.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#550 Templating of custom label names
  deployment/base/nfd-crds/cr-sample.yaml
  deployment/base/nfd-crds/nodefeaturerule-crd.yaml
  deployment/components/worker-config/nfd-worker.conf.example
  deployment/helm/node-feature-discovery/manifests/nodefeaturerule-crd.yaml
  deployment/helm/node-feature-discovery/values.yaml
  pkg/apis/nfd/v1alpha1/expression.go
  pkg/apis/nfd/v1alpha1/expression_test.go
  pkg/apis/nfd/v1alpha1/rule.go
  pkg/apis/nfd/v1alpha1/rule_test.go
  pkg/apis/nfd/v1alpha1/types.go
  pkg/apis/nfd/v1alpha1/zz_generated.deepcopy.go
Labels: lgtm, cncf-cla: yes, size/XL, approved

#647 source/cpu: detect Intel SGX
  docs/get-started/features.md
  source/cpu/cpu.go
  source/cpu/sgx_amd64.go
  source/cpu/sgx_stub.go
Labels: lgtm, cncf-cla: yes, size/M, approved, ok-to-test

#665 source/kernel: don't advertise selinux.enabled=false
  source/kernel/kernel.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#666 source/memory: fix memory.numa label
  source/memory/memory.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#668 pkg/apis/nfd: stricter format checking for template labels
  pkg/apis/nfd/v1alpha1/rule.go
  pkg/apis/nfd/v1alpha1/rule_test.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#663 Add variables to feature rule spec and support backrefs
  deployment/base/nfd-crds/cr-sample.yaml
  deployment/base/nfd-crds/nodefeaturerule-crd.yaml
  deployment/components/worker-config/nfd-worker.conf.example
  deployment/helm/node-feature-discovery/manifests/nodefeaturerule-crd.yaml
  deployment/helm/node-feature-discovery/values.yaml
  pkg/api/feature/feature.go
  pkg/apis/nfd/v1alpha1/rule.go
  pkg/apis/nfd/v1alpha1/rule_test.go
  pkg/apis/nfd/v1alpha1/types.go
  pkg/apis/nfd/v1alpha1/zz_generated.deepcopy.go
  pkg/nfd-master/nfd-master.go
  source/custom/custom.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#675 source/cpu: add additional IBM Z CPU Flags
  source/cpu/cpuid_s390x.go
  source/cpu/power_stub.go
Labels: lgtm, cncf-cla: yes, size/S, approved, ok-to-test

#685 images: use k8s-staging-test-infra/gcb-docker-gcloud
  cloudbuild.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved
