Repository kubernetes-sigs/node-feature-discovery, pull requests merged in 2021-07, with the labels that each got.

#547 cpuid: correct the name of SSE4* cpuid flags
  deployment/node-feature-discovery/values.yaml
  docs/get-started/features.md
  nfd-daemonset-combined.yaml.template
  nfd-worker-daemonset.yaml.template
  nfd-worker-job.yaml.template
  nfd-worker.conf.example
  source/cpu/cpu.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#546 go.mod: update dependencies
  Makefile
  go.mod
  go.sum
  test/e2e/framework.go
  test/e2e/node_feature_discovery.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#538 make go report happy
  pkg/nfd-master/nfd-master-internal_test.go
  pkg/nfd-master/nfd-master.go
  source/custom/custom.go
  source/custom/directory_features.go
  source/custom/rules/loaded_kmod_rule.go
  source/custom/rules/nodename_rule.go
  source/custom/static_features.go
  source/internal/cpuidutils/cpuid_amd64.go
  source/internal/pci_utils.go
  source/iommu/iommu.go
  source/local/local.go
  source/pci/pci.go
  source/usb/usb.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#537 chore: update tolerations and affinities to control-plane
  deployment/node-feature-discovery/Chart.yaml
  deployment/node-feature-discovery/values.yaml
  nfd-master.yaml.template
  nfd-prune.yaml.template
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#551 Straighten wrinkles in lint fixes
  pkg/nfd-master/nfd-master.go
  source/custom/custom.go
  source/local/local.go
  source/pci/pci.go
  source/usb/usb.go
Labels: approved, cncf-cla: yes, lgtm, size/S
