Repository kubernetes-sigs/node-feature-discovery, pull requests merged in 2021-12, with the labels that each got.

#686 images: fix invalid k8s-staging-test-infra/gcb-docker-gcloud tag
  cloudbuild.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved

#679 Makefile: Add make deploy rule
  Makefile
Labels: lgtm, cncf-cla: yes, approved

#672 docs: drop cmdline help from developer guide
  docs/advanced/developer-guide.md
Labels: lgtm, cncf-cla: yes, size/M, approved

#687 Lint fixes to pkg/apis
  pkg/api/feature/feature.go
  pkg/apis/nfd/v1alpha1/doc.go
  pkg/apis/nfd/v1alpha1/expression.go
  pkg/apis/nfd/v1alpha1/register.go
  pkg/apis/nfd/v1alpha1/rule.go
  pkg/apis/nfd/v1alpha1/types.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#667 Add deploy-prune makefile rule to ease devel processes
  Makefile
Labels: lgtm, cncf-cla: yes, size/XS, approved

#671 Use single-dash format of cmdline flags
  cmd/nfd-topology-updater/main_test.go
  cmd/nfd-worker/main.go
  cmd/nfd-worker/main_test.go
  docs/advanced/worker-configuration-reference.md
  docs/get-started/features.md
  docs/get-started/introduction.md
  pkg/nfd-client/base.go
  pkg/nfd-client/topology-updater/nfd-topology-updater_test.go
  pkg/nfd-client/worker/nfd-worker.go
  pkg/nfd-client/worker/nfd-worker_test.go
  pkg/nfd-master/nfd-master-internal_test.go
  pkg/nfd-master/nfd-master.go
  pkg/nfd-master/nfd-master_test.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#683 source/kernel: ditch regexp in kconfig parsing
  source/kernel/kconfig.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#673 nfd-worker: rename 'sources' config option
  cmd/nfd-worker/main.go
  cmd/nfd-worker/main_test.go
  deployment/components/worker-config/nfd-worker.conf.example
  deployment/helm/node-feature-discovery/values.yaml
  docs/advanced/worker-commandline-reference.md
  docs/advanced/worker-configuration-reference.md
  docs/get-started/features.md
  pkg/nfd-client/worker/nfd-worker-internal_test.go
  pkg/nfd-client/worker/nfd-worker.go
  pkg/nfd-client/worker/nfd-worker_test.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#682 source/kernel: drop length check of kconfig values
  source/kernel/kconfig.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#684 source/kernel: unmangled kconfig values for custom rules
  source/custom/rules/kconfig_rule.go
  source/kernel/kconfig.go
  source/kernel/kernel.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#688 scripts: increase e2e-test image poll timeout to 12mins
  scripts/test-infra/test-e2e.sh
Labels: lgtm, cncf-cla: yes, size/XS, approved

#689 scripts/test-infra: bump helm to v3.7.1
  scripts/test-infra/verify.sh
Labels: lgtm, cncf-cla: yes, size/XS, approved

#670 nfd-worker: disable sources more easily
  cmd/nfd-worker/main.go
  docs/advanced/worker-commandline-reference.md
  docs/advanced/worker-configuration-reference.md
  pkg/nfd-client/worker/nfd-worker.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#605 nfd-worker: add core.featureSources config option
  cmd/nfd-worker/main.go
  cmd/nfd-worker/main_test.go
  deployment/components/worker-config/nfd-worker.conf.example
  deployment/helm/node-feature-discovery/values.yaml
  docs/advanced/worker-commandline-reference.md
  docs/advanced/worker-configuration-reference.md
  pkg/nfd-client/worker/nfd-worker-internal_test.go
  pkg/nfd-client/worker/nfd-worker.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#691 source: make per-source unit tests stricter
  source/cpu/cpu_test.go
  source/kernel/kernel_test.go
  source/local/local_test.go
  source/memory/memory_test.go
  source/network/network_test.go
  source/pci/pci_test.go
  source/storage/storage_test.go
  source/system/system_test.go
  source/usb/usb_test.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#692 source/fake: implement FeatureSource
  pkg/nfd-client/worker/nfd-worker-internal_test.go
  source/fake/fake.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#693 docs: fix mistake in md format
  docs/get-started/features.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#690 test/e2e: revise usage of nfd command line flags
  test/e2e/node_feature_discovery.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#694 source/usb: fix fallback to default label format
  source/usb/usb.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#696 source/local: log features per each hook and feature file
  source/local/local.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#695 source/local: don't prefix label names with the filename
  docs/get-started/features.md
  source/local/local.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#697 nfd-worker: drop 'custom-' prefix from matchFeatures custom rules
  pkg/nfd-client/worker/nfd-worker.go
  source/custom/custom.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#707 Dockerfile: build grpc_health-probe from source
  Dockerfile
Labels: lgtm, cncf-cla: yes, size/XS, approved

#709 Fix readiness and liveness checks
  Dockerfile
Labels: lgtm, cncf-cla: yes, size/XS, approved, ok-to-test
