Repository kubernetes-sigs/node-feature-discovery, pull requests merged in 2021-08, with the labels that each got.

#555 go.mod: update to klauspost/cpuid/v2@v2.0.9
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#541 Makefile: add apigen target
  Makefile
  go.mod
  go.sum
  pkg/labeler/labeler.pb.go
  pkg/labeler/labeler.proto
Labels: approved, cncf-cla: yes, lgtm, size/L

#549 Makefile: add lint target
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#559 Remove wrong comands on documentation
  docs/get-started/deployment-and-usage.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#560 backport-0.8: remove wrong commands from docs
  docs/get-started/deployment-and-usage.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#561 backport-0.7: remove wrong commands from docs
  docs/get-started/deployment-and-usage.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#536 nfd-master: allow sub-namespaces of the default label ns
  docs/advanced/master-commandline-reference.md
  docs/get-started/features.md
  pkg/nfd-master/nfd-master-internal_test.go
  pkg/nfd-master/nfd-master.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#564 helm: add readme
  deployment/node-feature-discovery/README.md
  scripts/prepare-release.sh
Labels: lgtm, cncf-cla: yes, size/S, approved

#568 Dockerfile: update go to 1.16.7
  Dockerfile
Labels: lgtm, cncf-cla: yes, size/XS, approved

#569 go.mod: update kubernetes to v1.22.0
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/XL, approved

#570 Better error reporting of kernel and cpu feature sources
  source/cpu/cpu.go
  source/cpu/cstate.go
  source/cpu/pstate.go
  source/kernel/selinux.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#563 Add Readiness and liveliness probes to nfd-master
  Dockerfile
  deployment/base/master-worker-combined/master-worker-daemonset.yaml
  deployment/base/master/master-deployment.yaml
  deployment/helm/node-feature-discovery/templates/master.yaml
  pkg/nfd-master/nfd-master.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#571 cstate/pstate: Skip check on non intel arches
  source/cpu/cstate_amd64.go
  source/cpu/cstate_stub.go
  source/cpu/pstate_amd64.go
  source/cpu/pstate_stub.go
Labels: lgtm, cncf-cla: yes, size/M, approved, ok-to-test

#572 docs: clarify the cpu.cstate feature
  docs/get-started/features.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#577 scripts: fix prepare-release.sh to update all kustomize files
  scripts/prepare-release.sh
Labels: lgtm, cncf-cla: yes, size/XS, approved

#578 kustomize: fix broken master-worker-combined base
  deployment/base/master-worker-combined/master-worker-daemonset.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved

#579 release-0.9: sync with master
  deployment/base/master-worker-combined/master-worker-daemonset.yaml
  scripts/prepare-release.sh
Labels: lgtm, cncf-cla: yes, size/S, approved

#576 release-0.9: update references to v0.9.0
  README.md
  deployment/base/master-worker-combined/master-worker-daemonset.yaml
  deployment/base/master/master-deployment.yaml
  deployment/base/worker-daemonset/worker-daemonset.yaml
  deployment/base/worker-job/worker-job.yaml
  deployment/helm/node-feature-discovery/Chart.yaml
  deployment/helm/node-feature-discovery/README.md
  deployment/helm/node-feature-discovery/values.yaml
  deployment/overlays/prune/master-job.yaml
  docs/_config.yml
  test/e2e/node_feature_discovery.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#581 release-0.9: README: fix deployment instructions
  README.md
Labels: lgtm, cncf-cla: yes, size/S, approved

#580 README: update deployment instructions to use v0.9.0
  README.md
Labels: lgtm, cncf-cla: yes, size/S, approved

#552 nfd-worker: split out gRPC connection handling
  cmd/nfd-worker/main.go
  pkg/nfd-client/base.go
  pkg/nfd-client/worker/nfd-worker-internal_test.go
  pkg/nfd-client/worker/nfd-worker.go
  pkg/nfd-client/worker/nfd-worker_test.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#583 gitignore: add kustomization.yaml
  .gitignore
Labels: lgtm, cncf-cla: yes, size/XS, approved

#543 source/custom: refactor kconfig rule internal representation
  source/custom/rules/kconfig_rule.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#575 Fix the typo in deployment-and-usage.md
  docs/get-started/deployment-and-usage.md
Labels: lgtm, cncf-cla: yes, size/XS, approved, tide/merge-method-squash, ok-to-test
