Repository kubernetes-sigs/node-feature-discovery, pull requests merged in 2021-09, with the labels that each got.

#589 Fix a link in deployment-and-usage.md
  docs/get-started/deployment-and-usage.md
Labels: lgtm, cncf-cla: yes, size/XS, approved, ok-to-test

#590 Fix broken link for worker-conf example
  docs/advanced/worker-configuration-reference.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#592 source/network: silence annoying/useless log message
  source/network/network.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#594 backports/v0.9: documentation fixes
  docs/advanced/worker-configuration-reference.md
  docs/get-started/deployment-and-usage.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#596 source: rename FeatureSource to LabelSource
  Makefile
  pkg/nfd-client/worker/nfd-worker-internal_test.go
  pkg/nfd-client/worker/nfd-worker.go
  source/cpu/cpu.go
  source/custom/custom.go
  source/fake/fake.go
  source/iommu/iommu.go
  source/kernel/kernel.go
  source/local/local.go
  source/memory/memory.go
  source/mock_LabelSource.go
  source/network/network.go
  source/pci/pci.go
  source/source.go
  source/storage/storage.go
  source/system/system.go
  source/usb/usb.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#599 deployment: fix formatting of the worker conf sample
  deployment/components/worker-config/nfd-worker.conf.example
  deployment/helm/node-feature-discovery/values.yaml
Labels: lgtm, cncf-cla: yes, size/M, approved

#597 source: make sources register themselves
  Makefile
  pkg/nfd-client/worker/nfd-worker-internal_test.go
  pkg/nfd-client/worker/nfd-worker.go
  source/cpu/cpu.go
  source/custom/custom.go
  source/fake/fake.go
  source/iommu/iommu.go
  source/kernel/kernel.go
  source/local/local.go
  source/memory/memory.go
  source/mock_LabelSource.go
  source/network/network.go
  source/pci/pci.go
  source/source.go
  source/source_test.go
  source/storage/storage.go
  source/system/system.go
  source/usb/usb.go
Labels: lgtm, cncf-cla: yes, size/XL, approved

#601 source: introduce FeatureSource interface
  pkg/api/feature/feature.go
  pkg/api/feature/types.go
  pkg/nfd-client/worker/nfd-worker-internal_test.go
  pkg/nfd-client/worker/nfd-worker.go
  source/cpu/cpu.go
  source/custom/custom.go
  source/fake/fake.go
  source/iommu/iommu.go
  source/kernel/kernel.go
  source/local/local.go
  source/memory/memory.go
  source/mock_LabelSource.go
  source/network/network.go
  source/pci/pci.go
  source/source.go
  source/source_test.go
  source/storage/storage.go
  source/system/system.go
  source/usb/usb.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#602 Utilize go generate
  Makefile
  pkg/apihelper/apihelpers.go
  pkg/apihelper/mock_APIHelpers.go
  pkg/labeler/doc.go
  pkg/labeler/labeler.pb.go
  pkg/labeler/mock_LabelerClient.go
  pkg/topologyupdater/doc.go
  pkg/topologyupdater/mock_NodeTopologyClient.go
  pkg/topologyupdater/topology-updater.pb.go
  source/mock_LabelSource.go
  source/source.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#606 Trim single quotes in parseOSRelease
  source/system/system.go
Labels: lgtm, cncf-cla: yes, size/XS, approved, ok-to-test

#611 docs: remote wip note from worker configuration reference
  docs/advanced/worker-configuration-reference.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#609 deployment: fix typo in overlay name
  deployment/overlays/topologyupdater-job/kustomization.yaml
  deployment/overlays/topologyupdater-job/namespace.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved

#613 Update developer-guide.md
  docs/advanced/developer-guide.md
Labels: lgtm, cncf-cla: yes, size/XS, approved, ok-to-test
