Repository kubernetes-sigs/node-feature-discovery, pull requests merged in 2021-10, with the labels that each got.

#615 scripts/test-infra: bump golangci-lint to v1.42.1
  pkg/nfd-master/nfd-master-internal_test.go
  scripts/test-infra/verify.sh
Labels: lgtm, cncf-cla: yes, size/XS, approved

#610 docs: fix TOCs
  docs/advanced/architecture.md
  docs/advanced/customization-guide.md
  docs/advanced/developer-guide.md
  docs/advanced/e2e-configuration-reference.md
  docs/advanced/master-commandline-reference.md
  docs/advanced/worker-commandline-reference.md
  docs/advanced/worker-configuration-reference.md
  docs/get-started/deployment-and-usage.md
  docs/get-started/examples-and-demos.md
  docs/get-started/features.md
  docs/get-started/introduction.md
  docs/mdl-style.rb
Labels: lgtm, cncf-cla: yes, size/M, approved, Hacktoberfest

#620 backports/v0.8: fixes to docs
  docs/advanced/architecture.md
  docs/advanced/customization-guide.md
  docs/advanced/developer-guide.md
  docs/advanced/e2e-configuration-reference.md
  docs/advanced/master-commandline-reference.md
  docs/advanced/worker-commandline-reference.md
  docs/advanced/worker-configuration-reference.md
  docs/get-started/deployment-and-usage.md
  docs/get-started/examples-and-demos.md
  docs/get-started/features.md
  docs/get-started/introduction.md
  docs/mdl-style.rb
Labels: lgtm, cncf-cla: yes, size/M, approved

#619 backports/v0.9: fixes to docs
  docs/advanced/architecture.md
  docs/advanced/customization-guide.md
  docs/advanced/developer-guide.md
  docs/advanced/e2e-configuration-reference.md
  docs/advanced/master-commandline-reference.md
  docs/advanced/worker-commandline-reference.md
  docs/advanced/worker-configuration-reference.md
  docs/get-started/deployment-and-usage.md
  docs/get-started/examples-and-demos.md
  docs/get-started/features.md
  docs/get-started/introduction.md
  docs/mdl-style.rb
Labels: lgtm, cncf-cla: yes, size/M, approved

#607 deployment: align topologyupdater overlays
  deployment/overlays/topologyupdater/kustomization.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved

#622 drop the topology updater job
  deployment/base/topologyupdater-job/kustomization.yaml
  deployment/base/topologyupdater-job/topologyupdater-job.yaml
  deployment/overlays/topologyupdater-job/kustomization.yaml
  deployment/overlays/topologyupdater-job/namespace.yaml
Labels: lgtm, cncf-cla: yes, size/M, approved, ok-to-test
