Repository kubernetes-sigs/node-feature-discovery, pull requests merged in 2022-01, with the labels that each got.

#710 Fix kustomization template to work with cert-manager
  deployment/overlays/samples/cert-manager/issuer.yaml
  deployment/overlays/samples/cert-manager/kustomization.yaml
  deployment/overlays/samples/cert-manager/master-cert.yaml
  deployment/overlays/samples/cert-manager/probes.yaml
  docs/get-started/deployment-and-usage.md
Labels: lgtm, cncf-cla: yes, size/M, approved, ok-to-test

#712 Enable TLS and cert-manager created certs for helm chart
  deployment/helm/node-feature-discovery/templates/cert-manager-certs.yaml
  deployment/helm/node-feature-discovery/templates/cert-manager-issuer.yaml
  deployment/helm/node-feature-discovery/templates/master.yaml
  deployment/helm/node-feature-discovery/templates/topologyupdater.yaml
  deployment/helm/node-feature-discovery/templates/worker.yaml
  deployment/helm/node-feature-discovery/values.yaml
  docs/get-started/deployment-and-usage.md
Labels: lgtm, cncf-cla: yes, size/L, approved, ok-to-test

#706 deployment/helm: refactor nfd-master rbac parameters
  deployment/helm/node-feature-discovery/templates/_helpers.tpl
  deployment/helm/node-feature-discovery/templates/clusterrole.yaml
  deployment/helm/node-feature-discovery/templates/clusterrolebinding.yaml
  deployment/helm/node-feature-discovery/templates/serviceaccount.yaml
  deployment/helm/node-feature-discovery/values.yaml
  docs/get-started/deployment-and-usage.md
Labels: lgtm, cncf-cla: yes, size/M, approved

#699 deployment/helm: disable nfr controller for parallel instances
  deployment/helm/node-feature-discovery/templates/master.yaml
  deployment/helm/node-feature-discovery/values.yaml
  docs/get-started/deployment-and-usage.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#701 deployment: use new custom rule format in sample configs
  deployment/components/worker-config/nfd-worker.conf.example
  deployment/helm/node-feature-discovery/values.yaml
  deployment/overlays/samples/custom-rules/custom-rules.example.yaml
Labels: lgtm, cncf-cla: yes, size/L, approved

#677 source/iommu: deprecate and disable by default
  docs/get-started/features.md
  docs/get-started/introduction.md
  pkg/nfd-client/worker/nfd-worker-internal_test.go
  pkg/nfd-client/worker/nfd-worker.go
  source/fake/fake.go
  source/iommu/iommu.go
  source/source.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#713 Initial bash at new TLS docs
  docs/get-started/deployment-and-usage.md
  docs/get-started/index.md
Labels: lgtm, cncf-cla: yes, size/L, approved, ok-to-test

#704 docs: add customization guide
  docs/_config.yml
  docs/advanced/customization-guide.md
  docs/get-started/features.md
  examples/nodefeaturerule.yaml
Labels: lgtm, cncf-cla: yes, size/XXL, approved

#714 docs: small tinkering on the TLS documentation
  docs/get-started/deployment-and-usage.md
Labels: lgtm, cncf-cla: yes, size/S, approved

#705 source/pci: add iommu_group/type attribute
  docs/advanced/customization-guide.md
  source/pci/utils.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#715 docs: small fix in block and net features in customization guide
  docs/advanced/customization-guide.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#719 release-0.10: update references to release v0.10.0
  deployment/base/master-worker-combined/master-worker-daemonset.yaml
  deployment/base/master/master-deployment.yaml
  deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
  deployment/base/worker-daemonset/worker-daemonset.yaml
  deployment/base/worker-job/worker-job.yaml
  deployment/helm/node-feature-discovery/Chart.yaml
  deployment/helm/node-feature-discovery/README.md
  deployment/helm/node-feature-discovery/values.yaml
  deployment/overlays/prune/master-job.yaml
  docs/_config.yml
  test/e2e/node_feature_discovery.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#720 README: bump to v0.10.0
  README.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#724 scripts/update-gh-pages: fix symlink to stable version
  scripts/github/update-gh-pages.sh
Labels: lgtm, cncf-cla: yes, size/XS, approved

#725 go.mod: bump kubernetes to v1.23.1
  go.mod
  go.sum
  test/e2e/node_feature_discovery.go
Labels: lgtm, cncf-cla: yes, size/XL, approved

#728 Adding missing target dep
  Makefile
Labels: lgtm, cncf-cla: yes, size/XS, approved

#730 cloudbuild.yaml: set HOME to /root
  cloudbuild.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved

#731 cloudbuild.yaml: double the timeout
  cloudbuild.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved

#733 cloudbuild.yaml: increase timeout to 2400s
  cloudbuild.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved

#734 cloudbuild.yaml: increase timeout to 1 hour
  cloudbuild.yaml
  scripts/test-infra/test-e2e.sh
Labels: lgtm, cncf-cla: yes, size/XS, approved

#735 cloudbuild.yaml: increase timeout to 1h 20min
  cloudbuild.yaml
  scripts/test-infra/test-e2e.sh
Labels: lgtm, cncf-cla: yes, size/XS, approved

#738 Increase timeout in test setups
  pkg/nfd-client/topology-updater/nfd-topology-updater_test.go
  pkg/nfd-client/worker/nfd-worker_test.go
Labels: lgtm, cncf-cla: yes, size/XS, approved, needs-ok-to-test

#739 scripts: configure docker auth in push-image.sh
  scripts/test-infra/push-image.sh
Labels: lgtm, cncf-cla: yes, size/XS, approved

#740 cloudbuild.yaml: upgrade machine type to n1-highcpu-8
  cloudbuild.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved

#742 scripts/test-infra: separate task for multiarch image build
  scripts/test-infra/build-image-cross.sh
  scripts/test-infra/build-image.sh
Labels: lgtm, cncf-cla: yes, size/XS, approved

#732 nfd-master: print gRPC server error correctly
  pkg/nfd-master/nfd-master.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#736 nfd-master: do graceful stop of gRPC server
  pkg/nfd-master/nfd-master.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#745 docs: clarify deployment requirements
  docs/get-started/deployment-and-usage.md
Labels: lgtm, cncf-cla: yes, size/S, approved

#743 release-0.10: enable multi arch builds
  Makefile
  cloudbuild.yaml
  docs/advanced/developer-guide.md
  docs/get-started/deployment-and-usage.md
  hack/init-buildx.sh
  pkg/nfd-client/topology-updater/nfd-topology-updater_test.go
  pkg/nfd-client/worker/nfd-worker_test.go
  pkg/nfd-master/nfd-master.go
  scripts/test-infra/build-image-cross.sh
  scripts/test-infra/build-image.sh
  scripts/test-infra/push-image.sh
  scripts/test-infra/test-e2e.sh
Labels: lgtm, cncf-cla: yes, size/L, approved

#748 docs: drop topology-updater cmdline help from developer guide
  docs/advanced/developer-guide.md
Labels: lgtm, cncf-cla: yes, size/M, approved

#753 README: point to v0.10.1
  README.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#727 docs: update helm document to match values.yaml
  docs/get-started/deployment-and-usage.md
Labels: lgtm, cncf-cla: yes, size/S, approved, tide/merge-method-squash, ok-to-test

#726 docs: fix operator deployment instructions
  docs/get-started/deployment-and-usage.md
Labels: lgtm, cncf-cla: yes, size/M, approved

#755 scripts/prepare-release: fix upating of readme
  scripts/prepare-release.sh
Labels: lgtm, cncf-cla: yes, size/XS, approved

#762 docs: re-fix operator deployment instructions
  docs/get-started/deployment-and-usage.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#754 docs: use new custom rule format in worker config reference
  docs/advanced/worker-configuration-reference.md
Labels: lgtm, cncf-cla: yes, size/S, approved

#761 [release-0.7] docs: fix operator deployment instructions
  docs/get-started/deployment-and-usage.md
Labels: lgtm, cncf-cla: yes, size/M, approved
