Repository kubernetes-sigs/node-feature-discovery, pull requests merged in 2022-03, with the labels that each got.

#782 Add ServiceAccount for nfd-worker
  deployment/helm/node-feature-discovery/templates/_helpers.tpl
  deployment/helm/node-feature-discovery/templates/clusterrolebinding.yaml
  deployment/helm/node-feature-discovery/templates/master.yaml
  deployment/helm/node-feature-discovery/templates/serviceaccount.yaml
  deployment/helm/node-feature-discovery/templates/worker.yaml
  deployment/helm/node-feature-discovery/values.yaml
Labels: lgtm, cncf-cla: yes, size/M, approved, ok-to-test

#779 Additional Lint Fixes in Codebase
  pkg/apihelper/k8shelpers.go
  pkg/apis/nfd/v1alpha1/rule_test.go
  pkg/nfd-client/base.go
  pkg/nfd-client/topology-updater/nfd-topology-updater.go
  pkg/nfd-master/nfd-master.go
  pkg/resourcemonitor/podresourcesscanner.go
  pkg/resourcemonitor/types.go
  source/cpu/cpu.go
  source/cpu/cstate_amd64.go
  source/cpu/power_amd64.go
  source/custom/rules/kconfig_rule.go
  source/custom/rules/nodename_rule.go
  source/fake/fake.go
  source/local/local.go
  source/memory/memory.go
  source/pci/pci.go
Labels: lgtm, cncf-cla: yes, size/M, approved, tide/merge-method-squash, ok-to-test

#769 Fixed the incorrect references
  docs/advanced/customization-guide.md
Labels: lgtm, cncf-cla: yes, size/XS, approved, tide/merge-method-squash, ok-to-test

#783 topologyupdater: Prevent crash with incorrect node id
  pkg/resourcemonitor/noderesourcesaggregator.go
Labels: kind/bug, lgtm, cncf-cla: yes, size/XS, approved, priority/awaiting-more-evidence, ok-to-test

#796 Fix a couple typos
  .github/ISSUE_TEMPLATE/new-release.md
  docs/advanced/customization-guide.md
  docs/advanced/developer-guide.md
  docs/get-started/deployment-and-usage.md
Labels: lgtm, cncf-cla: yes, size/S, approved

#787 apis/nfd: empty match expression set returns no features for templates
  docs/advanced/customization-guide.md
  pkg/apis/nfd/v1alpha1/expression.go
  pkg/apis/nfd/v1alpha1/expression_test.go
  pkg/apis/nfd/v1alpha1/rule.go
  pkg/apis/nfd/v1alpha1/rule_test.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#794 helm: add annotations to daemonset and deployment
  deployment/helm/node-feature-discovery/templates/master.yaml
  deployment/helm/node-feature-discovery/templates/worker.yaml
  deployment/helm/node-feature-discovery/values.yaml
  docs/get-started/deployment-and-usage.md
Labels: lgtm, cncf-cla: yes, size/S, approved, ok-to-test

#792 Add cpu-model feature detection
  docs/advanced/customization-guide.md
  docs/get-started/features.md
  source/cpu/cpu.go
Labels: lgtm, cncf-cla: yes, size/S, approved, tide/merge-method-squash

#790 cpu: Discover IBM Secure Execution
  docs/advanced/customization-guide.md
  docs/get-started/features.md
  source/cpu/cpu.go
  source/cpu/se_s390x.go
  source/cpu/se_stub.go
Labels: lgtm, cncf-cla: yes, size/M, approved, ok-to-test

#797 [release-0.11] Update references to release v0.11.0
  README.md
  deployment/base/master-worker-combined/master-worker-daemonset.yaml
  deployment/base/master/master-deployment.yaml
  deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
  deployment/base/worker-daemonset/worker-daemonset.yaml
  deployment/base/worker-job/worker-job.yaml
  deployment/helm/node-feature-discovery/Chart.yaml
  deployment/helm/node-feature-discovery/README.md
  deployment/helm/node-feature-discovery/values.yaml
  deployment/overlays/prune/master-job.yaml
  docs/_config.yml
  docs/advanced/developer-guide.md
  test/e2e/node_feature_discovery.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#799 README: bump instructions to use v0.11.0
  README.md
Labels: lgtm, cncf-cla: yes, size/XS, approved
