Repository kubernetes-sigs/node-feature-discovery, pull requests merged in 2022-02, with the labels that each got.

#771 go.mod: update to klauspost/cpuid/v2@v2.0.11
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/XS, approved, needs-ok-to-test

#770 [release-0.9] Revert "scripts: disable gofmt check in ci"
  scripts/test-infra/verify.sh
Labels: lgtm, cncf-cla: yes, size/XS, approved

#773 docs: Update default K8S_NAMESPACE
  docs/advanced/developer-guide.md
Labels: lgtm, cncf-cla: yes, size/XS, approved, ok-to-test

#781 tls: require min TLS version 1.3
  pkg/nfd-client/base.go
  pkg/utils/tls.go
Labels: lgtm, cncf-cla: yes, size/XS, approved
