Repository kubernetes-sigs/node-feature-discovery, pull requests merged in 2022-08, with the labels that each got.

#831 helm: add namespace override for multi-namespace deployments
  deployment/helm/node-feature-discovery/templates/_helpers.tpl
  deployment/helm/node-feature-discovery/templates/cert-manager-certs.yaml
  deployment/helm/node-feature-discovery/templates/cert-manager-issuer.yaml
  deployment/helm/node-feature-discovery/templates/clusterrolebinding.yaml
  deployment/helm/node-feature-discovery/templates/master.yaml
  deployment/helm/node-feature-discovery/templates/nfd-worker-conf.yaml
  deployment/helm/node-feature-discovery/templates/service.yaml
  deployment/helm/node-feature-discovery/templates/serviceaccount.yaml
  deployment/helm/node-feature-discovery/templates/topologyupdater.yaml
  deployment/helm/node-feature-discovery/templates/worker.yaml
  deployment/helm/node-feature-discovery/values.yaml
Labels: lgtm, cncf-cla: yes, size/M, approved, ok-to-test

#836 dockerfile: update builder image to golang v1.18
  Dockerfile
  Makefile
Labels: lgtm, cncf-cla: yes, size/S, approved

#838 go.mod: update github.com/google/go-cmp to v0.5.8
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/XS, approved

#851 go.mod: update github.com/klauspost/cpuid to v2.1.0
  docs/get-started/features.md
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/S, approved, ok-to-test

#854 Move e2e-test helpers to a separate package
  test/e2e/node_feature_discovery.go
  test/e2e/utils/config.go
  test/e2e/utils/pod.go
  test/e2e/utils/rbac.go
  test/e2e/utils/service.go
Labels: lgtm, cncf-cla: yes, size/XL, approved, ok-to-test

#847 test/e2e: refactor setup and cleanup
  test/e2e/node_feature_discovery.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#846 Improvements to scripts/prepare-release.sh
  scripts/prepare-release.sh
Labels: lgtm, cncf-cla: yes, size/M, approved

#829 Containerized auto-generation
  Dockerfile_generator
  Makefile
  hack/generate.sh
  pkg/api/feature/generated.pb.go
  pkg/api/feature/generated.proto
  pkg/apihelper/apihelpers.go
  pkg/apihelper/mock_APIHelpers.go
  pkg/generated/clientset/versioned/clientset.go
  pkg/generated/clientset/versioned/doc.go
  pkg/generated/clientset/versioned/fake/clientset_generated.go
  pkg/generated/clientset/versioned/fake/doc.go
  pkg/generated/clientset/versioned/fake/register.go
  pkg/generated/clientset/versioned/scheme/doc.go
  pkg/generated/clientset/versioned/scheme/register.go
  pkg/generated/clientset/versioned/typed/nfd/v1alpha1/doc.go
  pkg/generated/clientset/versioned/typed/nfd/v1alpha1/fake/doc.go
  pkg/generated/clientset/versioned/typed/nfd/v1alpha1/fake/fake_nfd_client.go
  pkg/generated/clientset/versioned/typed/nfd/v1alpha1/fake/fake_nodefeaturerule.go
  pkg/generated/clientset/versioned/typed/nfd/v1alpha1/generated_expansion.go
  pkg/generated/clientset/versioned/typed/nfd/v1alpha1/nfd_client.go
  pkg/generated/clientset/versioned/typed/nfd/v1alpha1/nodefeaturerule.go
  pkg/generated/informers/externalversions/factory.go
  pkg/generated/informers/externalversions/generic.go
  pkg/generated/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/generated/informers/externalversions/nfd/interface.go
  pkg/generated/informers/externalversions/nfd/v1alpha1/interface.go
  pkg/generated/informers/externalversions/nfd/v1alpha1/nodefeaturerule.go
  pkg/generated/listers/nfd/v1alpha1/expansion_generated.go
  pkg/generated/listers/nfd/v1alpha1/nodefeaturerule.go
  pkg/labeler/doc.go
  pkg/labeler/mock_LabelerClient.go
  pkg/topologyupdater/doc.go
  pkg/topologyupdater/mock_NodeTopologyClient.go
  source/mock_LabelSource.go
  source/source.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#845 Revert type hack in api
  Dockerfile_generator
  deployment/base/nfd-crds/nodefeaturerule-crd.yaml
  deployment/helm/node-feature-discovery/manifests/nodefeaturerule-crd.yaml
  pkg/api/feature/generated.pb.go
  pkg/apis/nfd/v1alpha1/expression.go
  pkg/apis/nfd/v1alpha1/rule_test.go
  pkg/apis/nfd/v1alpha1/types.go
  pkg/apis/nfd/v1alpha1/zz_generated.deepcopy.go
  pkg/generated/clientset/versioned/clientset.go
  pkg/generated/clientset/versioned/fake/clientset_generated.go
  pkg/generated/clientset/versioned/typed/nfd/v1alpha1/fake/fake_nodefeaturerule.go
  pkg/generated/clientset/versioned/typed/nfd/v1alpha1/nfd_client.go
  source/custom/static_features.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#528 topology updater: add e2e tests
  Makefile
  docs/advanced/developer-guide.md
  go.mod
  test/e2e/e2e-test-config.example.yaml
  test/e2e/topology_updater.go
  test/e2e/utils/config.go
  test/e2e/utils/kubeletconfig.go
  test/e2e/utils/node.go
  test/e2e/utils/noderesourcetopology.go
  test/e2e/utils/pod.go
  test/e2e/utils/rbac.go
Labels: lgtm, cncf-cla: yes, size/XXL, approved, ok-to-test

#860 nfd-master: fix incorrect log messages in crd controller
  pkg/nfd-master/nodefeaturerule-controller.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#861 nfd-master: more fixes to log messages
  pkg/nfd-master/nfd-master.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#868 logging: do not use %w with klog.Errorf
  pkg/nfd-master/nfd-master.go
  pkg/resourcemonitor/noderesourcesaggregator.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#862 helm: rename "manifests" subdir to "crds"
  deployment/helm/node-feature-discovery/crds/nodefeaturerule-crd.yaml
  deployment/helm/node-feature-discovery/templates/nodefeaturerule-crd.yaml
  hack/generate.sh
Labels: lgtm, cncf-cla: yes, size/XS, approved

#867 helm: add priorityClassName to worker
  deployment/helm/node-feature-discovery/templates/worker.yaml
  deployment/helm/node-feature-discovery/values.yaml
  docs/get-started/deployment-and-usage.md
Labels: lgtm, cncf-cla: yes, size/XS, approved, ok-to-test

#865 Fix templates for NodeFeatureRule with MatchAny
  pkg/apis/nfd/v1alpha1/rule.go
  pkg/apis/nfd/v1alpha1/rule_test.go
Labels: lgtm, cncf-cla: yes, size/S, approved, ok-to-test

#873 [release-0.11] Update references to release v0.11.2
  README.md
  deployment/base/master-worker-combined/master-worker-daemonset.yaml
  deployment/base/master/master-deployment.yaml
  deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
  deployment/base/worker-daemonset/worker-daemonset.yaml
  deployment/base/worker-job/worker-job.yaml
  deployment/helm/node-feature-discovery/Chart.yaml
  deployment/overlays/prune/master-job.yaml
  docs/_config.yml
  test/e2e/node_feature_discovery.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#874 README: update to v0.11.2
  README.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#877 scripts/test-e2e: install kubectl
  scripts/test-infra/test-e2e.sh
Labels: lgtm, cncf-cla: yes, size/XS, approved

#878 README: reconfigure prow badges
  README.md
Labels: lgtm, cncf-cla: yes, size/XS, approved
