Repository kubernetes-sigs/node-feature-discovery, pull requests merged in 2022-10, with the labels that each got.

#830 cpu: Discover Intel TDX
  docs/advanced/customization-guide.md
  docs/get-started/features.md
  source/cpu/security_amd64.go
Labels: lgtm, cncf-cla: yes, size/S, approved, ok-to-test

#905 nfd-worker: rename some symbols
  pkg/nfd-client/worker/nfd-worker-internal_test.go
  pkg/nfd-client/worker/nfd-worker.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#906 nfd-master: rename crd controller
  pkg/nfd-master/nfd-api-controller.go
  pkg/nfd-master/nfd-master.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#908 pkg/api/feature: rename types
  pkg/api/feature/feature.go
  pkg/api/feature/generated.pb.go
  pkg/api/feature/generated.proto
  pkg/api/feature/types.go
  pkg/apis/nfd/v1alpha1/rule.go
  pkg/apis/nfd/v1alpha1/rule_test.go
  pkg/nfd-master/nfd-master.go
  source/cpu/cpu.go
  source/custom/custom.go
  source/custom/rules/cpuid_rule.go
  source/custom/rules/loaded_kmod_rule.go
  source/custom/rules/nodename_rule.go
  source/fake/fake.go
  source/kernel/kernel.go
  source/local/local.go
  source/memory/memory.go
  source/source_test.go
  source/system/system.go
Labels: lgtm, cncf-cla: yes, size/XXL, approved

#891 test/e2e: fix segfault in case no e2e config file is specified
  test/e2e/utils/config.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#907 nfd-worker: refactor gRPC connection logic
  pkg/nfd-client/worker/nfd-worker.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#911 nfd-master: refactor gRPC into a separate method
  pkg/nfd-master/nfd-master.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#918 OWNERS: add fmuyassarov as a reviewer
  OWNERS
Labels: lgtm, cncf-cla: yes, size/XS, approved

#915 Tiltfile: update builder image to golang:1.19-bullseye
  Tiltfile
Labels: lgtm, cncf-cla: yes, size/XS, approved

#916 Update base image to Debian bullseye
  Makefile
  Tiltfile
Labels: lgtm, cncf-cla: yes, size/XS, approved

#921 Error strings should not be capitalized
  pkg/apis/nfd/v1alpha1/expression.go
  pkg/apis/nfd/v1alpha1/rule_test.go
  test/e2e/utils/pod.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#920 Standardize "k8s.io/api/core/v1" package short name
  pkg/apihelper/apihelpers.go
  pkg/apihelper/k8shelpers.go
  pkg/apihelper/mock_APIHelpers.go
  pkg/nfd-master/nfd-master-internal_test.go
  pkg/nfd-master/nfd-master.go
  pkg/resourcemonitor/noderesourcesaggregator.go
  pkg/resourcemonitor/podresourcesscanner.go
  pkg/utils/memory_resources.go
  pkg/utils/memory_resources_test.go
  test/e2e/node_feature_discovery.go
  test/e2e/topology_updater.go
  test/e2e/utils/node.go
  test/e2e/utils/noderesourcetopology.go
  test/e2e/utils/pod.go
  test/e2e/utils/rbac.go
  test/e2e/utils/service.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#919 Update CPU flags for ARM, POWER, and Z
  source/cpu/cpuid_arm.go
  source/cpu/cpuid_arm64.go
  source/cpu/cpuid_ppc64le.go
  source/cpu/cpuid_s390x.go
Labels: lgtm, cncf-cla: yes, size/L, approved, ok-to-test

#912 apis/nfd: migrate pkg/api/feature
  pkg/api/feature/generate.sh
  pkg/api/feature/types.go
  pkg/apis/nfd/v1alpha1/doc.go
  pkg/apis/nfd/v1alpha1/expression.go
  pkg/apis/nfd/v1alpha1/expression_test.go
  pkg/apis/nfd/v1alpha1/feature.go
  pkg/apis/nfd/v1alpha1/generate.sh
  pkg/apis/nfd/v1alpha1/generated.pb.go
  pkg/apis/nfd/v1alpha1/generated.proto
  pkg/apis/nfd/v1alpha1/rule.go
  pkg/apis/nfd/v1alpha1/rule_test.go
  pkg/apis/nfd/v1alpha1/types.go
  pkg/apis/nfd/v1alpha1/zz_generated.deepcopy.go
  pkg/labeler/labeler.pb.go
  pkg/labeler/labeler.proto
  pkg/nfd-client/worker/nfd-worker.go
  pkg/nfd-master/nfd-master.go
  source/cpu/cpu.go
  source/custom/custom.go
  source/fake/fake.go
  source/kernel/kernel.go
  source/local/local.go
  source/memory/memory.go
  source/network/network.go
  source/pci/pci.go
  source/pci/utils.go
  source/source.go
  source/storage/storage.go
  source/system/system.go
  source/usb/usb.go
  source/usb/utils.go
Labels: lgtm, cncf-cla: yes, size/XL, approved

#914 cpu: ignore unknown cpuid flags on non-x86
  source/cpu/cpuid_arm.go
  source/cpu/cpuid_arm64.go
  source/cpu/cpuid_ppc64le.go
  source/cpu/cpuid_s390x.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#929 topology-updater: continue looping on scan error
  pkg/nfd-client/topology-updater/nfd-topology-updater.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#930 Bump Kubernetes to v1.25.3
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/M, approved

#925 apis/nfd: flatten the structure of features data type
  deployment/base/nfd-crds/nfd-api-crds.yaml
  deployment/helm/node-feature-discovery/crds/nfd-api-crds.yaml
  pkg/apihelper/mock_APIHelpers.go
  pkg/apis/nfd/v1alpha1/feature.go
  pkg/apis/nfd/v1alpha1/generated.pb.go
  pkg/apis/nfd/v1alpha1/generated.proto
  pkg/apis/nfd/v1alpha1/rule.go
  pkg/apis/nfd/v1alpha1/rule_test.go
  pkg/apis/nfd/v1alpha1/types.go
  pkg/apis/nfd/v1alpha1/zz_generated.deepcopy.go
  pkg/labeler/labeler.pb.go
  pkg/labeler/labeler.proto
  pkg/nfd-client/worker/nfd-worker.go
  pkg/nfd-master/nfd-master.go
  source/cpu/cpu.go
  source/custom/custom.go
  source/fake/fake.go
  source/kernel/kernel.go
  source/local/local.go
  source/memory/memory.go
  source/network/network.go
  source/pci/pci.go
  source/source.go
  source/storage/storage.go
  source/system/system.go
  source/usb/usb.go
Labels: lgtm, cncf-cla: yes, size/XXL, approved

#933 source/usb: scan host sysfs
  source/usb/utils.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#935 apis/nfd: fix NodeFeatureRule templating
  pkg/apis/nfd/v1alpha1/rule.go
  pkg/apis/nfd/v1alpha1/rule_test.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#937 Stop using the beta.kubernetes.io/os and arch labels
  README.md
  docs/get-started/index.md
  docs/get-started/quick-start.md
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/cleanup

#936 Increase allowed image build timeout for 500s
  cloudbuild.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved

#938 Increase image waiting timeout
  scripts/test-infra/test-e2e.sh
Labels: lgtm, cncf-cla: yes, size/XS, approved

#942 [release-0.11] Update base image to Debian bullseye
  Makefile
Labels: lgtm, cncf-cla: yes, size/XS, approved

#943 [release-0.11] cpu: ignore unknown cpuid flags on non-x86
  source/cpu/cpuid_arm.go
  source/cpu/cpuid_arm64.go
  source/cpu/cpuid_ppc64le.go
  source/cpu/cpuid_s390x.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#944 [release-0.11] go.mod: bump kubernetes to v1.23.13
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/L, approved
