Repository kubernetes-sigs/node-feature-discovery, pull requests merged in 2022-12, with the labels that each got.

#974 docs: better document custom resources
  docs/get-started/introduction.md
  docs/get-started/quick-start.md
  docs/usage/custom-resources.md
  docs/usage/customization-guide.md
  docs/usage/examples-and-demos.md
Labels: lgtm, cncf-cla: yes, size/L, approved

#973 docs: simplify quick-start page
  docs/get-started/quick-start.md
  docs/usage/nfd-topology-updater.md
Labels: lgtm, cncf-cla: yes, size/M, approved

#977 scripts/mdlint: update mdlint to v0.12.0
  docs/mdl-style.rb
  scripts/test-infra/mdlint.sh
Labels: lgtm, cncf-cla: yes, size/XS, approved

#976 docs: small update to customization guide
  docs/usage/customization-guide.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#975 test/e2e: no pod restart policy of nfd-worker by default
  test/e2e/node_feature_discovery.go
  test/e2e/utils/pod/pod.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#981 nfd-master svc should select only nfd-master pods
  deployment/helm/node-feature-discovery/templates/service.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved

#979 helm: fix mount name of topology-updater config
  deployment/helm/node-feature-discovery/templates/topologyupdater.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved

#987 Bump go.mod k8s.io to 1.26
  go.mod
  go.sum
  pkg/nfd-master/nfd-api-controller.go
  pkg/resourcemonitor/excludelist.go
  test/e2e/node_feature_discovery.go
  test/e2e/topology_updater.go
  test/e2e/utils/config.go
  test/e2e/utils/pod/pod.go
Labels: lgtm, cncf-cla: yes, size/XL, approved

#988 nfd-master: add error checking for CRD controller creation
  pkg/nfd-master/nfd-api-controller.go
  pkg/nfd-master/nfd-master.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#986 Introduce NodeFeature CRD
  cmd/nfd-master/main.go
  cmd/nfd-worker/main.go
  deployment/base/nfd-crds/kustomization.yaml
  deployment/base/nfd-crds/nfd-api-crds.yaml
  deployment/base/rbac/kustomization.yaml
  deployment/base/rbac/master-clusterrole.yaml
  deployment/base/rbac/worker-role.yaml
  deployment/base/rbac/worker-rolebinding.yaml
  deployment/base/rbac/worker-serviceaccount.yaml
  deployment/base/worker-daemonset/worker-daemonset.yaml
  deployment/base/worker-job/worker-job.yaml
  deployment/helm/node-feature-discovery/crds/nfd-api-crds.yaml
  deployment/helm/node-feature-discovery/templates/clusterrole.yaml
  deployment/helm/node-feature-discovery/templates/master.yaml
  deployment/helm/node-feature-discovery/templates/role.yaml
  deployment/helm/node-feature-discovery/templates/rolebinding.yaml
  deployment/helm/node-feature-discovery/templates/worker.yaml
  deployment/helm/node-feature-discovery/values.yaml
  docs/deployment/helm.md
  docs/reference/master-commandline-reference.md
  docs/reference/worker-commandline-reference.md
  docs/reference/worker-configuration-reference.md
  hack/generate.sh
  pkg/apis/nfd/v1alpha1/annotations_labels.go
  pkg/apis/nfd/v1alpha1/register.go
  pkg/apis/nfd/v1alpha1/types.go
  pkg/apis/nfd/v1alpha1/zz_generated.deepcopy.go
  pkg/generated/clientset/versioned/typed/nfd/v1alpha1/fake/fake_nfd_client.go
  pkg/generated/clientset/versioned/typed/nfd/v1alpha1/fake/fake_nodefeature.go
  pkg/generated/clientset/versioned/typed/nfd/v1alpha1/generated_expansion.go
  pkg/generated/clientset/versioned/typed/nfd/v1alpha1/nfd_client.go
  pkg/generated/clientset/versioned/typed/nfd/v1alpha1/nodefeature.go
  pkg/generated/informers/externalversions/generic.go
  pkg/generated/informers/externalversions/nfd/v1alpha1/interface.go
  pkg/generated/informers/externalversions/nfd/v1alpha1/nodefeature.go
  pkg/generated/listers/nfd/v1alpha1/expansion_generated.go
  pkg/generated/listers/nfd/v1alpha1/nodefeature.go
  pkg/nfd-client/base.go
  pkg/nfd-client/worker/nfd-worker.go
  pkg/nfd-master/nfd-api-controller.go
  pkg/nfd-master/nfd-master-internal_test.go
  pkg/nfd-master/nfd-master.go
Labels: lgtm, cncf-cla: yes, size/XXL, approved

#992 nfd-master: fix creation of the -enable-nodefeature-api flag
  cmd/nfd-master/main.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#993 test/e2e: fix creation of NFD CRDs
  test/e2e/node_feature_discovery.go
  test/e2e/utils/crd.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#994 E2E: default kubeconfig location to ${HOME}/.kube/config
  Makefile
Labels: lgtm, cncf-cla: yes, size/XS, approved

#989 nfd-master: handle multiple NodeFeature objects
  pkg/apis/nfd/v1alpha1/feature.go
  pkg/nfd-master/nfd-master.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#997 test/e2e: create CRDs once in the beginning of the tests
  test/e2e/node_feature_discovery.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#1000 test/e2e: fix mistake in ginkgo focus
  test/e2e/node_feature_discovery.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#995 E2E: default seccompProfile to runtimeDefault for nfd worker
  test/e2e/utils/pod/pod.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#903 docs: document NodeFeature API
  docs/deployment/helm.md
  docs/get-started/introduction.md
  docs/reference/master-commandline-reference.md
  docs/reference/worker-commandline-reference.md
  docs/reference/worker-configuration-reference.md
  docs/usage/custom-resources.md
  docs/usage/customization-guide.md
  docs/usage/nfd-master.md
Labels: lgtm, cncf-cla: yes, size/L, approved

#996 E2E: parameterize container image and tag
  test/e2e/node_feature_discovery.go
  test/e2e/topology_updater.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#1002 test/e2e: drop pod security enforcement label from the test namespace
  test/e2e/node_feature_discovery.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#998 nfd-master: update all nodes at startup when NodeFeature API enabled
  pkg/nfd-master/nfd-master.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1004 test/e2e: don't expect control-plane nodes to be labeled
  test/e2e/node_feature_discovery.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#999 nfd-master: update node if no NodeFeature objects are present
  pkg/nfd-master/nfd-master.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#1003 test/e2e: drop host-usr-src mount
  test/e2e/utils/pod/pod.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#932 Add E2E test for NFD tainting feature
  test/e2e/data/nodefeaturerule-3-updated.yaml
  test/e2e/data/nodefeaturerule-3.yaml
  test/e2e/node_feature_discovery.go
  test/e2e/utils/crd.go
  test/e2e/utils/pod/pod.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#1001 test/e2e: add basic e2e-tests for NodeFeature API
  test/e2e/node_feature_discovery.go
  test/e2e/utils/pod/pod.go
  test/e2e/utils/rbac.go
Labels: lgtm, cncf-cla: yes, size/XL, approved

#1006 docs: better document differences between deployment methods
  docs/deployment/helm.md
  docs/deployment/index.md
  docs/deployment/kustomize.md
  docs/deployment/operator.md
Labels: lgtm, cncf-cla: yes, size/M, approved

#1008 github: update new-release issue template
  .github/ISSUE_TEMPLATE/new-release.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1009 docs: mention NodeFeature as an extension point
  docs/usage/custom-resources.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1007 [release-0.12] Update references to release v0.12.0
  Makefile
  README.md
  deployment/base/master-worker-combined/master-worker-daemonset.yaml
  deployment/base/master/master-deployment.yaml
  deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
  deployment/base/worker-daemonset/worker-daemonset.yaml
  deployment/base/worker-job/worker-job.yaml
  deployment/helm/node-feature-discovery/Chart.yaml
  deployment/helm/node-feature-discovery/README.md
  deployment/helm/node-feature-discovery/values.yaml
  deployment/overlays/prune/master-job.yaml
  docs/_config.yml
  test/e2e/node_feature_discovery.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#1011 docs: fix typo in CRD name
  docs/usage/custom-resources.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1013 Use single-dash format for nfd cmdline flags
  deployment/helm/node-feature-discovery/templates/master.yaml
  deployment/helm/node-feature-discovery/templates/topologyupdater.yaml
  deployment/helm/node-feature-discovery/templates/worker.yaml
  deployment/overlays/prune/master-job.yaml
  test/e2e/utils/pod/pod.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#1014 README: update to latest release v0.12.0
  README.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1015 dockerfile: update grpc-health-probe to v0.4.14
  Dockerfile
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1018 Add common utility function for getting node name
  cmd/nfd-topology-updater/main.go
  pkg/nfd-client/base.go
  pkg/nfd-client/topology-updater/nfd-topology-updater.go
  pkg/nfd-client/worker/nfd-worker.go
  pkg/nfd-master/nfd-master.go
  pkg/utils/kubernetes.go
  source/system/system.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#1019 topology-updater: move code
  cmd/nfd-topology-updater/main.go
  pkg/nfd-topology-updater/nfd-topology-updater.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1017 apis/nfd: make all fields in NodeFeatureSpec optional
  deployment/base/nfd-crds/nfd-api-crds.yaml
  deployment/helm/node-feature-discovery/crds/nfd-api-crds.yaml
  pkg/apis/nfd/v1alpha1/generated.proto
  pkg/apis/nfd/v1alpha1/types.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#1020 worker: move code
  cmd/nfd-worker/main.go
  pkg/nfd-client/base.go
  pkg/nfd-worker/nfd-worker-internal_test.go
  pkg/nfd-worker/nfd-worker.go
  pkg/nfd-worker/nfd-worker_test.go
Labels: lgtm, cncf-cla: yes, size/L, approved
