Repository kubernetes-sigs/node-feature-discovery, pull requests merged in 2023-12, with the labels that each got.

#1486 Change the base image of full image variant to Debian Bookworm
  Makefile
  docs/deployment/image-variants.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1485 docs: remove outdated instructions for minimal image
  docs/deployment/helm.md
  docs/deployment/kustomize.md
  docs/deployment/operator.md
Labels: lgtm, cncf-cla: yes, size/S, approved

#1448 feat: discover virtual network interface
  docs/usage/customization-guide.md
  source/network/network.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#1492 deployment/kustomize: drop default-combined overlay
  deployment/base/master-worker-combined/kustomization.yaml
  deployment/base/master-worker-combined/master-worker-daemonset.yaml
  deployment/components/common/env-combined.yaml
  deployment/components/common/kustomization.yaml
  deployment/components/common/securitycontext-combined.yaml
  deployment/components/common/worker-mounts-combined.yaml
  deployment/overlays/default-combined/kustomization.yaml
  deployment/overlays/default-combined/namespace.yaml
  docs/deployment/kustomize.md
  docs/developer-guide/index.md
Labels: lgtm, cncf-cla: yes, size/L, approved

#1493 dockerignore: cleanup
  .dockerignore
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1494 deployment/kustomize: drop nfd-master service
  deployment/base/master/kustomization.yaml
  deployment/base/master/master-service.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved

#1491 nfd-worker: set owner reference in NodeFeature objects
  deployment/components/common/env.yaml
  deployment/helm/node-feature-discovery/templates/worker.yaml
  pkg/nfd-worker/nfd-worker.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#1498 Makefile: more verbose output for e2e-tests
  Makefile
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1499 go.mod: update dependencies
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/M, approved

#1500 Makefile: fix e2e-testing of the full image
  Makefile
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1455 Create a Validate pkg
  docs/reference/master-configuration-reference.md
  docs/usage/customization-guide.md
  pkg/apis/nfd/validate/validate.go
  pkg/apis/nfd/validate/validate_test.go
  pkg/nfd-master/nfd-master-internal_test.go
  pkg/nfd-master/nfd-master.go
  scripts/test-infra/test-e2e.sh
Labels: lgtm, cncf-cla: yes, size/XL, approved

#1501 nfd-master: remove default denied ns from config
  pkg/nfd-master/nfd-master.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1502 Use non-exp maps package
  go.mod
  test/e2e/gomega.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1481 apis/nfd: drop creation helper functions
  deployment/base/nfd-crds/nfd-api-crds.yaml
  deployment/helm/node-feature-discovery/crds/nfd-api-crds.yaml
  pkg/apis/nfd/v1alpha1/expression.go
  pkg/apis/nfd/v1alpha1/expression_test.go
  pkg/apis/nfd/v1alpha1/rule_test.go
  pkg/apis/nfd/v1alpha1/types.go
  source/custom/static_features.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#788 apis/nfd: add matchName field in feature matcher terms
  deployment/base/nfd-crds/cr-sample.yaml
  deployment/base/nfd-crds/nfd-api-crds.yaml
  deployment/components/worker-config/nfd-worker.conf.example
  deployment/helm/node-feature-discovery/crds/nfd-api-crds.yaml
  deployment/helm/node-feature-discovery/values.yaml
  docs/usage/customization-guide.md
  pkg/apis/nfd/v1alpha1/expression.go
  pkg/apis/nfd/v1alpha1/rule.go
  pkg/apis/nfd/v1alpha1/rule_test.go
  pkg/apis/nfd/v1alpha1/types.go
  pkg/apis/nfd/v1alpha1/zz_generated.deepcopy.go
  samples/nodefeaturerule-cpu.yaml
  samples/nodefeaturerule-custom.yaml
  samples/nodefeaturerule-kernel.yaml
  samples/nodefeaturerule-local.yaml
  samples/nodefeaturerule-memory.yaml
  samples/nodefeaturerule-network.yaml
  samples/nodefeaturerule-pci.yaml
  samples/nodefeaturerule-storage.yaml
  samples/nodefeaturerule-system.yaml
  samples/nodefeaturerule-usb.yaml
  source/custom/static_features.go
  test/e2e/data/nodefeaturerule-1.yaml
  test/e2e/data/nodefeaturerule-2.yaml
  test/e2e/node_feature_discovery_test.go
Labels: lgtm, cncf-cla: yes, size/XL, do-not-merge/hold, approved

#1504 Document the NodeFeatureRule samples and move them under deployment dir
  deployment/nodefeaturerule/samples/nodefeaturerule-cpu.yaml
  deployment/nodefeaturerule/samples/nodefeaturerule-custom.yaml
  deployment/nodefeaturerule/samples/nodefeaturerule-kernel.yaml
  deployment/nodefeaturerule/samples/nodefeaturerule-local.yaml
  deployment/nodefeaturerule/samples/nodefeaturerule-memory.yaml
  deployment/nodefeaturerule/samples/nodefeaturerule-network.yaml
  deployment/nodefeaturerule/samples/nodefeaturerule-pci.yaml
  deployment/nodefeaturerule/samples/nodefeaturerule-storage.yaml
  deployment/nodefeaturerule/samples/nodefeaturerule-system.yaml
  deployment/nodefeaturerule/samples/nodefeaturerule-usb.yaml
  docs/usage/custom-resources.md
Labels: lgtm, cncf-cla: yes, size/S, approved

#1497 feat: add cpu socket count in `cpu.topology`
  docs/usage/customization-guide.md
  source/cpu/cpu.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#1477 apis/nfd: drop the private template caching fields
  pkg/apis/nfd/v1alpha1/rule.go
  pkg/apis/nfd/v1alpha1/rule_test.go
  pkg/apis/nfd/v1alpha1/types.go
  pkg/apis/nfd/v1alpha1/zz_generated.deepcopy.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#1506 chore(nfd-worker): fix minor typo in wrong label value format error
  pkg/nfd-worker/nfd-worker.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1508 apis/nfd: split rule processing into a separate package
  pkg/apis/nfd/v1alpha1/expression_test.go
  pkg/apis/nfd/v1alpha1/nodefeaturerule/expression-api_test.go
  pkg/apis/nfd/v1alpha1/nodefeaturerule/expression.go
  pkg/apis/nfd/v1alpha1/nodefeaturerule/expression_test.go
  pkg/apis/nfd/v1alpha1/nodefeaturerule/rule.go
  pkg/apis/nfd/v1alpha1/nodefeaturerule/rule_test.go
  pkg/nfd-master/nfd-master.go
  source/custom/custom.go
Labels: lgtm, cncf-cla: yes, size/XXL, approved

#1509 go.mod: bump kubernetes to v1.29
  go.mod
  go.sum
  test/e2e/utils/pod/pod.go
Labels: lgtm, cncf-cla: yes, size/XXL, approved

#1511 [release-0.14] go.mod: update dependencies
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/M, approved

#1512 [release-0.14] Update references to release v0.14.4
  Makefile
  README.md
  deployment/base/gc/gc.yaml
  deployment/base/master-worker-combined/master-worker-daemonset.yaml
  deployment/base/master/master-deployment.yaml
  deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
  deployment/base/worker-daemonset/worker-daemonset.yaml
  deployment/base/worker-job/worker-job.yaml
  deployment/helm/node-feature-discovery/Chart.yaml
  deployment/overlays/prune/master-job.yaml
  docs/_config.yml
Labels: lgtm, cncf-cla: yes, size/S, approved

#1513 [release-0.14] Dockerfile: update grpc-health-probe to v0.4.24
  Dockerfile
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1514 docs: use default instead of minimal image variant
  docs/deployment/image-variants.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1515 docs: document new x86 cpuid features
  docs/usage/features.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1516 docs: fix malformed hyperlink syntax
  docs/usage/custom-resources.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1446 Add Kubectl NFD plugin
  Makefile
  cmd/kubectl-nfd/main.go
  cmd/kubectl-nfd/subcmd/dryrun.go
  cmd/kubectl-nfd/subcmd/root.go
  cmd/kubectl-nfd/subcmd/test.go
  cmd/kubectl-nfd/subcmd/validate.go
  docs/reference/plugin-commandline-reference.md
  docs/reference/versions.md
  docs/usage/kubectl-plugin.md
  examples/nodefeature.yaml
  examples/nodefeaturerule.yaml
  go.mod
  pkg/apis/nfd/validate/validate.go
  pkg/kubectl-nfd/dryrun.go
  pkg/kubectl-nfd/test.go
  pkg/kubectl-nfd/validate.go
Labels: lgtm, cncf-cla: yes, size/XL, approved

#1517 docs: fix name of prometheus kustomize overlay
  docs/deployment/kustomize.md
Labels: lgtm, cncf-cla: yes, size/XS, do-not-merge/hold, approved

#1519 docs: document all tracking annotations
  docs/get-started/introduction.md
Labels: lgtm, cncf-cla: yes, size/S, approved

#1520 docs: fix wording and nfd version in master config ref
  docs/reference/master-configuration-reference.md
Labels: lgtm, cncf-cla: yes, size/S, approved

#1518 docs: second fix to the prometheus kustomize overlay name
  docs/deployment/metrics.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1521 docs: fixes
  docs/usage/custom-resources.md
  docs/usage/kubectl-plugin.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1523 deployment/kustomize: enable nfd-gc in the default overlay
  deployment/overlays/default/kustomization.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1522 [release-0.15] Update references to release v0.15.0
  Makefile
  README.md
  deployment/base/gc/gc.yaml
  deployment/base/master/master-deployment.yaml
  deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
  deployment/base/worker-daemonset/worker-daemonset.yaml
  deployment/base/worker-job/worker-job.yaml
  deployment/helm/node-feature-discovery/Chart.yaml
  deployment/helm/node-feature-discovery/README.md
  deployment/helm/node-feature-discovery/values.yaml
  deployment/overlays/prune/master-job.yaml
  docs/_config.yml
Labels: lgtm, cncf-cla: yes, size/M, approved

#1527 github: update tagging instructions in release checklists
  .github/ISSUE_TEMPLATE/new-patch-release.md
  .github/ISSUE_TEMPLATE/new-release.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1524 Update readme to v0.15.0 release
  README.md
Labels: lgtm, cncf-cla: yes, size/S, approved

#1528 makefile: fix build: target
  Makefile
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1526 Makefile: add -timeout argument to e2e-tests
  Makefile
Labels: lgtm, cncf-cla: yes, size/XS, approved
