Repository kubernetes-sigs/node-feature-discovery, pull requests merged in 2023-10, with the labels that each got.

#1387 Helm - Move remaining gPRC related flags to conditional
  deployment/helm/node-feature-discovery/templates/master.yaml
  deployment/helm/node-feature-discovery/templates/worker.yaml
  deployment/helm/node-feature-discovery/values.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1389 Helm - service to be only deployed when needed
  deployment/helm/node-feature-discovery/templates/service.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved, tide/merge-method-squash

#1386 feat: support raw features
  docs/usage/customization-guide.md
  source/local/local.go
  source/local/local_test.go
  source/local/testdata/features.d/features_with_labels
Labels: lgtm, cncf-cla: yes, size/L, approved

#1392 Fix serviceaccount handling for nfd-gc to be consistent with others
  deployment/helm/node-feature-discovery/templates/clusterrolebinding.yaml
  deployment/helm/node-feature-discovery/templates/nfd-gc.yaml
  deployment/helm/node-feature-discovery/templates/serviceaccount.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved, needs-ok-to-test

#1393 nfd-master: correctly clean up annotations
  pkg/nfd-master/nfd-master.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1390 Bump to Go 1.21
  Makefile
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/M, approved

#1394 nfd-master: stop creating NFD version annotations
  docs/get-started/introduction.md
  pkg/apis/nfd/v1alpha1/annotations_labels.go
  pkg/nfd-master/nfd-master-internal_test.go
  pkg/nfd-master/nfd-master.go
  test/e2e/e2e-test-config.example.yaml
  test/e2e/node_feature_discovery_test.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#1398 Refactor metrics
  pkg/nfd-master/metrics.go
  pkg/nfd-master/nfd-master.go
  pkg/nfd-topology-updater/metrics.go
  pkg/nfd-topology-updater/nfd-topology-updater.go
  pkg/nfd-worker/metrics.go
  pkg/nfd-worker/nfd-worker.go
  pkg/utils/metrics.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#1402 go.mod: bump kubernetes to v1.28.2
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/L, approved

#1403 [Release-0.14]Fix serviceaccount handling for nfd-gc to be consistent with others
  deployment/helm/node-feature-discovery/templates/clusterrolebinding.yaml
  deployment/helm/node-feature-discovery/templates/nfd-gc.yaml
  deployment/helm/node-feature-discovery/templates/serviceaccount.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1405 [release-0.13] go.mod: bump kubernetes to v1.28.2
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/L, approved

#1406 docs: clarify nfd_node_update_requests_total metric
  docs/deployment/metrics.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1400 docs: document nfd_topology_updater_build_info metric
  docs/deployment/metrics.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1404 [release-0.14] go.mod: bump kubernetes to v1.28.2
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/L, approved

#1408 [release-0.14]Update references to release v0.14.2
  Makefile
  README.md
  deployment/base/gc/gc.yaml
  deployment/base/master-worker-combined/master-worker-daemonset.yaml
  deployment/base/master/master-deployment.yaml
  deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
  deployment/base/worker-daemonset/worker-daemonset.yaml
  deployment/base/worker-job/worker-job.yaml
  deployment/helm/node-feature-discovery/Chart.yaml
  deployment/overlays/prune/master-job.yaml
  docs/_config.yml
Labels: lgtm, cncf-cla: yes, size/S, approved

#1407 nfd-gc: add metrics
  cmd/nfd-gc/main.go
  deployment/base/gc/gc.yaml
  deployment/helm/node-feature-discovery/templates/nfd-gc.yaml
  deployment/helm/node-feature-discovery/values.yaml
  docs/deployment/helm.md
  docs/deployment/metrics.md
  pkg/nfd-gc/metrics.go
  pkg/nfd-gc/nfd-gc.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#1411 Update Readme to V0.14.2
  README.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1415 feat: add parameters in helm to disable/enable nfd-master and nfd-worker
  deployment/helm/node-feature-discovery/templates/cert-manager-certs.yaml
  deployment/helm/node-feature-discovery/templates/clusterrole.yaml
  deployment/helm/node-feature-discovery/templates/clusterrolebinding.yaml
  deployment/helm/node-feature-discovery/templates/master.yaml
  deployment/helm/node-feature-discovery/templates/nfd-master-conf.yaml
  deployment/helm/node-feature-discovery/templates/nfd-worker-conf.yaml
  deployment/helm/node-feature-discovery/templates/role.yaml
  deployment/helm/node-feature-discovery/templates/rolebinding.yaml
  deployment/helm/node-feature-discovery/templates/service.yaml
  deployment/helm/node-feature-discovery/templates/serviceaccount.yaml
  deployment/helm/node-feature-discovery/templates/worker.yaml
  deployment/helm/node-feature-discovery/values.yaml
  docs/deployment/helm.md
Labels: lgtm, cncf-cla: yes, size/M, approved

#1413 examples: add example grafana dashboard
  docs/deployment/metrics.md
  examples/grafana-dashboard.json
Labels: lgtm, cncf-cla: yes, size/XXL, approved

#1397 source/custom: drop support for the legacy rule format
  docs/usage/customization-guide.md
  source/custom/custom.go
  source/custom/rules/cpuid_rule.go
  source/custom/rules/kconfig_rule.go
  source/custom/rules/loaded_kmod_rule.go
  source/custom/rules/nodename_rule.go
  source/custom/rules/pci_id_rule.go
  source/custom/rules/usb_id_rule.go
  source/custom/static_features.go
Labels: lgtm, cncf-cla: yes, size/XL, approved

#1421 test/e2e: fix source/custom nodename test
  test/e2e/node_feature_discovery_test.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#1418 Fix pkg name for test/utils/deployment
  test/e2e/utils/deployment/deployment.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1425 nfd-master: fix retry of node updates
  pkg/nfd-master/node-updater-pool.go
  test/e2e/gomega.go
  test/e2e/node_feature_discovery_test.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#1422 go.mod: update deps
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/L, approved

#1428 [release-0.14] Update deps
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/L, approved

#1426 test/e2e: stricter validation of node annotations
  test/e2e/gomega.go
  test/e2e/node_feature_discovery_test.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#1429 [release-0.13] Update deps
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/L, approved

#1433 [release-0.13] Update references to release v0.13.6
  Makefile
  README.md
  deployment/base/master-worker-combined/master-worker-daemonset.yaml
  deployment/base/master/master-deployment.yaml
  deployment/base/topology-gc/topology-gc.yaml
  deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
  deployment/base/worker-daemonset/worker-daemonset.yaml
  deployment/base/worker-job/worker-job.yaml
  deployment/helm/node-feature-discovery/Chart.yaml
  deployment/overlays/prune/master-job.yaml
  docs/_config.yml
Labels: lgtm, cncf-cla: yes, size/S, approved

#1432 [release-0.14] Update references to release v0.14.3
  Makefile
  README.md
  deployment/base/gc/gc.yaml
  deployment/base/master-worker-combined/master-worker-daemonset.yaml
  deployment/base/master/master-deployment.yaml
  deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
  deployment/base/worker-daemonset/worker-daemonset.yaml
  deployment/base/worker-job/worker-job.yaml
  deployment/helm/node-feature-discovery/Chart.yaml
  deployment/overlays/prune/master-job.yaml
  docs/_config.yml
Labels: lgtm, cncf-cla: yes, size/S, approved

#1435 Update readme to v0.14.3
  README.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1437 scripts/test-infra: bump mdlint to v0.13.0
  scripts/test-infra/mdlint.sh
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1438 scripts/test-infra: bump golangci-lint to v1.55.1
  scripts/test-infra/verify.sh
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1439 Make mdlint v0.13 happy
  docs/deployment/helm.md
  docs/deployment/metrics.md
  docs/developer-guide/index.md
  docs/get-started/introduction.md
  docs/mdl-style.rb
  docs/usage/customization-guide.md
  docs/usage/features.md
Labels: lgtm, cncf-cla: yes, size/XL, approved

#1417 Discover node features as annotations
  deployment/base/nfd-crds/nfd-api-crds.yaml
  deployment/helm/node-feature-discovery/crds/nfd-api-crds.yaml
  docs/get-started/introduction.md
  docs/usage/customization-guide.md
  pkg/apis/nfd/v1alpha1/annotations_labels.go
  pkg/apis/nfd/v1alpha1/rule.go
  pkg/apis/nfd/v1alpha1/types.go
  pkg/apis/nfd/v1alpha1/zz_generated.deepcopy.go
  pkg/nfd-master/nfd-master-internal_test.go
  pkg/nfd-master/nfd-master.go
  test/e2e/data/nodefeaturerule-5.yaml
  test/e2e/node_feature_discovery_test.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#1441 test/e2e: fix log messages
  test/e2e/node_feature_discovery_test.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1442 test/e2e: improved test logging
  test/e2e/node_feature_discovery_test.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1440 test/e2e: fix broken feature-annotations test
  test/e2e/node_feature_discovery_test.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#1443 test/e2e: cleanup feature annotations
  test/e2e/node_feature_discovery_test.go
Labels: lgtm, cncf-cla: yes, size/XS, approved
