Repository kubernetes-sigs/node-feature-discovery, pull requests merged in 2023-07, with the labels that each got.

#1253 fix typo in helm chart
  deployment/helm/node-feature-discovery/templates/master.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1255 Stop ticker in time to avoid memory leak
  pkg/nfd-topology-gc/nfd-nrt-gc.go
  pkg/nfd-topology-updater/kubeletnotifier/kubeletnotifier.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1261 [release-0.12] go.mod: update kubernetes to v1.26.6
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/L, approved

#1260 [release-0.13] go.mod: update kubernetes to v1.26.6
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/L, approved

#1259 [release-0.13] nfd-master: fix node updates on config change
  pkg/nfd-master/nfd-master.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1258 nfd-master: check for nil references in nfdAPIUpdateAllNodes
  pkg/nfd-master/nfd-master.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1265 cpu: Take cgroupsv1 into account when reading misc.capacity
  source/cpu/security_amd64.go
Labels: lgtm, cncf-cla: yes, size/S, approved, ok-to-test

#1268 go.mod: update kubernetes to v1.27.4
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/L, approved

#1270 [release-0.12] go.mod: update kubernetes to v1.26.7
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/L, approved

#1269 [release-0.13] go.mod: update kubernetes to v1.26.7
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/L, approved

#1271 [release-0.12] Update references to release v0.12.5
  Makefile
  README.md
  deployment/base/master-worker-combined/master-worker-daemonset.yaml
  deployment/base/master/master-deployment.yaml
  deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
  deployment/base/worker-daemonset/worker-daemonset.yaml
  deployment/base/worker-job/worker-job.yaml
  deployment/helm/node-feature-discovery/Chart.yaml
  deployment/overlays/prune/master-job.yaml
  docs/_config.yml
Labels: lgtm, cncf-cla: yes, size/S, approved

#1274 github: update assignees in new-release issue template
  .github/ISSUE_TEMPLATE/new-release.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1242 Enable metrics via prometheus operator
  cmd/nfd-master/main.go
  cmd/nfd-worker/main.go
  deployment/base/master/master-deployment.yaml
  deployment/base/worker-daemonset/worker-daemonset.yaml
  deployment/helm/node-feature-discovery/templates/master.yaml
  deployment/helm/node-feature-discovery/templates/prometheus.yaml
  deployment/helm/node-feature-discovery/templates/worker.yaml
  deployment/helm/node-feature-discovery/values.yaml
  deployment/overlays/prometheus/kustomization.yaml
  deployment/overlays/prometheus/monitor.yaml
  docs/deployment/helm.md
  docs/deployment/kustomize.md
  docs/deployment/metrics.md
  go.mod
  go.sum
  pkg/nfd-master/metrics.go
  pkg/nfd-master/nfd-master.go
  pkg/nfd-worker/metrics.go
  pkg/nfd-worker/nfd-worker.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#1276 README: update to v0.13.3
  README.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1279 docs: document version and deprecation policy
  docs/reference/versions.md
Labels: lgtm, cncf-cla: yes, size/M, approved

#1278 docs: fix toc of topology-updater and topology-gc reference
  docs/reference/topology-gc-commandline-reference.md
  docs/reference/topology-updater-commandline-reference.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1280 docs: remove useless TOCs
  docs/deployment/image-variants.md
  docs/deployment/uninstallation.md
  docs/usage/nfd-worker.md
Labels: lgtm, cncf-cla: yes, size/S, approved

#1282 Add optional labels to the podmonitor
  deployment/helm/node-feature-discovery/templates/prometheus.yaml
  deployment/helm/node-feature-discovery/values.yaml
  docs/deployment/helm.md
  docs/deployment/metrics.md
Labels: lgtm, cncf-cla: yes, size/XS, approved, needs-ok-to-test

#1277 docs: describe supported Kubernetes versions
  docs/deployment/index.md
  docs/get-started/introduction.md
  docs/usage/nfd-topology-updater.md
Labels: lgtm, cncf-cla: yes, size/S, approved

#1283 docs: deprecation policy for Helm chart params
  docs/reference/versions.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1256 Fix Topology Manager policy and scope not being updated after NRT creation
  cmd/nfd-topology-updater/main.go
  pkg/nfd-topology-updater/nfd-topology-updater.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#1284 generate: bump tools to their latest versions
  Dockerfile_generator
  deployment/base/nfd-crds/nfd-api-crds.yaml
  deployment/helm/node-feature-discovery/crds/nfd-api-crds.yaml
  pkg/apihelper/mock_APIHelpers.go
  pkg/labeler/labeler.pb.go
  pkg/labeler/mock_LabelerClient.go
  pkg/podres/mocks/PodResourcesListerClient.go
  source/mock_LabelSource.go
Labels: lgtm, cncf-cla: yes, size/M, approved
