Repository kubernetes-sigs/node-feature-discovery, pull requests merged in 2023-01, with the labels that each got.

#1023 Bump cpuid to v2.2.3
  docs/usage/features.md
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/S, approved

#1021 Docs: mention tainting in the intro section
  docs/get-started/introduction.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1016 test/e2e: more comprehensive test for NodeFeature objects
  test/e2e/data/nodefeature-1.yaml
  test/e2e/data/nodefeature-2.yaml
  test/e2e/node_feature_discovery.go
  test/e2e/utils/crd.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#1026 Add missing TopologyManagerPolicy
  go.mod
  go.sum
  pkg/topologypolicy/topology-policy.go
  pkg/topologypolicy/topology-policy_test.go
Labels: lgtm, cncf-cla: yes, size/L, approved, ok-to-test

#1024 Add NRT garbage collector
  cmd/nfd-topology-gc/main.go
  cmd/nfd-topology-gc/main_test.go
  deployment/base/rbac-topology-gc/kustomization.yaml
  deployment/base/rbac-topology-gc/topology-gc-clusterrole.yaml
  deployment/base/rbac-topology-gc/topology-gc-clusterrolebinding.yaml
  deployment/base/rbac-topology-gc/topology-gc-serviceaccount.yaml
  deployment/base/topology-gc/kustomization.yaml
  deployment/base/topology-gc/topology-gc.yaml
  deployment/helm/node-feature-discovery/templates/_helpers.tpl
  deployment/helm/node-feature-discovery/templates/clusterrole.yaml
  deployment/helm/node-feature-discovery/templates/clusterrolebinding.yaml
  deployment/helm/node-feature-discovery/templates/serviceaccount.yaml
  deployment/helm/node-feature-discovery/templates/topology-gc.yaml
  deployment/helm/node-feature-discovery/values.yaml
  deployment/overlays/master-worker-topologyupdater/kustomization.yaml
  deployment/overlays/topologyupdater/kustomization.yaml
  docs/deployment/helm.md
  docs/get-started/introduction.md
  docs/reference/topology-gc-commandline-reference.md
  docs/usage/custom-resources.md
  docs/usage/customization-guide.md
  docs/usage/examples-and-demos.md
  docs/usage/nfd-topology-gc.md
  pkg/nfd-topology-gc/nfd-nrt-gc.go
  pkg/nfd-topology-gc/nfd-nrt-gc_test.go
Labels: lgtm, cncf-cla: yes, size/XL, approved, ok-to-test

#1029 e2e: append `_test` suffix to test files
  test/e2e/node_feature_discovery_test.go
  test/e2e/topology_updater_test.go
Labels: lgtm, cncf-cla: yes, size/XS, approved, ok-to-test

#1028 e2e: init docker image
  test/e2e/e2e_test.go
  test/e2e/node_feature_discovery_test.go
  test/e2e/topology_updater_test.go
Labels: lgtm, cncf-cla: yes, size/M, approved, ok-to-test

#1034 nfd-master: always start gRPC server
  pkg/nfd-master/nfd-master.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#1036 [release-0.12] Update docker builder image to golang v19.5
  Makefile
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1030 docs: fix internal cross-page references by injecting .md
  docs/deployment/helm.md
  docs/deployment/kustomize.md
  docs/deployment/operator.md
  docs/deployment/tls.md
  docs/deployment/uninstallation.md
  docs/get-started/introduction.md
  docs/reference/master-commandline-reference.md
  docs/reference/worker-commandline-reference.md
  docs/reference/worker-configuration-reference.md
  docs/usage/custom-resources.md
  docs/usage/customization-guide.md
  docs/usage/features.md
  docs/usage/nfd-master.md
  docs/usage/nfd-topology-gc.md
  docs/usage/nfd-topology-updater.md
  docs/usage/nfd-worker.md
Labels: lgtm, cncf-cla: yes, size/L, approved, ok-to-test

#1039 [release-0.12] e2e: init docker image
  test/e2e/e2e_test.go
  test/e2e/node_feature_discovery.go
  test/e2e/topology_updater.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#1038 [release-0.12] Update references to release v0.12.1
  README.md
  deployment/base/master-worker-combined/master-worker-daemonset.yaml
  deployment/base/master/master-deployment.yaml
  deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
  deployment/base/worker-daemonset/worker-daemonset.yaml
  deployment/base/worker-job/worker-job.yaml
  deployment/helm/node-feature-discovery/Chart.yaml
  deployment/overlays/prune/master-job.yaml
  docs/_config.yml
  test/e2e/e2e_test.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#1041 [release-0.12] docs: Fix link for Helm docs
  deployment/helm/node-feature-discovery/README.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#956 cpu: support for detecting nx-gzip coprocessor feature
  docs/usage/customization-guide.md
  docs/usage/features.md
  source/cpu/coprocessor_ppc64le.go
  source/cpu/coprocessor_stub.go
  source/cpu/cpu.go
Labels: lgtm, cncf-cla: yes, size/M, approved, ok-to-test

#1042 README: update to release v0.12.1
  README.md
Labels: lgtm, cncf-cla: yes, size/XS, approved
