Repository kubernetes-sigs/node-feature-discovery, pull requests merged in 2023-08, with the labels that each got.

#1289 docs: align metrics documentation with latest changes on naming
  docs/deployment/metrics.md
Labels: lgtm, cncf-cla: yes, size/S, approved

#1293 source/local: trim whitespace from input
  source/local/local.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1291 nfd-master: use term node update instead of labeling
  pkg/nfd-master/nfd-master.go
  pkg/nfd-master/node-updater-pool.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1296 docs: document -metrics flag in command line reference
  docs/reference/master-commandline-reference.md
  docs/reference/worker-commandline-reference.md
Labels: lgtm, cncf-cla: yes, size/S, approved

#1287 fix empty hugepages in some numa nodes caused no such file or directory errors
  pkg/utils/memory_resources.go
Labels: lgtm, cncf-cla: yes, size/XS, approved, ok-to-test

#1299 scripts/test-infra: update logcheck tool to v0.6.0
  scripts/test-infra/verify.sh
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1300 scripts/test-infra: bump golangci-lint to v1.54.0
  scripts/test-infra/verify.sh
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1302 Update kubernetes to v1.28.0
  go.mod
  go.sum
  test/e2e/topology_updater_test.go
Labels: lgtm, cncf-cla: yes, size/XL, approved

#1303 docs: update github-pages gem to v228
  docs/Gemfile
  docs/Gemfile.lock
Labels: lgtm, cncf-cla: yes, size/M, approved

#1306 topology-gc: fix Stop
  pkg/nfd-topology-gc/nfd-nrt-gc.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1309 topology-gc: rename run()
  pkg/nfd-topology-gc/nfd-nrt-gc.go
  pkg/nfd-topology-gc/nfd-nrt-gc_test.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#1310 topology-gc: rename runGC to garbageCollect()
  pkg/nfd-topology-gc/nfd-nrt-gc.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1295 nfd-topology-updater: add metrics support
  cmd/nfd-topology-updater/main.go
  deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
  deployment/helm/node-feature-discovery/templates/topologyupdater.yaml
  deployment/helm/node-feature-discovery/values.yaml
  docs/deployment/helm.md
  docs/deployment/metrics.md
  docs/reference/topology-updater-commandline-reference.md
  pkg/nfd-topology-updater/metrics.go
  pkg/nfd-topology-updater/nfd-topology-updater.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#1308 topology-gc: move initial GC out of startNodeInformer()
  pkg/nfd-topology-gc/nfd-nrt-gc.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1311 topology-gc: simplify listing of node objects
  pkg/nfd-topology-gc/nfd-nrt-gc.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#1290 metrics: additional metrics for nfd-master
  docs/deployment/metrics.md
  pkg/nfd-master/metrics.go
  pkg/nfd-master/nfd-master.go
  pkg/nfd-master/node-updater-pool.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#1305 Garbage collection of NodeFeature objects
  cmd/nfd-gc/main.go
  cmd/nfd-gc/main_test.go
  deployment/base/gc/gc-clusterrole.yaml
  deployment/base/gc/gc-clusterrolebinding.yaml
  deployment/base/gc/gc-serviceaccount.yaml
  deployment/base/gc/gc.yaml
  deployment/base/gc/kustomization.yaml
  deployment/base/rbac-topology-gc/kustomization.yaml
  deployment/helm/node-feature-discovery/templates/_helpers.tpl
  deployment/helm/node-feature-discovery/templates/clusterrole.yaml
  deployment/helm/node-feature-discovery/templates/clusterrolebinding.yaml
  deployment/helm/node-feature-discovery/templates/nfd-gc.yaml
  deployment/helm/node-feature-discovery/templates/serviceaccount.yaml
  deployment/helm/node-feature-discovery/values.yaml
  deployment/overlays/master-worker-topologyupdater/kustomization.yaml
  deployment/overlays/topologyupdater/kustomization.yaml
  docs/deployment/helm.md
  docs/get-started/introduction.md
  docs/reference/gc-commandline-reference.md
  docs/usage/nfd-gc.md
  docs/usage/nfd-topology-gc.md
  pkg/nfd-gc/nfd-gc.go
  pkg/nfd-gc/nfd-gc_test.go
  test/e2e/nfd_gc_test.go
  test/e2e/utils/crd.go
  test/e2e/utils/deployment/deployment.go
  test/e2e/utils/noderesourcetopology.go
  test/e2e/utils/pod/pod.go
  test/e2e/utils/rbac.go
Labels: lgtm, cncf-cla: yes, size/XL, approved

#1297 topology-updater: make -version always runnable
  cmd/nfd-topology-updater/main.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#1320 Makefile: increase golangci-lint timeout to 10min
  Makefile
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1318 [release-0.13] Bump kubernetes to v1.28.1
  go.mod
  go.sum
  pkg/podres/client.go
  pkg/podres/mock_PodResourcesListerClient.go
  pkg/podres/mocks/PodResourcesListerClient.go
  pkg/resourcemonitor/podresourcesscanner_test.go
  test/e2e/node_feature_discovery_test.go
  test/e2e/topology_updater_test.go
  test/e2e/utils/configmap.go
  test/e2e/utils/crd.go
  test/e2e/utils/node.go
  test/e2e/utils/noderesourcetopology.go
  test/e2e/utils/pod/pod.go
  test/e2e/utils/rbac.go
  test/e2e/utils/service.go
Labels: lgtm, cncf-cla: yes, size/XXL, approved

#1319 docs: use ruby docker image for building docs
  Makefile
  docs/Gemfile
  docs/Gemfile.lock
Labels: lgtm, cncf-cla: yes, size/S, approved
