Repository kubernetes-sigs/node-feature-discovery, pull requests merged in 2023-06, with the labels that each got.

#1236 [release-0.13] Prepare for release 0.13.2
  Makefile
  README.md
  deployment/base/master-worker-combined/master-worker-daemonset.yaml
  deployment/base/master/master-deployment.yaml
  deployment/base/topology-gc/topology-gc.yaml
  deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
  deployment/base/worker-daemonset/worker-daemonset.yaml
  deployment/base/worker-job/worker-job.yaml
  deployment/helm/node-feature-discovery/Chart.yaml
  deployment/overlays/prune/master-job.yaml
  docs/_config.yml
Labels: lgtm, cncf-cla: yes, size/S, approved

#1237 [release-0.12] Update references to release v0.12.4
  Makefile
  README.md
  deployment/base/master-worker-combined/master-worker-daemonset.yaml
  deployment/base/master/master-deployment.yaml
  deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
  deployment/base/worker-daemonset/worker-daemonset.yaml
  deployment/base/worker-job/worker-job.yaml
  deployment/helm/node-feature-discovery/Chart.yaml
  deployment/overlays/prune/master-job.yaml
  docs/_config.yml
Labels: lgtm, cncf-cla: yes, size/S, approved

#1238 Update README to v0.13.2
  README.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1133 feat: parallelize nodes update
  Makefile
  cmd/nfd-master/main.go
  deployment/components/master-config/nfd-master.conf.example
  deployment/helm/node-feature-discovery/templates/master.yaml
  deployment/helm/node-feature-discovery/values.yaml
  docs/deployment/helm.md
  docs/reference/master-commandline-reference.md
  docs/reference/master-configuration-reference.md
  pkg/nfd-master/nfd-master-internal_test.go
  pkg/nfd-master/nfd-master.go
  pkg/nfd-master/node-updater-pool.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#1240 cpu: Discover TDX guests based on cpuid information
  deployment/components/worker-config/nfd-worker.conf.example
  deployment/helm/node-feature-discovery/values.yaml
  docs/reference/worker-configuration-reference.md
  docs/usage/customization-guide.md
  docs/usage/features.md
  go.mod
  go.sum
  source/cpu/cpu.go
  source/cpu/security_amd64.go
Labels: lgtm, cncf-cla: yes, size/S, approved, ok-to-test

#1243 deployment/kustomize: use a named port for nfd gRPC service
  deployment/base/master/master-deployment.yaml
  deployment/base/master/master-service.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1245 Fix missing apostrophe for jq
  README.md
  docs/get-started/index.md
  docs/get-started/quick-start.md
Labels: lgtm, cncf-cla: yes, size/XS, approved, ok-to-test

#1244 Fix a typo on nfd-master cmd
  cmd/nfd-master/main.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1247 Docs: Fix typo on customization-guide
  docs/usage/customization-guide.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1182 hooks: disable hooks by default from v0.14
  deployment/components/worker-config/nfd-worker.conf.example
  deployment/helm/node-feature-discovery/values.yaml
  docs/reference/worker-configuration-reference.md
  docs/usage/customization-guide.md
  source/local/local.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#1248 Remove pkg's imported twice
  pkg/nfd-master/nfd-master-internal_test.go
  test/e2e/node_feature_discovery_test.go
Labels: lgtm, cncf-cla: yes, size/S, approved, ok-to-test
