Repository kubernetes-sigs/node-feature-discovery, pull requests merged in 2023-09, with the labels that each got.

#1324 README: update to v0.13.4
  README.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1252 test: add node updater pool unit tests
  pkg/nfd-master/node-updater-pool_test.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#1321 docs: nfd-updater: clarify accounting
  docs/usage/nfd-topology-updater.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1325 nfd-updater: events: enable timer-only flow
  pkg/nfd-topology-updater/kubeletnotifier/kubeletnotifier.go
  pkg/nfd-topology-updater/nfd-topology-updater.go
  test/e2e/topology_updater_test.go
  test/e2e/utils/noderesourcetopology.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#1326 docs: demote hooks in the customization guide
  docs/usage/customization-guide.md
Labels: lgtm, cncf-cla: yes, size/M, approved

#1285 Feat: add expiry date for feature files
  docs/usage/customization-guide.md
  source/local/local.go
  source/local/local_test.go
  source/local/testdata/features.d/expired_feature
  source/local/testdata/features.d/feature_with_comments
  source/local/testdata/features.d/multiple_expiration_dates
  source/local/testdata/features.d/unparsable_expiry_comment
  source/local/testdata/features.d/valid_feature
Labels: lgtm, cncf-cla: yes, size/L, approved

#1327 Dockerfile: bump grpc-health-probe to v0.4.19
  Dockerfile
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1328 e2e/test: make the nfd-gc test pass on one-node cluster
  test/e2e/nfd_gc_test.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#1329 Enable NodeFeature API by default
  cmd/nfd-master/main.go
  cmd/nfd-worker/main.go
  deployment/helm/node-feature-discovery/values.yaml
  docs/deployment/helm.md
  docs/get-started/introduction.md
  docs/reference/master-commandline-reference.md
  docs/reference/worker-commandline-reference.md
  docs/usage/custom-resources.md
  docs/usage/customization-guide.md
  docs/usage/nfd-master.md
  test/e2e/node_feature_discovery_test.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#1332 tls.md: Add note
  docs/deployment/tls.md
Labels: lgtm, cncf-cla: yes, size/XS, approved, tide/merge-method-squash

#1333 nfd_gc_test.go: fix multiple import of same pkg
  test/e2e/nfd_gc_test.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1335 feat: add feature file size limit
  docs/usage/customization-guide.md
  source/local/local.go
  source/local/testdata/features.d/big_file
Labels: lgtm, cncf-cla: yes, size/L, approved

#1336 sources/custom: convert static rules to new format
  source/custom/custom.go
  source/custom/static_features.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#1338 nfd-master: add config file options for logging
  cmd/nfd-master/main.go
  cmd/nfd-master/main_test.go
  deployment/components/master-config/nfd-master.conf.example
  deployment/helm/node-feature-discovery/values.yaml
  docs/reference/master-configuration-reference.md
  pkg/nfd-master/nfd-master.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#1334 Deprecate gRPC API
  cmd/nfd-master/main.go
  cmd/nfd-worker/main.go
  docs/deployment/helm.md
  docs/deployment/tls.md
  docs/developer-guide/index.md
  docs/reference/master-commandline-reference.md
  docs/reference/worker-commandline-reference.md
  docs/usage/customization-guide.md
  docs/usage/nfd-master.md
Labels: lgtm, cncf-cla: yes, size/L, approved

#1331 Helm: conditionally add annotations if defined
  deployment/helm/node-feature-discovery/templates/master.yaml
  deployment/helm/node-feature-discovery/templates/nfd-gc.yaml
  deployment/helm/node-feature-discovery/templates/topologyupdater.yaml
  deployment/helm/node-feature-discovery/templates/worker.yaml
  deployment/helm/node-feature-discovery/values.yaml
  docs/deployment/helm.md
Labels: lgtm, cncf-cla: yes, size/M, approved, ok-to-test

#1340 [release-0.14] Update references to release v0.14
  Makefile
  README.md
  deployment/base/gc/gc.yaml
  deployment/base/master-worker-combined/master-worker-daemonset.yaml
  deployment/base/master/master-deployment.yaml
  deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
  deployment/base/worker-daemonset/worker-daemonset.yaml
  deployment/base/worker-job/worker-job.yaml
  deployment/helm/node-feature-discovery/Chart.yaml
  deployment/helm/node-feature-discovery/README.md
  deployment/helm/node-feature-discovery/values.yaml
  deployment/overlays/prune/master-job.yaml
  docs/_config.yml
  node-feature-discovery-chart-0.14.0.tgz
  node-feature-discovery-chart-0.14.0.tgz.prov
Labels: lgtm, cncf-cla: yes, size/M, approved

#1343 go.mod: bump github.com/cyphar/filepath-securejoin from 0.2.3 to 0.2.4
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1345 README: update to v0.14.0
  README.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1341 chore: introduce a commong klog handling for cmd/nfd-*
  cmd/nfd-master/main.go
  cmd/nfd-worker/main.go
  cmd/nfd-worker/main_test.go
  pkg/nfd-master/nfd-master.go
  pkg/nfd-worker/nfd-worker.go
  pkg/utils/klog/klog.go
  pkg/utils/klog/klog_test.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#1350 cpu: drop the deprecated sgx and se labels
  docs/usage/customization-guide.md
  docs/usage/features.md
  source/cpu/cpu.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#1351 source/local: simplify feature file size checking
  source/local/local.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#1355 scripts/update-gh-pages: sync OWNERS from master to gh-pages
  scripts/github/update-gh-pages.sh
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1358 github: prevent parallel runs of gh-pages update
  .github/workflows/gh-pages.yml
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1359 github: separate workflow for helm repo index update
  .github/workflows/gh-pages.yml
  .github/workflows/release.yml
  scripts/github/update-gh-pages.sh
  scripts/github/update-helm-repo.sh
Labels: lgtm, cncf-cla: yes, size/L, approved

#1361 [release-0.14] github: separate workflow for helm repo index update
  .github/workflows/gh-pages.yml
  .github/workflows/release.yml
  scripts/github/update-gh-pages.sh
  scripts/github/update-helm-repo.sh
Labels: lgtm, cncf-cla: yes, size/L, approved

#1362 [release-0.13] github: separate workflow for helm repo index update
  .github/workflows/gh-pages.yml
  .github/workflows/release.yml
  scripts/github/update-gh-pages.sh
  scripts/github/update-helm-repo.sh
Labels: lgtm, cncf-cla: yes, size/L, approved

#1356 gh-pages: Add nojekyll file
  .nojekyll
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1360 [release-0.12] docs: mark release v0.12 as unsupported
  docs/_includes/templates/content.liquid
Labels: lgtm, cncf-cla: yes, size/S, approved

#1364 deployment/helm: fix namespace of nfd-worker role and rolebinding
  deployment/helm/node-feature-discovery/templates/role.yaml
  deployment/helm/node-feature-discovery/templates/rolebinding.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1365 deployment/helm: fix handling of enableNodeFeatureApi parameter
  deployment/helm/node-feature-discovery/templates/master.yaml
  deployment/helm/node-feature-discovery/templates/worker.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved

#1373 Build statically linked binaries
  Dockerfile
  Makefile
  docs/deployment/image-variants.md
Labels: lgtm, cncf-cla: yes, size/S, approved

#1374 [release-0.14] Update references to release v0.14.1
  README.md
  deployment/base/gc/gc.yaml
  deployment/base/master-worker-combined/master-worker-daemonset.yaml
  deployment/base/master/master-deployment.yaml
  deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
  deployment/base/worker-daemonset/worker-daemonset.yaml
  deployment/base/worker-job/worker-job.yaml
  deployment/helm/node-feature-discovery/Chart.yaml
  deployment/overlays/prune/master-job.yaml
  docs/_config.yml
Labels: lgtm, cncf-cla: yes, size/S, approved

#1375 [release-0.13] Update references to release v0.13.5 and bump Go to v1.20.8
  Makefile
  README.md
  deployment/base/master-worker-combined/master-worker-daemonset.yaml
  deployment/base/master/master-deployment.yaml
  deployment/base/topology-gc/topology-gc.yaml
  deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
  deployment/base/worker-daemonset/worker-daemonset.yaml
  deployment/base/worker-job/worker-job.yaml
  deployment/helm/node-feature-discovery/Chart.yaml
  deployment/overlays/prune/master-job.yaml
  docs/_config.yml
Labels: lgtm, cncf-cla: yes, size/S, approved

#1046 Replace gRPC health probe utility with k8s built-in health probe
  Dockerfile
  deployment/base/master-worker-combined/master-worker-daemonset.yaml
  deployment/base/master/master-deployment.yaml
  deployment/helm/node-feature-discovery/templates/cert-manager-certs.yaml
  deployment/helm/node-feature-discovery/templates/master.yaml
  deployment/overlays/samples/cert-manager/master-cert.yaml
Labels: lgtm, cncf-cla: yes, size/M, approved

#1377 README: update to v0.14.1
  README.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1378 nfd-master: fix filtering of extended resources
  pkg/nfd-master/nfd-master.go
  test/e2e/data/nodefeaturerule-4.yaml
  test/e2e/node_feature_discovery_test.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#1382 apis/nfd: drop one stale comment line
  pkg/apis/nfd/v1alpha1/types.go
Labels: lgtm, cncf-cla: yes, size/XS, approved
