Repository kubernetes-sigs/node-feature-discovery, pull requests merged in 2023-05, with the labels that each got.

#1202 nfd-master: refactor filtering of labels, taints and ERs
  pkg/nfd-master/nfd-master.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#1204 helm: fix mount for nfd-master config
  deployment/helm/node-feature-discovery/templates/master.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1205 [release-0.13] helm: fix mount for nfd-master config
  deployment/helm/node-feature-discovery/templates/master.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1185 nfd-master: fix resync period config option
  cmd/nfd-master/main.go
  pkg/nfd-master/nfd-api-controller.go
  pkg/nfd-master/nfd-master.go
  test/e2e/node_feature_discovery_test.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#1207 deployment/helm: fix default for kubeletStateDir parameter
  deployment/helm/node-feature-discovery/values.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1208 deployment/kustomize: drop pod-resources mount for topology-updater
  deployment/components/topology-updater/topologyupdater-mounts.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1184 test/e2e: refactor matching of node properties
  test/e2e/gomega.go
  test/e2e/node_feature_discovery_test.go
Labels: lgtm, cncf-cla: yes, size/XL, approved

#1212 deployment/helm: avoid overlapping mount paths on topology-updater
  deployment/helm/node-feature-discovery/templates/topologyupdater.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1213 deployment/helm: user dedicated serviceaccount for topology-updater
  deployment/helm/node-feature-discovery/templates/clusterrolebinding.yaml
  deployment/helm/node-feature-discovery/templates/serviceaccount.yaml
  deployment/helm/node-feature-discovery/values.yaml
  docs/deployment/helm.md
Labels: lgtm, cncf-cla: yes, size/S, approved

#1211 deployment/helm: improve handling of topologyUpdater.kubeletStateFiles
  deployment/helm/node-feature-discovery/templates/topologyupdater.yaml
  docs/deployment/helm.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1216 [release-0.12] deployment/helm: user dedicated serviceaccount for topology-updater
  deployment/helm/node-feature-discovery/templates/clusterrolebinding.yaml
  deployment/helm/node-feature-discovery/templates/serviceaccount.yaml
  deployment/helm/node-feature-discovery/values.yaml
  docs/deployment/helm.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1218 topology-updater: use node IP in the default configz URI
  cmd/nfd-topology-updater/main.go
  deployment/components/topology-updater/env.yaml
  deployment/components/topology-updater/kustomization.yaml
  deployment/helm/node-feature-discovery/templates/topologyupdater.yaml
  docs/reference/topology-updater-commandline-reference.md
Labels: lgtm, cncf-cla: yes, size/S, approved

#1221 e2e: delete CRs only if found
  test/e2e/node_feature_discovery_test.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#1219 Add leader election for nfd-master
  cmd/nfd-master/main.go
  deployment/base/rbac/master-clusterrole.yaml
  deployment/components/master-config/nfd-master.conf.example
  deployment/helm/node-feature-discovery/templates/clusterrole.yaml
  deployment/helm/node-feature-discovery/templates/master.yaml
  deployment/helm/node-feature-discovery/values.yaml
  docs/reference/master-commandline-reference.md
  docs/reference/master-configuration-reference.md
  docs/usage/nfd-master.md
  pkg/nfd-master/nfd-master-internal_test.go
  pkg/nfd-master/nfd-master.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#1224 [release-0.13] go.mod: bump kubernetes to v1.26.5
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/L, approved

#1225 [release-0.12] go.mod: bump kubernetes to v1.26.5
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/L, approved

#1227 nfd-master: use close for stop channel
  pkg/nfd-master/nfd-master.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1230 scripts/test-infra: bump golangci-lint to v1.52.2
  scripts/test-infra/verify.sh
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1228 nfd-master: add validation of label names and values
  pkg/nfd-master/nfd-master-internal_test.go
  pkg/nfd-master/nfd-master.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#1223 Migrate to structured logging
  cmd/nfd-master/main.go
  cmd/nfd-topology-gc/main.go
  cmd/nfd-topology-updater/main.go
  cmd/nfd-worker/main.go
  pkg/apis/nfd/v1alpha1/expression.go
  pkg/apis/nfd/v1alpha1/rule.go
  pkg/nfd-master/nfd-api-controller.go
  pkg/nfd-master/nfd-master.go
  pkg/nfd-topology-gc/nfd-nrt-gc.go
  pkg/nfd-topology-updater/kubeletnotifier/kubeletnotifier.go
  pkg/nfd-topology-updater/nfd-topology-updater.go
  pkg/nfd-worker/nfd-worker.go
  pkg/resourcemonitor/excludelist.go
  pkg/resourcemonitor/noderesourcesaggregator.go
  pkg/resourcemonitor/podresourcesscanner.go
  pkg/utils/dump.go
  pkg/utils/fswatcher.go
  pkg/utils/memory_resources.go
  source/cpu/coprocessor_ppc64le.go
  source/cpu/cpu.go
  source/cpu/cstate_amd64.go
  source/cpu/power_amd64.go
  source/cpu/pstate_amd64.go
  source/cpu/rdt_amd64.go
  source/custom/custom.go
  source/custom/directory_features.go
  source/fake/fake.go
  source/kernel/kernel.go
  source/kernel/selinux.go
  source/local/local.go
  source/memory/memory.go
  source/network/network.go
  source/pci/pci.go
  source/pci/utils.go
  source/source.go
  source/storage/storage.go
  source/system/system.go
  source/usb/usb.go
  source/usb/utils.go
Labels: lgtm, cncf-cla: yes, size/XL, approved

#1233 [release-0.13] nfd-master: add validation of label names and values
  pkg/nfd-master/nfd-master-internal_test.go
  pkg/nfd-master/nfd-master.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#1234 [release-0.12] nfd-master: add validation of label names and values
  pkg/nfd-master/nfd-master-internal_test.go
  pkg/nfd-master/nfd-master.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#1235 scripts/test-infra: add logcheck to verify script
  scripts/test-infra/logcheck.conf
  scripts/test-infra/verify.sh
Labels: lgtm, cncf-cla: yes, size/XS, approved
