Repository kubernetes-sigs/node-feature-discovery, pull requests merged in 2023-03, with the labels that each got.

#1074 test/e2e: cleanup NodeFeature objects before/after tests
  test/e2e/node_feature_discovery_test.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#1066 docs: fix usage customization guide typos
  docs/usage/customization-guide.md
Labels: lgtm, cncf-cla: yes, size/M, approved, ok-to-test

#1069 test: add code coverage reporting
  Makefile
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1078 helm: fix topology-updater rbac
  deployment/helm/node-feature-discovery/templates/clusterrole.yaml
  deployment/helm/node-feature-discovery/values.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved

#1080 deployment: fixes for mounting kubelet config
  deployment/components/topology-updater/topologyupdater-mounts.yaml
  deployment/helm/node-feature-discovery/templates/topologyupdater.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved

#1076 Update worker-configuration-reference.md
  docs/reference/worker-configuration-reference.md
Labels: lgtm, cncf-cla: yes, size/S, approved, ok-to-test

#1082 scripts/test-infra: bump golangci-lint to v1.51.2
  scripts/test-infra/verify.sh
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1077 go.mod: update kubernetes to v1.26.2
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/L, approved

#1087 pkg/utils: add UnmarshalJSON method to StringSetVal
  pkg/utils/flags.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#1083 codegen: fix code-generation
  Dockerfile_generator
  hack/generate.sh
  pkg/apihelper/mock_APIHelpers.go
  pkg/apis/nfd/v1alpha1/generated.pb.go
  pkg/apis/nfd/v1alpha1/generated.proto
  pkg/generated/clientset/versioned/clientset.go
  pkg/generated/clientset/versioned/doc.go
  pkg/generated/clientset/versioned/fake/clientset_generated.go
  pkg/generated/clientset/versioned/fake/doc.go
  pkg/generated/clientset/versioned/fake/register.go
  pkg/generated/clientset/versioned/scheme/doc.go
  pkg/generated/clientset/versioned/scheme/register.go
  pkg/generated/clientset/versioned/typed/nfd/v1alpha1/doc.go
  pkg/generated/clientset/versioned/typed/nfd/v1alpha1/fake/doc.go
  pkg/generated/clientset/versioned/typed/nfd/v1alpha1/fake/fake_nfd_client.go
  pkg/generated/clientset/versioned/typed/nfd/v1alpha1/fake/fake_nodefeature.go
  pkg/generated/clientset/versioned/typed/nfd/v1alpha1/fake/fake_nodefeaturerule.go
  pkg/generated/clientset/versioned/typed/nfd/v1alpha1/generated_expansion.go
  pkg/generated/clientset/versioned/typed/nfd/v1alpha1/nfd_client.go
  pkg/generated/clientset/versioned/typed/nfd/v1alpha1/nodefeature.go
  pkg/generated/clientset/versioned/typed/nfd/v1alpha1/nodefeaturerule.go
  pkg/generated/informers/externalversions/factory.go
  pkg/generated/informers/externalversions/generic.go
  pkg/generated/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/generated/informers/externalversions/nfd/interface.go
  pkg/generated/informers/externalversions/nfd/v1alpha1/interface.go
  pkg/generated/informers/externalversions/nfd/v1alpha1/nodefeature.go
  pkg/generated/informers/externalversions/nfd/v1alpha1/nodefeaturerule.go
  pkg/generated/listers/nfd/v1alpha1/expansion_generated.go
  pkg/generated/listers/nfd/v1alpha1/nodefeature.go
  pkg/generated/listers/nfd/v1alpha1/nodefeaturerule.go
  pkg/labeler/mock_LabelerClient.go
  source/mock_LabelSource.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#1090 kustomize: trim prune overlay
  deployment/overlays/prune/master-clusterrole.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1085 gitignore: ignore codecov coverage report
  .gitignore
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1031 topology-updater: reactive updates
  cmd/nfd-topology-updater/main.go
  deployment/components/topology-updater/topologyupdater-mounts.yaml
  deployment/helm/node-feature-discovery/templates/topologyupdater.yaml
  deployment/helm/node-feature-discovery/values.yaml
  docs/deployment/helm.md
  docs/reference/topology-updater-commandline-reference.md
  docs/usage/nfd-topology-updater.md
  pkg/nfd-topology-updater/kubeletnotifier/kubeletnotifier.go
  pkg/nfd-topology-updater/nfd-topology-updater.go
  test/e2e/topology_updater_test.go
  test/e2e/utils/pod/pod.go
Labels: lgtm, cncf-cla: yes, size/L, approved, ok-to-test

#1092 chore: add debug dump of nfd worker configuration
  pkg/nfd-worker/nfd-worker.go
Labels: lgtm, cncf-cla: yes, size/XS, approved, ok-to-test

#1097 cpu: expose AMD SEV support
  docs/usage/customization-guide.md
  docs/usage/features.md
  source/cpu/cpu.go
  source/cpu/security_amd64.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#1079 cpu: Expose the total number of keys for TDX
  docs/usage/customization-guide.md
  docs/usage/features.md
  source/cpu/security_amd64.go
Labels: lgtm, cncf-cla: yes, size/M, approved, ok-to-test

#1106 go.mod: update kubernetes to v1.26.3
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/L, approved

#1107 [release-0.12] go.mod: update kubernetes to v1.26.2
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/L, approved
