Repository kubernetes-sigs/node-feature-discovery, pull requests merged in 2023-04, with the labels that each got.

#1110 Update references to release v0.12.2
  Makefile
  README.md
  deployment/base/master-worker-combined/master-worker-daemonset.yaml
  deployment/base/master/master-deployment.yaml
  deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
  deployment/base/worker-daemonset/worker-daemonset.yaml
  deployment/base/worker-job/worker-job.yaml
  deployment/helm/node-feature-discovery/Chart.yaml
  deployment/overlays/prune/master-job.yaml
  docs/_config.yml
Labels: lgtm, cncf-cla: yes, size/S, approved

#1112 README: update to release v0.12.2
  README.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1084 feat: add master config file
  Makefile
  cmd/nfd-master/main.go
  deployment/base/master/master-deployment.yaml
  deployment/components/common/kustomization.yaml
  deployment/components/common/master-mounts.yaml
  deployment/components/master-config/kustomization.yaml
  deployment/components/master-config/nfd-master.conf.example
  deployment/helm/node-feature-discovery/templates/master.yaml
  deployment/helm/node-feature-discovery/templates/nfd-master-conf.yaml
  deployment/helm/node-feature-discovery/values.yaml
  deployment/overlays/default-combined/kustomization.yaml
  deployment/overlays/default-job/kustomization.yaml
  deployment/overlays/default/kustomization.yaml
  deployment/overlays/master-worker-topologyupdater/kustomization.yaml
  docs/deployment/helm.md
  docs/reference/master-commandline-reference.md
  docs/reference/master-configuration-reference.md
  docs/reference/topology-gc-commandline-reference.md
  docs/reference/topology-updater-commandline-reference.md
  docs/reference/topology-updater-configuration-reference.md
  docs/reference/worker-configuration-reference.md
  docs/usage/nfd-master.md
  pkg/nfd-master/nfd-master-internal_test.go
  pkg/nfd-master/nfd-master.go
  pkg/nfd-master/nfd-master_test.go
  pkg/nfd-worker/nfd-worker_test.go
  test/e2e/node_feature_discovery_test.go
  test/e2e/utils/configmap.go
Labels: lgtm, cncf-cla: yes, size/XL, approved, ok-to-test

#1116 test/e2e: wait for CRD deletion to complete
  test/e2e/utils/crd.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#1117 test/e2e: refactor nfd pod configuration
  test/e2e/node_feature_discovery_test.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#1118 nfd-master: disallow unprefixed and kubernetes taints
  docs/usage/customization-guide.md
  pkg/apis/nfd/v1alpha1/annotations_labels.go
  pkg/nfd-master/nfd-master.go
  test/e2e/data/nodefeaturerule-3-updated.yaml
  test/e2e/data/nodefeaturerule-3.yaml
  test/e2e/node_feature_discovery_test.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#1119 nfd-master: fix node update
  pkg/nfd-master/nfd-master-internal_test.go
  pkg/nfd-master/nfd-master.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#1100 Advertise RDT L3 num_closid
  docs/usage/customization-guide.md
  source/cpu/cpu.go
  source/cpu/rdt_amd64.go
  source/cpu/rdt_stub.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#1099 Create extended resources with NodeFeatureRule
  deployment/base/nfd-crds/nfd-api-crds.yaml
  deployment/base/rbac/master-clusterrole.yaml
  deployment/helm/node-feature-discovery/crds/nfd-api-crds.yaml
  deployment/helm/node-feature-discovery/templates/clusterrole.yaml
  docs/usage/customization-guide.md
  examples/nodefeaturerule.yaml
  pkg/apis/nfd/v1alpha1/annotations_labels.go
  pkg/apis/nfd/v1alpha1/rule.go
  pkg/apis/nfd/v1alpha1/types.go
  pkg/apis/nfd/v1alpha1/zz_generated.deepcopy.go
  pkg/nfd-master/nfd-master-internal_test.go
  pkg/nfd-master/nfd-master.go
  test/e2e/data/nodefeaturerule-4.yaml
  test/e2e/node_feature_discovery_test.go
  test/e2e/utils/rbac.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#1121 Dockerfile: bump grpc-health-probe to v0.4.17
  Dockerfile
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1122 docs: add missing mentions of extended resources and taints
  docs/deployment/uninstallation.md
  docs/get-started/introduction.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1123 nfd-master: increase controller resync period to 1 hour
  pkg/nfd-master/nfd-api-controller.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1127 nfd-master: re-try on node update failures
  pkg/nfd-master/nfd-master.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#1128 Makefile: set e2e test timeout to 1 hour
  Makefile
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1126 nfd-master: deprecate the -resource-labels flag
  cmd/nfd-master/main.go
  docs/reference/master-commandline-reference.md
  docs/reference/master-configuration-reference.md
Labels: lgtm, cncf-cla: yes, size/S, approved

#1130 source/cpu: don't create cpu-security.tdx.total_keys label
  docs/usage/features.md
  source/cpu/cpu.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1129 cpu: Expose SGX EPC resource
  docs/usage/customization-guide.md
  docs/usage/features.md
  source/cpu/cpu.go
  source/cpu/security_amd64.go
Labels: lgtm, cncf-cla: yes, size/S, approved, ok-to-test

#1132 [release-0.6] docs: mark release as unsupported
  docs/_includes/class/content-wrap.liquid
Labels: lgtm, cncf-cla: yes, size/S, approved

#1095 e2e: add codecov uploader configuration
  codecov.yml
  scripts/test-infra/verify.sh
Labels: lgtm, cncf-cla: yes, size/S, approved

#1140 OWNERS: add PiotrProkop as a reviewer
  OWNERS
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1145 Dockerfile: bump grpc-health-probe to v0.4.18
  Dockerfile
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1143 [release-0.9] docs: mark release v0.9 as unsupported
  docs/_includes/class/content-wrap.liquid
Labels: lgtm, cncf-cla: yes, size/S, approved

#1141 [release-0.7] docs: mark release v0.7 as unsupported
  docs/_includes/class/content-wrap.liquid
Labels: lgtm, cncf-cla: yes, size/S, approved

#1142 [release-0.8] docs: mark release v0.8 as unsupported
  docs/_includes/class/content-wrap.liquid
Labels: lgtm, cncf-cla: yes, size/S, approved

#1148 [release-0.12] Update references to release v0.12.3
  Makefile
  README.md
  deployment/base/master-worker-combined/master-worker-daemonset.yaml
  deployment/base/master/master-deployment.yaml
  deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
  deployment/base/worker-daemonset/worker-daemonset.yaml
  deployment/base/worker-job/worker-job.yaml
  deployment/helm/node-feature-discovery/Chart.yaml
  deployment/overlays/prune/master-job.yaml
  docs/_config.yml
Labels: lgtm, cncf-cla: yes, size/S, approved

#1149 cpu: expose the total number of AMD SEV ASID and ES
  docs/usage/features.md
  source/cpu/cpu.go
  source/cpu/security_amd64.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#1151 hack/prepare-release.sh: fix name of one e2e test file
  hack/prepare-release.sh
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1152 [release-0.13] Update references to release v0.13.0
  Makefile
  README.md
  deployment/base/master-worker-combined/master-worker-daemonset.yaml
  deployment/base/master/master-deployment.yaml
  deployment/base/topology-gc/topology-gc.yaml
  deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
  deployment/base/worker-daemonset/worker-daemonset.yaml
  deployment/base/worker-job/worker-job.yaml
  deployment/helm/node-feature-discovery/Chart.yaml
  deployment/helm/node-feature-discovery/README.md
  deployment/helm/node-feature-discovery/values.yaml
  deployment/overlays/prune/master-job.yaml
  docs/_config.yml
Labels: lgtm, cncf-cla: yes, size/M, approved

#1150 [release-0.11] docs: mark release v0.11 as unsupported
  docs/_includes/templates/content.liquid
Labels: lgtm, cncf-cla: yes, size/S, approved

#1154 test/e2e: use proper context
  test/e2e/node_feature_discovery_test.go
  test/e2e/topology_updater_test.go
  test/e2e/utils/configmap.go
  test/e2e/utils/crd.go
  test/e2e/utils/node.go
  test/e2e/utils/noderesourcetopology.go
  test/e2e/utils/pod/pod.go
  test/e2e/utils/rbac.go
  test/e2e/utils/service.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#1155 deps: Update kubernetes to v1.27.1
  go.mod
  go.sum
  pkg/podres/client.go
  pkg/podres/mock_PodResourcesListerClient.go
  pkg/podres/mocks/PodResourcesListerClient.go
  pkg/resourcemonitor/podresourcesscanner_test.go
  test/e2e/node_feature_discovery_test.go
  test/e2e/topology_updater_test.go
  test/e2e/utils/crd.go
  test/e2e/utils/noderesourcetopology.go
  test/e2e/utils/pod/pod.go
Labels: lgtm, cncf-cla: yes, size/XL, approved

#1156 generate: update k8s code-generator to v0.27.1
  Dockerfile_generator
  pkg/generated/clientset/versioned/clientset.go
  pkg/generated/clientset/versioned/doc.go
  pkg/generated/clientset/versioned/typed/nfd/v1alpha1/fake/fake_nodefeature.go
  pkg/generated/clientset/versioned/typed/nfd/v1alpha1/fake/fake_nodefeaturerule.go
  pkg/generated/informers/externalversions/factory.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#1157 generate: update protoc to v22.3
  Dockerfile_generator
  pkg/labeler/labeler.pb.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1158 generate: update controller-gen to v0.11.3
  Dockerfile_generator
  deployment/base/nfd-crds/nfd-api-crds.yaml
  deployment/helm/node-feature-discovery/crds/nfd-api-crds.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved

#1159 generate: update mockery to v2.25.1
  Dockerfile_generator
  pkg/apihelper/mock_APIHelpers.go
  pkg/labeler/mock_LabelerClient.go
  pkg/podres/mocks/PodResourcesListerClient.go
  source/mock_LabelSource.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#1161 nfd-master: support noPublish with -prune
  pkg/nfd-master/nfd-master.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1160 nfd-master: fix -prune
  deployment/overlays/prune/kustomization.yaml
  pkg/nfd-master/nfd-master.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#1166 nfd-master: don't create emtpy annotations
  pkg/nfd-master/nfd-master-internal_test.go
  pkg/nfd-master/nfd-master.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#1173 nfd-master: fix a crash when processing NodeFeatureRules
  pkg/apis/nfd/v1alpha1/feature.go
  pkg/nfd-master/nfd-master.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#1171 pkg/nfd-master/nfd-master.go: Fix typo
  pkg/nfd-master/nfd-master.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1169 nfd-master: reject malformed extended resource dynamic capacity assignment
  pkg/nfd-master/nfd-master.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1178 go.mod: update deps
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/M, approved

#1180 OWNERS: add ArangoGutierrez as an approver
  OWNERS
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1139 feat: add master resync period configurability
  cmd/nfd-master/main.go
  deployment/components/master-config/nfd-master.conf.example
  deployment/helm/node-feature-discovery/templates/master.yaml
  deployment/helm/node-feature-discovery/values.yaml
  docs/deployment/helm.md
  docs/reference/master-commandline-reference.md
  docs/reference/master-configuration-reference.md
  pkg/nfd-master/nfd-api-controller.go
  pkg/nfd-master/nfd-master-internal_test.go
  pkg/nfd-master/nfd-master.go
  pkg/nfd-worker/nfd-worker.go
  pkg/utils/flags.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#1167 nfd-topology-updater: fix wrong kubelet_internal_checkpoint path and compare basename to full path
  pkg/nfd-topology-updater/kubeletnotifier/kubeletnotifier.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#1189 docs: add missing .md suffix to internal references
  docs/deployment/index.md
  docs/deployment/kustomize.md
  docs/get-started/index.md
  docs/usage/features.md
Labels: lgtm, cncf-cla: yes, size/S, approved

#1191 nfd-master: log node name when processing NodeFeatureRules
  pkg/nfd-master/nfd-master.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#1194 scripts/test-infra: provide PR info to codecov
  scripts/test-infra/verify.sh
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1196 Match usage and example for prepare-release.sh
  hack/prepare-release.sh
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1190 apis/nfd: add unit tests for Feature type
  pkg/apis/nfd/v1alpha1/feature.go
  pkg/apis/nfd/v1alpha1/feature_test.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#1197 Update README to v0.13.1
  README.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1199 scripts/test-infra: provide PR base SHA to codecov
  scripts/test-infra/verify.sh
Labels: lgtm, cncf-cla: yes, size/S, approved

#1200 codecov: drop required minimum coverage ratio of a commit to 0%
  codecov.yml
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1201 codecov: drop required minimum coverage ratio at patch level
  codecov.yml
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1198 nfd-master: refactor api-controller object handling
  pkg/nfd-master/nfd-api-controller.go
  pkg/nfd-master/nfd-api-controller_test.go
Labels: lgtm, cncf-cla: yes, size/M, approved
