Repository kubernetes-sigs/node-feature-discovery, pull requests merged in 2023-02, with the labels that each got.

#1044 helm: make master port configurable
  deployment/helm/node-feature-discovery/templates/master.yaml
  deployment/helm/node-feature-discovery/templates/service.yaml
  deployment/helm/node-feature-discovery/values.yaml
  docs/deployment/helm.md
Labels: lgtm, cncf-cla: yes, size/S, approved, ok-to-test

#1047 test: move out unit testing from Dockerfile
  Dockerfile
  scripts/test-infra/verify.sh
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1045 deployment: disable service links in NFD master pod
  deployment/base/master-worker-combined/master-worker-daemonset.yaml
  deployment/base/master/master-deployment.yaml
  deployment/helm/node-feature-discovery/templates/master.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved, ok-to-test

#1053 topology-updater: nrt-api Update to v1alpha2
  deployment/base/noderesourcetopologies-crd/noderesourcetopologies.yaml
  deployment/helm/node-feature-discovery/templates/topologyupdater-crds.yaml
  go.mod
  go.sum
  pkg/nfd-topology-gc/nfd-nrt-gc.go
  pkg/nfd-topology-gc/nfd-nrt-gc_test.go
  pkg/nfd-topology-updater/nfd-topology-updater.go
  pkg/resourcemonitor/noderesourcesaggregator.go
  pkg/resourcemonitor/noderesourcesaggregator_test.go
  pkg/resourcemonitor/types.go
  pkg/topologypolicy/topology-policy.go
  pkg/topologypolicy/topology-policy_test.go
  test/e2e/topology_updater_test.go
  test/e2e/utils/noderesourcetopology.go
Labels: lgtm, cncf-cla: yes, size/XL, approved, needs-ok-to-test

#1050 Change nfd-worker to use Ticker instead of After.
  pkg/nfd-worker/nfd-worker.go
Labels: lgtm, cncf-cla: yes, size/M, approved, ok-to-test

#1027 images: base the default image on distroless/base
  Makefile
  docs/deployment/image-variants.md
  docs/reference/worker-configuration-reference.md
  docs/usage/customization-guide.md
Labels: lgtm, cncf-cla: yes, size/M, approved

#1055 Add discovery duration logging
  pkg/nfd-worker/nfd-worker.go
Labels: lgtm, cncf-cla: yes, size/S, approved, ok-to-test

#1056 OWNERS: Update Ethyling username to jjacobelli
  .github/ISSUE_TEMPLATE/new-release.md
  OWNERS
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1054 Advertise TopologyManger policy and scope as Attributes in NRT api v1alpha2
  cmd/nfd-topology-updater/main.go
  pkg/nfd-topology-updater/nfd-topology-updater.go
  pkg/utils/kubeconf/kubelet_config_file.go
  test/e2e/utils/noderesourcetopology.go
Labels: lgtm, cncf-cla: yes, size/L, approved, ok-to-test

#1051 feat: add deny-label-ns flag which supports wildcard
  cmd/nfd-master/main.go
  deployment/helm/node-feature-discovery/templates/master.yaml
  deployment/helm/node-feature-discovery/values.yaml
  docs/reference/master-commandline-reference.md
  docs/usage/customization-guide.md
  pkg/nfd-master/nfd-master-internal_test.go
  pkg/nfd-master/nfd-master.go
  pkg/utils/flags.go
Labels: lgtm, cncf-cla: yes, size/L, approved, ok-to-test

#1058 Fix some typos
  docs/developer-guide/index.md
Labels: lgtm, cncf-cla: yes, size/XS, approved, needs-ok-to-test

#1061 scripts/test-infra: bump golangci-lint to v1.51.1
  scripts/test-infra/verify.sh
  test/e2e/e2e_test.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1059 GO Update version to 1.20
  Makefile
  go.mod
Labels: lgtm, cncf-cla: yes, size/XS, approved, ¯\_(ツ)_/¯

#1063 source/cpu: fix build flags of cpuid detection
  source/cpu/cpuid_linux_arm.go
  source/cpu/cpuid_linux_arm64.go
  source/cpu/cpuid_linux_ppc64le.go
  source/cpu/cpuid_linux_s390x.go
  source/cpu/cpuid_stub.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1064 go.mod: bump cpuid to v2.2.4
  docs/usage/features.md
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1062 docs: describe nfd-topology-gc in introduction.md
  docs/get-started/introduction.md
Labels: lgtm, cncf-cla: yes, size/XS, approved, ok-to-test

#1065 test/e2e: rename ginkgo focus for tests
  test/e2e/node_feature_discovery_test.go
  test/e2e/topology_updater_test.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1049 topology-updater:compute pod set fingerprint
  cmd/nfd-topology-updater/main.go
  deployment/helm/node-feature-discovery/templates/topologyupdater.yaml
  deployment/helm/node-feature-discovery/values.yaml
  docs/deployment/helm.md
  docs/reference/topology-updater-commandline-reference.md
  go.mod
  go.sum
  pkg/nfd-topology-updater/nfd-topology-updater.go
  pkg/nfd-topology-updater/nfd-topology-updater_test.go
  pkg/resourcemonitor/podresourcesscanner.go
  pkg/resourcemonitor/podresourcesscanner_test.go
  pkg/resourcemonitor/types.go
  test/e2e/topology_updater_test.go
Labels: lgtm, cncf-cla: yes, size/L, approved, ok-to-test
