Repository kubernetes-sigs/node-feature-discovery, pull requests merged in 2023-11, with the labels that each got.

#1447 docs: fix documentation on SEV security features
  docs/usage/customization-guide.md
  docs/usage/features.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1449 docs: use correct storage.block name for block device feature
  docs/usage/customization-guide.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1450 [release-0.14] docs: fix documentation on SEV security features
  docs/usage/customization-guide.md
  docs/usage/features.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1451 [release-0.14] docs: use correct storage.block name for block device feature
  docs/usage/customization-guide.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1452 source/network: refactor readIfaceInfo
  source/network/network.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#1453 go.mod: Update cpuid to its v2.2.6 release
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/XS, approved, ok-to-test

#1454 docs: stop advertising --resource-labels flag
  docs/usage/features.md
Labels: lgtm, cncf-cla: yes, size/M, approved

#1459 [release-0.14] Update dependencies
  Dockerfile
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/L, approved

#1457 go.mod: update deps
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/L, approved

#1463 go.mod: update deps
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/M, approved

#1464 [release-0.14] go.mod: update deps
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/M, approved

#1465 go.mod: bump kubernetes to v1.28.4
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/L, approved

#1466 [release-0.14] go.mod: bump kubernetes to v1.28.4
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/L, approved

#1467 apis/nfd: fix incorrect comments of matching functions
  pkg/apis/nfd/v1alpha1/expression.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#1458 apis/nfd: fix logging of rule expression processing
  pkg/apis/nfd/v1alpha1/expression.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1460 test/e2e: increase timeout for waiting node status
  test/e2e/gomega.go
  test/e2e/node_feature_discovery_test.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1469 docs: fix small typo in customization guide
  docs/usage/customization-guide.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1470 nfd-master: drop stale variables
  pkg/nfd-master/nfd-master-internal_test.go
  pkg/nfd-master/nfd-master.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#1471 nfd-master: predictable handling of unprefixed names
  pkg/nfd-master/nfd-master-internal_test.go
  pkg/nfd-master/nfd-master.go
  test/e2e/data/nodefeature-1.yaml
Labels: lgtm, cncf-cla: yes, size/L, approved

#1468 apis/nfd: fix multiple matcher terms targeting the same feature
  pkg/apis/nfd/v1alpha1/expression.go
  pkg/apis/nfd/v1alpha1/expression_test.go
  pkg/apis/nfd/v1alpha1/rule.go
  pkg/apis/nfd/v1alpha1/rule_test.go
  pkg/apis/nfd/v1alpha1/zz_generated.deepcopy.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#1461 Option to stop implicitly adding default prefix to names
  deployment/components/master-config/nfd-master.conf.example
  deployment/components/worker-config/nfd-worker.conf.example
  deployment/helm/node-feature-discovery/values.yaml
  docs/reference/master-configuration-reference.md
  docs/usage/customization-guide.md
  examples/nodefeaturerule.yaml
  pkg/nfd-master/nfd-master-internal_test.go
  pkg/nfd-master/nfd-master.go
  pkg/nfd-worker/nfd-worker-internal_test.go
  pkg/nfd-worker/nfd-worker.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#1474 Use T.Run in expression unit tests
  pkg/apis/nfd/v1alpha1/expression_test.go
Labels: lgtm, cncf-cla: yes, size/XL, approved

#1472 nfd-worker: fix typo in log message
  pkg/nfd-worker/nfd-worker.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1476 docs/tls: update cert-manager deployment instructions
  docs/deployment/tls.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1478 generate: update kube code-gen to v1.28.4
  Dockerfile_generator
  pkg/generated/informers/externalversions/factory.go
Labels: lgtm, cncf-cla: yes, size/XS, approved
