Repository kubernetes-sigs/node-feature-discovery, pull requests merged in 2024-07, with the labels that each got.

#1754 Release v0.16.1
  README.md
  deployment/base/gc/gc.yaml
  deployment/base/master/master-deployment.yaml
  deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
  deployment/base/worker-daemonset/worker-daemonset.yaml
  deployment/base/worker-job/worker-job.yaml
  deployment/helm/node-feature-discovery/Chart.yaml
  deployment/overlays/prune/master-job.yaml
  docs/_config.yml
Labels: lgtm, cncf-cla: yes, size/S, approved

#1756 Update README to v0.16.1
  README.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1757 [release-0.15] Update references for v0.15.5 release
  Makefile
  README.md
  deployment/base/gc/gc.yaml
  deployment/base/master/master-deployment.yaml
  deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
  deployment/base/worker-daemonset/worker-daemonset.yaml
  deployment/base/worker-job/worker-job.yaml
  deployment/helm/node-feature-discovery/Chart.yaml
  deployment/overlays/prune/master-job.yaml
  docs/_config.yml
Labels: lgtm, cncf-cla: yes, size/S, approved

#1749 Document AVXVNNIINT16 cpuid feature
  docs/usage/features.md
Labels: lgtm, cncf-cla: yes, size/XS, approved, ok-to-test

#1758 scripts: refresh e2e-presubmit test script
  scripts/test-infra/test-e2e-presubmit.sh
Labels: lgtm, cncf-cla: yes, size/M, approved

#1764 docs: describe Kubernetes version compatibility in versions page
  docs/deployment/index.md
  docs/deployment/kustomize.md
  docs/developer-guide/index.md
  docs/get-started/introduction.md
  docs/reference/versions.md
Labels: lgtm, cncf-cla: yes, size/S, approved

#1762 scripts/test-infra: drop the unused build-image script
  scripts/test-infra/build-image.sh
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1763 scripts/test-infra: run postsubmit e2e test in kind
  scripts/test-infra/test-e2e.sh
Labels: lgtm, cncf-cla: yes, size/S, approved

#1765 nfd-master: fix typos
  pkg/nfd-master/nfd-master.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1766 Simplify code
  api/nfd/v1alpha1/feature_test.go
  pkg/apis/nfd/nodefeaturerule/expression-api_test.go
  source/custom/static_features.go
  source/fake/fake.go
  source/pci/pci_test.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#1767 scripts/test-infra: setup kind in e2e-test
  scripts/test-infra/test-e2e.sh
Labels: lgtm, cncf-cla: yes, size/S, approved

#1768 README: update module name in go report card badge
  README.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1726 deployment/helm: enable specifying additional cmdline args
  deployment/helm/node-feature-discovery/templates/master.yaml
  deployment/helm/node-feature-discovery/templates/nfd-gc.yaml
  deployment/helm/node-feature-discovery/templates/topologyupdater.yaml
  deployment/helm/node-feature-discovery/templates/worker.yaml
  deployment/helm/node-feature-discovery/values.yaml
  docs/deployment/helm.md
Labels: lgtm, cncf-cla: yes, size/S, approved

#1770 cloudbuild: increase the image build timeout
  cloudbuild.yaml
  scripts/test-infra/test-e2e.sh
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1755 Use worker DS OwnerReference for NF's
  cmd/nfd-worker/main.go
  deployment/base/rbac/worker-role.yaml
  deployment/helm/node-feature-discovery/templates/role.yaml
  pkg/nfd-worker/nfd-worker-internal_test.go
  pkg/nfd-worker/nfd-worker.go
  pkg/nfd-worker/nfd-worker_test.go
  test/e2e/utils/rbac.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#1775 [Release-0.15] Use worker DS OwnerReference for NF's
  cmd/nfd-worker/main.go
  deployment/base/rbac/worker-role.yaml
  deployment/helm/node-feature-discovery/templates/role.yaml
  pkg/nfd-worker/nfd-worker-internal_test.go
  pkg/nfd-worker/nfd-worker.go
  pkg/nfd-worker/nfd-worker_test.go
  test/e2e/utils/rbac.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#1777 Release v0.15.6
  README.md
  deployment/base/gc/gc.yaml
  deployment/base/master/master-deployment.yaml
  deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
  deployment/base/worker-daemonset/worker-daemonset.yaml
  deployment/base/worker-job/worker-job.yaml
  deployment/helm/node-feature-discovery/Chart.yaml
  deployment/overlays/prune/master-job.yaml
  docs/_config.yml
Labels: lgtm, cncf-cla: yes, size/S, approved

#1776 Release v0.16.2
  Makefile
  README.md
  deployment/base/gc/gc.yaml
  deployment/base/master/master-deployment.yaml
  deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
  deployment/base/worker-daemonset/worker-daemonset.yaml
  deployment/base/worker-job/worker-job.yaml
  deployment/helm/node-feature-discovery/Chart.yaml
  deployment/overlays/prune/master-job.yaml
  docs/_config.yml
Labels: lgtm, cncf-cla: yes, size/S, approved

#1783 README: update to v0.16.2
  README.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1780 Drop the -enable-nodefeature-api flag
  cmd/nfd-master/main.go
  cmd/nfd-worker/main.go
  deployment/helm/node-feature-discovery/templates/clusterrole.yaml
  deployment/helm/node-feature-discovery/templates/clusterrolebinding.yaml
  deployment/helm/node-feature-discovery/templates/master.yaml
  deployment/helm/node-feature-discovery/templates/nfd-gc.yaml
  deployment/helm/node-feature-discovery/templates/service.yaml
  deployment/helm/node-feature-discovery/templates/serviceaccount.yaml
  deployment/helm/node-feature-discovery/templates/worker.yaml
  deployment/helm/node-feature-discovery/values.yaml
  docs/deployment/helm.md
  docs/reference/master-commandline-reference.md
  pkg/nfd-master/nfd-master.go
  pkg/nfd-worker/nfd-worker.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#1781 fix: take into consideration possibility of having empty line in swap file
  source/memory/memory.go
  source/memory/memory_test.go
  source/memory/testdata/noswap
  source/memory/testdata/swap
Labels: lgtm, cncf-cla: yes, size/S, approved

#1788 nfd-worker: change TestRun to use NodeFeature API
  pkg/nfd-worker/nfd-worker.go
  pkg/nfd-worker/nfd-worker_test.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#1786 go.mod: update kubernetes to v1.30.2 and klog to v2.130.1
  api/nfd/go.mod
  api/nfd/go.sum
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/L, approved

#1782 Helm: Add revision history limit for master replica
  deployment/helm/node-feature-discovery/templates/master.yaml
  deployment/helm/node-feature-discovery/templates/nfd-gc.yaml
  deployment/helm/node-feature-discovery/values.yaml
  docs/deployment/helm.md
Labels: lgtm, cncf-cla: yes, size/S, approved

#1789 [release-0.16] Add revision history limit for master replica and for garbage collector
  deployment/helm/node-feature-discovery/templates/master.yaml
  deployment/helm/node-feature-discovery/templates/nfd-gc.yaml
  deployment/helm/node-feature-discovery/values.yaml
  docs/deployment/helm.md
Labels: lgtm, cncf-cla: yes, size/S, approved

#1792 test/e2e: set topology-updater sleep-interval in podfingerprint test
  test/e2e/topology_updater_test.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1790 helm: drop trailing whitespace from values.yaml
  deployment/helm/node-feature-discovery/values.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1791 docs: reformat tables of helm parameters
  docs/deployment/helm.md
Labels: lgtm, cncf-cla: yes, size/L, approved

#1787 [release-0.16] Release v0.16.3
  README.md
  deployment/base/gc/gc.yaml
  deployment/base/master/master-deployment.yaml
  deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
  deployment/base/worker-daemonset/worker-daemonset.yaml
  deployment/base/worker-job/worker-job.yaml
  deployment/helm/node-feature-discovery/Chart.yaml
  deployment/overlays/prune/master-job.yaml
  docs/_config.yml
Labels: lgtm, cncf-cla: yes, size/S, approved

#1793 test/e2e: specify -sleep-interval in topology-updater exclude-memory test
  test/e2e/topology_updater_test.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1794 README: update to v0.16.3
  README.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1778 feature-gates: mark NodeFeatureAPI as GA
  docs/reference/feature-gates.md
  docs/reference/master-commandline-reference.md
  docs/reference/master-configuration-reference.md
  docs/reference/worker-commandline-reference.md
  docs/usage/customization-guide.md
  docs/usage/nfd-gc.md
  docs/usage/nfd-master.md
  pkg/features/features.go
  pkg/nfd-worker/nfd-worker_test.go
  test/e2e/node_feature_discovery_test.go
Labels: lgtm, cncf-cla: yes, size/XXL, approved

#1795 scripts/test-infra: bump golangci-lint to v1.59.1
  scripts/test-infra/verify.sh
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1797 Helm: Add revision history limit for worker daemonset
  deployment/helm/node-feature-discovery/templates/topologyupdater.yaml
  deployment/helm/node-feature-discovery/templates/worker.yaml
  deployment/helm/node-feature-discovery/values.yaml
  docs/deployment/helm.md
Labels: lgtm, cncf-cla: yes, size/S, approved, tide/merge-method-squash, ok-to-test

#1799 [release-0.16] Helm: Add revision history limit for worker daemonset (#1797)
  deployment/helm/node-feature-discovery/templates/topologyupdater.yaml
  deployment/helm/node-feature-discovery/templates/worker.yaml
  deployment/helm/node-feature-discovery/values.yaml
  docs/deployment/helm.md
Labels: lgtm, cncf-cla: yes, size/S, approved

#1798 Dockerfile: cache go modules on build
  Dockerfile
  Dockerfile_generator
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1805 [release-0.16] go.mod: bump kubernetes to v1.30.3
  api/nfd/go.mod
  api/nfd/go.sum
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/L, approved

#1801 helm: add configurable liveness&readiness probes for master topology-updater and worker
  deployment/helm/node-feature-discovery/templates/master.yaml
  deployment/helm/node-feature-discovery/templates/topologyupdater.yaml
  deployment/helm/node-feature-discovery/templates/worker.yaml
  deployment/helm/node-feature-discovery/values.yaml
  docs/deployment/helm.md
Labels: lgtm, cncf-cla: yes, size/L, approved

#1809 nfd-master: check nfd api informer cache sync result
  pkg/nfd-master/nfd-api-controller.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#1812 nfd-gc: check that node informer cache sync succeeded
  pkg/nfd-gc/nfd-gc.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#1808 [release-0.16] helm: add configurable liveness&readiness probes
  deployment/helm/node-feature-discovery/templates/master.yaml
  deployment/helm/node-feature-discovery/templates/topologyupdater.yaml
  deployment/helm/node-feature-discovery/templates/worker.yaml
  deployment/helm/node-feature-discovery/values.yaml
  docs/deployment/helm.md
Labels: lgtm, cncf-cla: yes, size/M, approved

#1822 Docs: Fixed feature-gates reference
  docs/reference/master-commandline-reference.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1811 nfd-master: tweak list options for NodeFeature informer
  pkg/nfd-master/nfd-api-controller.go
Labels: lgtm, cncf-cla: yes, size/S, approved
