Repository kubernetes-sigs/node-feature-discovery, pull requests merged in 2024-04, with the labels that each got.

#1631 chore/deployment: add resources requests and limits for helm and Kustomize
  deployment/base/gc/gc.yaml
  deployment/base/master/master-deployment.yaml
  deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
  deployment/base/worker-daemonset/worker-daemonset.yaml
  deployment/helm/node-feature-discovery/values.yaml
  docs/deployment/helm.md
Labels: lgtm, cncf-cla: yes, size/L, approved

#1643 nfd-topology-updater: Add liveness probe
  cmd/nfd-topology-updater/main.go
  deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
  deployment/helm/node-feature-discovery/templates/topologyupdater.yaml
  deployment/helm/node-feature-discovery/values.yaml
  pkg/nfd-topology-updater/nfd-topology-updater.go
Labels: lgtm, cncf-cla: yes, size/M, approved, ok-to-test

#1652 nfd-master: get node object only once when updating node
  pkg/nfd-master/nfd-master-internal_test.go
  pkg/nfd-master/nfd-master.go
  pkg/nfd-master/node-updater-pool.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#1649 [release-0.15] Update references for v0.15.4 release
  README.md
  deployment/base/gc/gc.yaml
  deployment/base/master/master-deployment.yaml
  deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
  deployment/base/worker-daemonset/worker-daemonset.yaml
  deployment/base/worker-job/worker-job.yaml
  deployment/helm/node-feature-discovery/Chart.yaml
  deployment/overlays/prune/master-job.yaml
  docs/_config.yml
Labels: lgtm, cncf-cla: yes, size/S, approved

#1639 chore/deploy: make interval property in PodMonitor configurable
  deployment/helm/node-feature-discovery/templates/prometheus.yaml
  deployment/helm/node-feature-discovery/values.yaml
  docs/deployment/helm.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1642 nfd-master: protect node updater pool queueing with a lock
  pkg/nfd-master/nfd-master.go
  pkg/nfd-master/node-updater-pool.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#1657 nfd-master: prevent crash on empty config struct
  pkg/nfd-master/nfd-master-internal_test.go
  pkg/nfd-master/nfd-master.go
  pkg/utils/flags.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#1650 Update readme to v0.15.4 release
  README.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1656 Tidy up usage of channels for signaling
  pkg/nfd-gc/nfd-gc_test.go
  pkg/nfd-master/nfd-api-controller.go
  pkg/nfd-master/nfd-master-internal_test.go
  pkg/nfd-master/nfd-master.go
  pkg/nfd-topology-updater/nfd-topology-updater.go
  pkg/nfd-worker/nfd-worker.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#1658 nfd-master: implement opts for modifying NfdMaster instance
  cmd/nfd-master/main.go
  pkg/nfd-master/nfd-master-internal_test.go
  pkg/nfd-master/nfd-master.go
  pkg/nfd-master/nfd-master_test.go
  pkg/nfd-master/node-updater-pool_test.go
  pkg/nfd-worker/nfd-worker_test.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#1662 Fix Make generate
  api/nfd/v1alpha1/zz_generated.deepcopy.go
  hack/update_codegen.sh
  pkg/labeler/labeler.pb.go
  pkg/labeler/labeler.proto
Labels: lgtm, cncf-cla: yes, size/L, approved

#1633 apis/nfd/validate: loosen validation of feature annotations
  api/nfd/v1alpha1/annotations_labels.go
  pkg/apis/nfd/validate/validate.go
  pkg/apis/nfd/validate/validate_test.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#1653 nfd-master: use separate k8s api clients for each updater
  pkg/nfd-master/nfd-master-internal_test.go
  pkg/nfd-master/nfd-master.go
  pkg/nfd-master/node-updater-pool.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#1660 nfd-master: stop node-updater pool before reconfiguring api-controller
  pkg/nfd-master/nfd-master.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#1668 chore/nfd-master: remove warnings in nfd-master unit tests file
  pkg/nfd-master/nfd-master-internal_test.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#1667 apis/nfd: add unit tests for match name functions
  pkg/apis/nfd/nodefeaturerule/expression-api_test.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#1670 apis/nfd: no error on ops that never match
  pkg/apis/nfd/nodefeaturerule/expression-api_test.go
  pkg/apis/nfd/nodefeaturerule/expression.go
  pkg/apis/nfd/nodefeaturerule/expression_test.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#1669 api/nfd: use varargs in the NewInstanceFeatures helper
  api/nfd/v1alpha1/feature.go
  api/nfd/v1alpha1/feature_test.go
  pkg/apis/nfd/nodefeaturerule/rule_test.go
  source/fake/fake.go
  source/pci/pci.go
  source/usb/usb.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#1674 scripts/test-infra: bump golangci-lint to v1.57.2
  scripts/test-infra/verify.sh
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1676 [release-0.15] go.mod: update dependencies
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/L, approved

#1659 add ARMv7 support
  Makefile
  scripts/test-infra/build-image-cross.sh
Labels: lgtm, cncf-cla: yes, size/XS, approved, ok-to-test

#1651 docs: document trade-offs in memory configuration
  deployment/helm/node-feature-discovery/values.yaml
  docs/deployment/helm.md
Labels: lgtm, cncf-cla: yes, size/XS, approved, ok-to-test

#1675 go.mod: bump kubernetes to v1.30
  api/nfd/go.mod
  api/nfd/go.sum
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/L, approved

#1678 cloudbuild.yaml: change machine type to e1-highcpu-32
  cloudbuild.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1683 hack/init-buildx.sh: fix broken patter matching
  hack/init-buildx.sh
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1677 Disable armv7 builds
  scripts/test-infra/push-image.sh
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1685 cloudbuild.yaml: downgrade machine type to e2-highcpu-8
  cloudbuild.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1679 Dependabot: Add proper dependabot config file
  .github/dependabot.yml
Labels: lgtm, cncf-cla: yes, size/S, approved

#1693 apis/nfd: increase unit test coverage
  pkg/apis/nfd/nodefeaturerule/expression-api_test.go
Labels: lgtm, cncf-cla: yes, size/M, approved
