Repository kubernetes-sigs/node-feature-discovery, pull requests merged in 2024-09, with the labels that each got.

#1859 scripts/test-infra: bump golangci-lint to v1.60.3
  scripts/test-infra/verify.sh
  test/e2e/utils/noderesourcetopology.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1847 Drop dynamic run-time reconfiguration
  deployment/components/master-config/kustomization.yaml
  deployment/components/topology-updater-config/kustomization.yaml
  deployment/components/worker-config/kustomization.yaml
  deployment/helm/node-feature-discovery/templates/master.yaml
  deployment/helm/node-feature-discovery/templates/topologyupdater.yaml
  deployment/helm/node-feature-discovery/templates/worker.yaml
  docs/reference/worker-configuration-reference.md
  docs/usage/nfd-master.md
  docs/usage/nfd-topology-updater.md
  docs/usage/nfd-worker.md
  pkg/nfd-master/nfd-master-internal_test.go
  pkg/nfd-master/nfd-master.go
  pkg/nfd-worker/nfd-worker-internal_test.go
  pkg/nfd-worker/nfd-worker.go
  test/e2e/node_feature_discovery_test.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#1865 build(deps): bump github.com/opencontainers/runc from 1.1.13 to 1.1.14
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1858 Bump Go to v1.23
  Makefile
  Tiltfile
  go.mod
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1876 nfd-master: cleanup updater-pool method args
  pkg/nfd-master/updater-pool.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#1880 helm: rename args chart value to extraArgs
  deployment/helm/node-feature-discovery/templates/master.yaml
  deployment/helm/node-feature-discovery/templates/nfd-gc.yaml
  deployment/helm/node-feature-discovery/templates/topologyupdater.yaml
  deployment/helm/node-feature-discovery/templates/worker.yaml
  docs/deployment/helm.md
Labels: lgtm, cncf-cla: yes, size/S, approved

#1881 helm: rename args to extraArgs in values.yaml
  deployment/helm/node-feature-discovery/values.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1856 source/network: Ignore bonding_masters interface during scanning
  source/network/network.go
Labels: lgtm, cncf-cla: yes, size/XS, approved, ok-to-test

#1878 Add helm values to configure hostNetwork and additional env vars
  deployment/helm/node-feature-discovery/templates/master.yaml
  deployment/helm/node-feature-discovery/templates/nfd-gc.yaml
  deployment/helm/node-feature-discovery/templates/topologyupdater.yaml
  deployment/helm/node-feature-discovery/templates/worker.yaml
  deployment/helm/node-feature-discovery/values.yaml
  docs/deployment/helm.md
Labels: lgtm, cncf-cla: yes, size/M, approved

#1885 Add parameter to configure health endpoint port
  cmd/nfd-master/main.go
  cmd/nfd-topology-updater/main.go
  cmd/nfd-worker/main.go
  deployment/helm/node-feature-discovery/templates/master.yaml
  deployment/helm/node-feature-discovery/templates/topologyupdater.yaml
  deployment/helm/node-feature-discovery/templates/worker.yaml
  deployment/helm/node-feature-discovery/values.yaml
  docs/deployment/helm.md
Labels: lgtm, cncf-cla: yes, size/M, approved

#1888 nfd-gc: drop one duplicate import from tests
  pkg/nfd-gc/nfd-gc_test.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1836 test/e2e: use ptr.To to get pointer to bool
  test/e2e/utils/pod/pod.go
Labels: lgtm, cncf-cla: yes, size/M, approved
