Repository kubernetes-sigs/node-feature-discovery, pull requests merged in 2024-08, with the labels that each got.

#1821 Docs: Fix the link to feature gates documentation
  docs/reference/master-commandline-reference.md
  docs/reference/worker-commandline-reference.md
Labels: lgtm, cncf-cla: yes, size/XS, approved, ok-to-test

#1813 nfd-gc: only fetch object metadata
  pkg/nfd-gc/nfd-gc.go
  pkg/nfd-gc/nfd-gc_test.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#1815 nfd-gc: use paging when listing CRs
  pkg/nfd-gc/nfd-gc.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#1807 Add helm migration guide
  docs/deployment/helm.md
Labels: lgtm, cncf-cla: yes, size/M, approved

#1829 docs: use jekyll-rtd-theme from a ruby gem
  Makefile
  docs/Gemfile
  docs/Gemfile.lock
  docs/_config.yml
  netlify.toml
Labels: lgtm, cncf-cla: yes, size/S, approved

#1827 tilt: sync up builder go version with project go.mod
  Tiltfile
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1826 [release-0.16] Release v0.16.4
  README.md
  deployment/base/gc/gc.yaml
  deployment/base/master/master-deployment.yaml
  deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
  deployment/base/worker-daemonset/worker-daemonset.yaml
  deployment/base/worker-job/worker-job.yaml
  deployment/helm/node-feature-discovery/Chart.yaml
  deployment/overlays/prune/master-job.yaml
  docs/_config.yml
Labels: lgtm, cncf-cla: yes, size/S, approved

#1834 README: update to v0.16.4
  README.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1844 nfd-master: explicit state variable for the node updater pool
  pkg/nfd-master/updater-pool.go
  pkg/nfd-master/updater-pool_test.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#1843 nfd-master: use only unbuffered chans in the nfd api-controller
  pkg/nfd-master/nfd-api-controller.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1848 nfd-master: proper shutdown of nfd api informers
  pkg/nfd-master/nfd-api-controller.go
  pkg/nfd-master/nfd-master.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#1850 [release-0.16] nfd-master: proper shutdown of nfd api informers
  pkg/nfd-master/nfd-api-controller.go
  pkg/nfd-master/nfd-master.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#1854 test/e2e: drop the pod security admission hack
  test/e2e/node_feature_discovery_test.go
Labels: lgtm, cncf-cla: yes, size/S, approved
