Repository kubernetes-sigs/node-feature-discovery, pull requests merged in 2024-10, with the labels that each got.

#1895 docs: quote shell snippets containing urls with query parameters
  README.md
  docs/deployment/kustomize.md
  docs/deployment/uninstallation.md
  docs/get-started/quick-start.md
Labels: lgtm, cncf-cla: yes, size/M, approved

#1902 [release-0.16] Add parameter to configure health endpoint port
  cmd/nfd-master/main.go
  cmd/nfd-topology-updater/main.go
  cmd/nfd-worker/main.go
  deployment/helm/node-feature-discovery/templates/master.yaml
  deployment/helm/node-feature-discovery/templates/topologyupdater.yaml
  deployment/helm/node-feature-discovery/templates/worker.yaml
  deployment/helm/node-feature-discovery/values.yaml
  docs/deployment/helm.md
Labels: lgtm, cncf-cla: yes, size/S, approved

#1857 [release-0.16] Release v0.16.5
  Makefile
  README.md
  deployment/base/gc/gc.yaml
  deployment/base/master/master-deployment.yaml
  deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
  deployment/base/worker-daemonset/worker-daemonset.yaml
  deployment/base/worker-job/worker-job.yaml
  deployment/helm/node-feature-discovery/Chart.yaml
  deployment/overlays/prune/master-job.yaml
  docs/_config.yml
Labels: lgtm, cncf-cla: yes, size/S, approved

#1903 [release-0.16] Add helm values to configure hostNetwork and additional env vars
  deployment/helm/node-feature-discovery/templates/master.yaml
  deployment/helm/node-feature-discovery/templates/nfd-gc.yaml
  deployment/helm/node-feature-discovery/templates/topologyupdater.yaml
  deployment/helm/node-feature-discovery/templates/worker.yaml
  deployment/helm/node-feature-discovery/values.yaml
  docs/deployment/helm.md
Labels: lgtm, cncf-cla: yes, size/M, approved

#1906 github: specify workflow permissions
  .github/workflows/gh-pages.yml
  .github/workflows/release.yml
Labels: lgtm, cncf-cla: yes, size/S, approved

#1908 [gh-pages] Update Helm repo index for release v0.16.5
  charts/index.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved

#1911 [release-0.15]: bump dependencies
  Makefile
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/L, approved

#1924 Convert testdata to an empty go module
  testdata/README.md
  testdata/go.mod
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1913 Add separate helm values for the liveness and readiness probes
  deployment/helm/node-feature-discovery/templates/master.yaml
  deployment/helm/node-feature-discovery/templates/topologyupdater.yaml
  deployment/helm/node-feature-discovery/templates/worker.yaml
  deployment/helm/node-feature-discovery/values.yaml
  docs/deployment/helm.md
Labels: lgtm, cncf-cla: yes, size/L, approved

#1925 [release-0.15] Release v0.15.7
  README.md
  deployment/base/gc/gc.yaml
  deployment/base/master/master-deployment.yaml
  deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
  deployment/base/worker-daemonset/worker-daemonset.yaml
  deployment/base/worker-job/worker-job.yaml
  deployment/helm/node-feature-discovery/Chart.yaml
  deployment/overlays/prune/master-job.yaml
  docs/_config.yml
Labels: lgtm, cncf-cla: yes, size/S, approved

#1592 feat/nfd-master: configure CR restrictions
  deployment/base/rbac/master-clusterrole.yaml
  deployment/components/master-config/nfd-master.conf.example
  deployment/helm/node-feature-discovery/templates/clusterrole.yaml
  deployment/helm/node-feature-discovery/values.yaml
  docs/reference/master-configuration-reference.md
  pkg/nfd-master/namespace-lister.go
  pkg/nfd-master/nfd-api-controller.go
  pkg/nfd-master/nfd-api-controller_test.go
  pkg/nfd-master/nfd-master-internal_test.go
  pkg/nfd-master/nfd-master.go
  test/e2e/data/nodefeaturerule-6.yaml
  test/e2e/node_feature_discovery_test.go
  test/e2e/utils/rbac.go
Labels: lgtm, cncf-cla: yes, size/XL, approved, ok-to-test

#1933 [Release-0.16] Bump to V0.16.6
  README.md
  deployment/base/gc/gc.yaml
  deployment/base/master/master-deployment.yaml
  deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
  deployment/base/worker-daemonset/worker-daemonset.yaml
  deployment/base/worker-job/worker-job.yaml
  deployment/helm/node-feature-discovery/Chart.yaml
  deployment/overlays/prune/master-job.yaml
  docs/_config.yml
Labels: lgtm, cncf-cla: yes, size/S, approved

#1910 Drop NFD gRPC API
  cmd/nfd-master/main.go
  cmd/nfd-worker/main.go
  deployment/helm/node-feature-discovery/templates/cert-manager-certs.yaml
  deployment/helm/node-feature-discovery/templates/cert-manager-issuer.yaml
  deployment/helm/node-feature-discovery/templates/master.yaml
  deployment/helm/node-feature-discovery/templates/topologyupdater.yaml
  deployment/helm/node-feature-discovery/templates/worker.yaml
  deployment/helm/node-feature-discovery/values.yaml
  go.mod
  pkg/labeler/doc.go
  pkg/labeler/labeler.pb.go
  pkg/labeler/labeler.proto
  pkg/labeler/mock_LabelerClient.go
  pkg/nfd-master/nfd-master-internal_test.go
  pkg/nfd-master/nfd-master.go
  pkg/nfd-master/nfd-master_test.go
  pkg/nfd-master/updater-pool.go
  pkg/nfd-worker/nfd-worker-internal_test.go
  pkg/nfd-worker/nfd-worker.go
  pkg/nfd-worker/nfd-worker_test.go
  pkg/utils/tls.go
  test/data/ca.crt
  test/data/data.go
  test/data/nfd-test-master.crt
  test/data/nfd-test-master.key
  test/data/nfd-test-topology-updater.crt
  test/data/nfd-test-topology-updater.key
  test/data/nfd-test-worker.crt
  test/data/nfd-test-worker.key
  test/e2e/utils/pod/pod.go
Labels: lgtm, cncf-cla: yes, size/XXL, approved

#1837 go.mod: bump kubernetes to v1.31
  Dockerfile_generator
  api/generated/clientset/versioned/fake/clientset_generated.go
  api/generated/clientset/versioned/typed/nfd/v1alpha1/fake/fake_nodefeature.go
  api/generated/clientset/versioned/typed/nfd/v1alpha1/fake/fake_nodefeaturegroup.go
  api/generated/clientset/versioned/typed/nfd/v1alpha1/fake/fake_nodefeaturerule.go
  api/generated/clientset/versioned/typed/nfd/v1alpha1/nodefeature.go
  api/generated/clientset/versioned/typed/nfd/v1alpha1/nodefeaturegroup.go
  api/generated/clientset/versioned/typed/nfd/v1alpha1/nodefeaturerule.go
  api/generated/informers/externalversions/factory.go
  api/generated/listers/nfd/v1alpha1/nodefeature.go
  api/generated/listers/nfd/v1alpha1/nodefeaturegroup.go
  api/generated/listers/nfd/v1alpha1/nodefeaturerule.go
  deployment/base/nfd-crds/nfd-api-crds.yaml
  deployment/helm/node-feature-discovery/crds/nfd-api-crds.yaml
  go.mod
  go.sum
  pkg/nfd-master/updater-pool.go
Labels: lgtm, cncf-cla: yes, size/XXL, approved

#1816 tests: better assertion message in nfd-gc unit tests
  pkg/nfd-gc/nfd-gc_test.go
Labels: lgtm, cncf-cla: yes, size/M, approved
