Repository kubernetes-sigs/node-feature-discovery, pull requests merged in 2024-12, with the labels that each got.

#1973 Docs: Fix the link to feature gates documentation
  docs/reference/master-commandline-reference.md
  docs/reference/worker-commandline-reference.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1845 NFD image compatibility proposal
  enhancements/1845-nfd-image-compatibility/README.md
Labels: lgtm, cncf-cla: yes, size/L, approved, ok-to-test

#1810 deployment: add startupProbe for nfd-master
  deployment/base/master/master-deployment.yaml
  deployment/helm/node-feature-discovery/templates/master.yaml
  deployment/helm/node-feature-discovery/values.yaml
  docs/deployment/helm.md
Labels: lgtm, cncf-cla: yes, size/M, approved

#1974 scripts/update-gh-pages: fix release version parsing
  scripts/github/update-gh-pages.sh
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1965 nfd-master: check that namespace informer cache sync succeeded
  pkg/nfd-master/namespace-lister.go
  pkg/nfd-master/nfd-api-controller.go
  pkg/nfd-master/nfd-api-controller_test.go
Labels: lgtm, cncf-cla: yes, size/S, approved, ok-to-test

#1977 Fix version parsing
  cmd/nfd-gc/main.go
  cmd/nfd-master/main.go
  cmd/nfd-topology-updater/main.go
  cmd/nfd-worker/main.go
  scripts/github/update-gh-pages.sh
  scripts/test-infra/test-e2e-presubmit.sh
Labels: lgtm, cncf-cla: yes, size/S, approved

#1981 Makefile: fix version parsing
  Makefile
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1980 [release-0.16] Fix version parsing
  Makefile
  cmd/nfd-gc/main.go
  cmd/nfd-master/main.go
  cmd/nfd-topology-updater/main.go
  cmd/nfd-worker/main.go
  scripts/github/update-gh-pages.sh
  scripts/test-infra/test-e2e-presubmit.sh
Labels: lgtm, cncf-cla: yes, size/S, approved

#1860 nfd-worker: Add an option to disable setting the owner references
  cmd/nfd-worker/main.go
  cmd/nfd-worker/main_test.go
  deployment/components/worker-config/nfd-worker.conf.example
  deployment/helm/node-feature-discovery/values.yaml
  docs/reference/worker-commandline-reference.md
  docs/reference/worker-configuration-reference.md
  pkg/nfd-worker/nfd-worker.go
Labels: lgtm, cncf-cla: yes, size/L, approved, ok-to-test

#1976 Cleanup for NodeFeature API being GA
  cmd/nfd-master/main.go
  deployment/base/worker-daemonset/worker-daemonset.yaml
  deployment/base/worker-job/worker-job.yaml
  deployment/helm/node-feature-discovery/templates/clusterrole.yaml
  deployment/helm/node-feature-discovery/templates/clusterrolebinding.yaml
  deployment/helm/node-feature-discovery/templates/master.yaml
  deployment/helm/node-feature-discovery/templates/nfd-gc.yaml
  deployment/helm/node-feature-discovery/templates/service.yaml
  deployment/helm/node-feature-discovery/templates/serviceaccount.yaml
  deployment/helm/node-feature-discovery/templates/worker.yaml
  deployment/helm/node-feature-discovery/values.yaml
  docs/deployment/helm.md
  docs/developer-guide/index.md
  docs/get-started/index.md
  pkg/nfd-master/nfd-master.go
  test/e2e/node_feature_discovery_test.go
  test/e2e/utils/service.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#1987 go.mod: bump kubernetes to v1.32
  api/nfd/go.mod
  api/nfd/go.sum
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/L, approved

#1989 Drop protobuf definitions and protobuf code generation
  Dockerfile_generator
  api/generated/clientset/versioned/clientset.go
  api/generated/clientset/versioned/typed/nfd/v1alpha1/fake/fake_nfd_client.go
  api/generated/clientset/versioned/typed/nfd/v1alpha1/fake/fake_nodefeature.go
  api/generated/clientset/versioned/typed/nfd/v1alpha1/fake/fake_nodefeaturegroup.go
  api/generated/clientset/versioned/typed/nfd/v1alpha1/fake/fake_nodefeaturerule.go
  api/generated/clientset/versioned/typed/nfd/v1alpha1/nfd_client.go
  api/generated/clientset/versioned/typed/nfd/v1alpha1/nodefeature.go
  api/generated/clientset/versioned/typed/nfd/v1alpha1/nodefeaturegroup.go
  api/generated/clientset/versioned/typed/nfd/v1alpha1/nodefeaturerule.go
  api/generated/informers/externalversions/generic.go
  api/generated/informers/externalversions/nfd/v1alpha1/nodefeature.go
  api/generated/informers/externalversions/nfd/v1alpha1/nodefeaturegroup.go
  api/generated/informers/externalversions/nfd/v1alpha1/nodefeaturerule.go
  api/generated/listers/nfd/v1alpha1/nodefeature.go
  api/generated/listers/nfd/v1alpha1/nodefeaturegroup.go
  api/generated/listers/nfd/v1alpha1/nodefeaturerule.go
  api/nfd/v1alpha1/doc.go
  api/nfd/v1alpha1/generate.sh
  api/nfd/v1alpha1/generated.pb.go
  api/nfd/v1alpha1/generated.proto
  api/nfd/v1alpha1/types.go
  deployment/base/nfd-crds/nfd-api-crds.yaml
  deployment/helm/node-feature-discovery/crds/nfd-api-crds.yaml
Labels: lgtm, cncf-cla: yes, size/XXL, approved

#1932 Introduce nfd client for image compatibilty
  Makefile
  api/image-compatibility/v1alpha1/spec.go
  api/nfd/v1alpha1/utils.go
  cmd/nfd/main.go
  cmd/nfd/subcmd/compat/compat.go
  cmd/nfd/subcmd/compat/options/platform.go
  cmd/nfd/subcmd/compat/validate-node.go
  cmd/nfd/subcmd/root.go
  docs/reference/feature-gates.md
  docs/reference/node-feature-client-reference.md
  docs/reference/versions.md
  docs/usage/image-compatibility.md
  examples/image-compatibility.yaml
  go.mod
  go.sum
  pkg/apis/nfd/nodefeaturerule/expression-api_test.go
  pkg/apis/nfd/nodefeaturerule/expression.go
  pkg/apis/nfd/nodefeaturerule/rule.go
  pkg/apis/nfd/nodefeaturerule/rule_test.go
  pkg/client-nfd/compat/artifact-client/client.go
  pkg/client-nfd/compat/artifact-client/mock_ArtifactClient.go
  pkg/client-nfd/compat/node-validator/node-validator.go
  pkg/client-nfd/compat/node-validator/node-validator_test.go
  pkg/client-nfd/compat/node-validator/status.go
  pkg/kubectl-nfd/dryrun.go
  pkg/nfd-master/nfd-master.go
  source/custom/custom.go
Labels: lgtm, cncf-cla: yes, size/XXL, approved, ok-to-test

#1988 Remove errors for nodes without NodeFeatures
  pkg/apis/nfd/nodefeaturerule/rule.go
  pkg/apis/nfd/nodefeaturerule/rule_test.go
Labels: lgtm, cncf-cla: yes, size/S, approved, ok-to-test

#1991 go.mod: bump golang.org/x/net to v0.33.0
  api/nfd/go.mod
  api/nfd/go.sum
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/S, approved

#1992 [release-0.17] Prepare v0.17 release
  Makefile
  README.md
  deployment/base/gc/gc.yaml
  deployment/base/master/master-deployment.yaml
  deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
  deployment/base/worker-daemonset/worker-daemonset.yaml
  deployment/base/worker-job/worker-job.yaml
  deployment/helm/node-feature-discovery/Chart.yaml
  deployment/helm/node-feature-discovery/README.md
  deployment/helm/node-feature-discovery/values.yaml
  deployment/overlays/prune/master-job.yaml
  docs/_config.yml
Labels: lgtm, cncf-cla: yes, size/M, approved

#1997 README: update to v0.17
  README.md
Labels: lgtm, cncf-cla: yes, size/XS, approved
