Repository kubernetes-sigs/node-feature-discovery, pull requests merged in 2024-11, with the labels that each got.

#1942 nfd-master: drop stale unreachable deprecation notices
  cmd/nfd-master/main.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1944 Taints: mark stable
  docs/usage/customization-guide.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1941 Drop support for hooks
  deployment/components/common/worker-mounts.yaml
  deployment/components/worker-config/nfd-worker.conf.example
  deployment/helm/node-feature-discovery/templates/worker.yaml
  deployment/helm/node-feature-discovery/values.yaml
  docs/deployment/image-variants.md
  docs/get-started/introduction.md
  docs/reference/worker-configuration-reference.md
  docs/usage/customization-guide.md
  pkg/nfd-worker/nfd-worker.go
  source/local/local.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#1889 Doc: Fix tilt up issue in feature discovering in developer guide
  docs/developer-guide/index.md
Labels: lgtm, cncf-cla: yes, size/M, approved, ok-to-test

#1948 Deprecate separate metrics and health port args
  docs/deployment/helm.md
  docs/reference/master-commandline-reference.md
  docs/reference/topology-updater-commandline-reference.md
  docs/reference/worker-commandline-reference.md
Labels: lgtm, cncf-cla: yes, size/S, approved

#1945 Release template: Document tagging for API submodule
  .github/ISSUE_TEMPLATE/new-patch-release.md
  .github/ISSUE_TEMPLATE/new-release.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1949 go.mod: bump cpuid to v2.2.9
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1950 nfd-master: drop resourceLabels
  cmd/nfd-master/main.go
  deployment/components/master-config/nfd-master.conf.example
  deployment/helm/node-feature-discovery/templates/master.yaml
  deployment/helm/node-feature-discovery/values.yaml
  docs/deployment/helm.md
  docs/reference/master-commandline-reference.md
  docs/reference/master-configuration-reference.md
  pkg/nfd-master/nfd-master-internal_test.go
  pkg/nfd-master/nfd-master.go
  test/e2e/node_feature_discovery_test.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#1935 Document AMXFP8 cpuid feature
  docs/usage/features.md
Labels: lgtm, cncf-cla: yes, size/XS, approved, ok-to-test

#1962 go.mod: bump kubernetes patch version
  api/nfd/go.mod
  api/nfd/go.sum
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/L, approved

#1961 pkg/utils: drop fswatcher
  pkg/utils/fswatcher.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#1956 chore: add metrics system prefix
  docs/deployment/metrics.md
  examples/grafana-dashboard.json
  pkg/nfd-gc/metrics.go
  pkg/nfd-master/metrics.go
  pkg/nfd-topology-updater/metrics.go
  pkg/nfd-worker/metrics.go
Labels: lgtm, cncf-cla: yes, size/L, approved
