Repository kubernetes-sigs/node-feature-discovery, pull requests merged in 2024-02, with the labels that each got.

#1577 [release-0.15] go.mod: bump github.com/opencontainers/runc to v1.1.12
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1578 [release-0.14] go.mod: bump github.com/opencontainers/runc to v1.1.12
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/S, approved

#1580 scripts/test-infra: bump golangci-lint to v1.56.1
  scripts/test-infra/verify.sh
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1583 scripts/test-infra: bump k8s logcheck to v0.8.1
  scripts/test-infra/verify.sh
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1579 Bump Go to v1.22
  Makefile
  go.mod
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1582 scripts/test-infra: bump helm to v3.14.0
  scripts/test-infra/verify.sh
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1587 helm: add priorityClassName option
  deployment/helm/node-feature-discovery/templates/master.yaml
  deployment/helm/node-feature-discovery/templates/nfd-gc.yaml
  deployment/helm/node-feature-discovery/templates/topologyupdater.yaml
  deployment/helm/node-feature-discovery/templates/worker.yaml
  deployment/helm/node-feature-discovery/values.yaml
  docs/deployment/helm.md
Labels: lgtm, cncf-cla: yes, size/S, approved

#1591 nfd-master: log errors on node update retries
  pkg/nfd-master/node-updater-pool.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1574 source/system: Add reading vendor information
  docs/usage/customization-guide.md
  examples/nodefeature.yaml
  source/system/system.go
Labels: lgtm, cncf-cla: yes, size/M, approved, ok-to-test
