Repository kubernetes-sigs/node-feature-discovery, pull requests merged in 2024-01, with the labels that each got.

#1532 helm: add post-delete hook that cleans up the node
  deployment/helm/node-feature-discovery/templates/post-delete-job.yaml
  docs/deployment/helm.md
  docs/deployment/uninstallation.md
Labels: lgtm, cncf-cla: yes, size/L, approved

#1534 deployment/kustomize: drop the sample cert-manager overlay
  deployment/overlays/samples/cert-manager/args.yaml
  deployment/overlays/samples/cert-manager/issuer.yaml
  deployment/overlays/samples/cert-manager/kustomization.yaml
  deployment/overlays/samples/cert-manager/master-cert.yaml
  deployment/overlays/samples/cert-manager/master-mounts.yaml
  deployment/overlays/samples/cert-manager/probes.yaml
  deployment/overlays/samples/cert-manager/worker-mounts.yaml
  deployment/overlays/samples/cert-manager/workers-cert.yaml
  docs/deployment/tls.md
Labels: lgtm, cncf-cla: yes, size/L, approved

#1535 nfd-master: run a separate gRPC health server
  cmd/nfd-master/main.go
  deployment/base/master/master-deployment.yaml
  deployment/helm/node-feature-discovery/templates/master.yaml
  pkg/nfd-master/nfd-master.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#1536 source/network: discover speed of virtual network interfaces
  docs/usage/customization-guide.md
  source/network/network.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1539 go.mod: update dependencies
  go.mod
  go.sum
  pkg/nfd-master/nfd-master-internal_test.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#1542 [release-0.13] docs: mark v0.13 as EOL
  docs/_includes/templates/content.liquid
Labels: lgtm, cncf-cla: yes, size/S, approved

#1505 chore: combine cpu count and thread_siblings functions into discover topology function
  source/cpu/cpu.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#1530 source/cpu: drop deprecated cpu-rdt labels
  docs/usage/features.md
  source/cpu/cpu.go
  test/e2e/e2e-test-config.example.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved

#1544 [release-0.15] Update references to release v0.15.1
  Makefile
  README.md
  deployment/base/gc/gc.yaml
  deployment/base/master/master-deployment.yaml
  deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
  deployment/base/worker-daemonset/worker-daemonset.yaml
  deployment/base/worker-job/worker-job.yaml
  deployment/helm/node-feature-discovery/Chart.yaml
  deployment/overlays/prune/master-job.yaml
  docs/_config.yml
Labels: lgtm, cncf-cla: yes, size/S, approved

#1552 Update readme to v0.15.1 release
  README.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1553 hack/generate: patch auto-generated deepcopy functions
  hack/generate.sh
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1537 apis/nfd: Trivial typo fix in tests
  pkg/apis/nfd/v1alpha1/feature_test.go
Labels: lgtm, cncf-cla: yes, size/XS, approved, ok-to-test

#1543 docs: update docs build dependencies
  docs/Gemfile.lock
Labels: lgtm, cncf-cla: yes, size/M, approved

#1554 topology-updater: initialize properly with -no-publish
  pkg/nfd-topology-updater/nfd-topology-updater.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#1555 topology-updater: document the -no-publish flag correctly
  cmd/nfd-topology-updater/main.go
  docs/reference/topology-updater-commandline-reference.md
Labels: lgtm, cncf-cla: yes, size/S, approved

#1558 Wrap nested errors
  pkg/nfd-master/nfd-master.go
  pkg/resourcemonitor/podresourcesscanner.go
  pkg/utils/fswatcher.go
  pkg/utils/klog/klog.go
  pkg/utils/tls.go
  source/cpu/power_amd64.go
  source/local/local.go
  source/pci/utils.go
  source/usb/utils.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#1562 pkg/utils: move GetKubeconfig from pkg/apihelper here
  pkg/apihelper/k8shelpers.go
  pkg/nfd-gc/nfd-gc.go
  pkg/nfd-master/nfd-master.go
  pkg/nfd-topology-updater/nfd-topology-updater.go
  pkg/nfd-worker/nfd-worker.go
  pkg/utils/kubernetes.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#1564 OWNERS: add AhmedGrati as a reviewer
  OWNERS
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1565 deployment/helm: don't deploy topology-updater conf unnecessarily
  deployment/helm/node-feature-discovery/templates/nfd-topologyupdater-conf.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1568 pkg/utils: move JsonPatch from pkg/apihelper
  pkg/apihelper/apihelpers.go
  pkg/apihelper/k8shelpers.go
  pkg/apihelper/mock_APIHelpers.go
  pkg/nfd-master/nfd-master-internal_test.go
  pkg/nfd-master/nfd-master.go
  pkg/nfd-master/node-updater-pool_test.go
  pkg/utils/jsonpatch.go
  test/e2e/node_feature_discovery_test.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#1570 nfd-master: ditch apihelper
  pkg/nfd-master/nfd-master-internal_test.go
  pkg/nfd-master/nfd-master.go
  pkg/nfd-master/node-updater-pool_test.go
Labels: lgtm, cncf-cla: yes, size/XL, approved

#1567 topology-updater: ditch apihelper
  pkg/nfd-topology-updater/nfd-topology-updater.go
  pkg/resourcemonitor/podresourcesscanner.go
  pkg/resourcemonitor/podresourcesscanner_test.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#1561 Drop pkg/apihelper
  pkg/apihelper/apihelpers.go
  pkg/apihelper/k8shelpers.go
  pkg/apihelper/mock_APIHelpers.go
Labels: lgtm, cncf-cla: yes, size/L, approved, needs-rebase

#1571 nfd-master: fix node status patching
  pkg/nfd-master/nfd-master.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1444 docs: add KEP of Spiffe integration
  enhancements/1186-spiffe-integration/README.md
  enhancements/1186-spiffe-integration/nfd-spiffe.png
Labels: lgtm, cncf-cla: yes, size/M, approved
