Repository kubernetes-sigs/node-feature-discovery, pull requests merged in 2024-06, with the labels that each got.

#1723 [release-0.14] docs: mark v0.14 EOL'd
  docs/_includes/templates/content.liquid
Labels: lgtm, cncf-cla: yes, size/S, approved

#1729 topology-updater: properly handle IPv6 from NODE_ADDRESS
  cmd/nfd-topology-updater/main.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#1728 helm: remove defaults CPU limits
  deployment/helm/node-feature-discovery/values.yaml
  docs/deployment/helm.md
Labels: lgtm, cncf-cla: yes, size/S, approved, ok-to-test

#1739 Fix the problem with starting the master with empty cache
  pkg/nfd-master/nfd-api-controller.go
Labels: lgtm, cncf-cla: yes, size/XS, approved, ok-to-test

#1746 ensure post-delete-job's service account matches ref in job spec
  deployment/helm/node-feature-discovery/templates/post-delete-job.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved, ok-to-test
