Repository kubernetes-sigs/node-feature-discovery, pull requests merged in 2024-03, with the labels that each got.

#1598 helm: add ability to use a custom issuer
  deployment/helm/node-feature-discovery/templates/cert-manager-certs.yaml
  deployment/helm/node-feature-discovery/templates/cert-manager-issuer.yaml
  deployment/helm/node-feature-discovery/values.yaml
  docs/deployment/helm.md
Labels: lgtm, cncf-cla: yes, size/S, approved, ok-to-test

#1606 generate: update autogenerate tools
  Dockerfile_generator
  deployment/base/nfd-crds/nfd-api-crds.yaml
  deployment/helm/node-feature-discovery/crds/nfd-api-crds.yaml
  pkg/apis/nfd/v1alpha1/generated.pb.go
  pkg/apis/nfd/v1alpha1/generated.proto
  pkg/apis/nfd/v1alpha1/zz_generated.deepcopy.go
  pkg/generated/clientset/versioned/clientset.go
  pkg/generated/clientset/versioned/fake/clientset_generated.go
  pkg/generated/clientset/versioned/fake/doc.go
  pkg/generated/clientset/versioned/fake/register.go
  pkg/generated/clientset/versioned/scheme/doc.go
  pkg/generated/clientset/versioned/scheme/register.go
  pkg/generated/clientset/versioned/typed/nfd/v1alpha1/doc.go
  pkg/generated/clientset/versioned/typed/nfd/v1alpha1/fake/doc.go
  pkg/generated/clientset/versioned/typed/nfd/v1alpha1/fake/fake_nfd_client.go
  pkg/generated/clientset/versioned/typed/nfd/v1alpha1/fake/fake_nodefeature.go
  pkg/generated/clientset/versioned/typed/nfd/v1alpha1/fake/fake_nodefeaturerule.go
  pkg/generated/clientset/versioned/typed/nfd/v1alpha1/generated_expansion.go
  pkg/generated/clientset/versioned/typed/nfd/v1alpha1/nfd_client.go
  pkg/generated/clientset/versioned/typed/nfd/v1alpha1/nodefeature.go
  pkg/generated/clientset/versioned/typed/nfd/v1alpha1/nodefeaturerule.go
  pkg/generated/informers/externalversions/factory.go
  pkg/generated/informers/externalversions/generic.go
  pkg/generated/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/generated/informers/externalversions/nfd/interface.go
  pkg/generated/informers/externalversions/nfd/v1alpha1/interface.go
  pkg/generated/informers/externalversions/nfd/v1alpha1/nodefeature.go
  pkg/generated/informers/externalversions/nfd/v1alpha1/nodefeaturerule.go
  pkg/generated/listers/nfd/v1alpha1/expansion_generated.go
  pkg/generated/listers/nfd/v1alpha1/nodefeature.go
  pkg/generated/listers/nfd/v1alpha1/nodefeaturerule.go
  pkg/labeler/labeler.pb.go
  pkg/labeler/mock_LabelerClient.go
  pkg/podres/mocks/PodResourcesListerClient.go
  source/mock_LabelSource.go
Labels: lgtm, cncf-cla: yes, size/XL, approved

#1610 [release-0.15] Update references to release v0.15.2
  Makefile
  README.md
  deployment/base/gc/gc.yaml
  deployment/base/master/master-deployment.yaml
  deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
  deployment/base/worker-daemonset/worker-daemonset.yaml
  deployment/base/worker-job/worker-job.yaml
  deployment/helm/node-feature-discovery/Chart.yaml
  deployment/overlays/prune/master-job.yaml
  docs/_config.yml
Labels: lgtm, cncf-cla: yes, size/S, approved

#1590 apis/nfd/validate: use testify/assert for checking test results
  pkg/apis/nfd/validate/validate.go
  pkg/apis/nfd/validate/validate_test.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#1611 Update readme to v0.15.2 release
  README.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1605 Update generate scripts to use latest code_gen functions
  Dockerfile_generator
  Makefile
  go.mod
  go.sum
  hack/generate.sh
  hack/tools.go
  hack/update_codegen.sh
  pkg/apis/nfd/v1alpha1/types.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#1612 nfd-master: mark the -crd-controller flag as deprecated
  cmd/nfd-master/main.go
  docs/reference/master-commandline-reference.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1619 [release-0.14] Dockerfile: bump grpc-health-probe to v0.4.25
  Dockerfile
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1620 Use close to signal stop channedl in worker and topology-updater
  pkg/nfd-topology-updater/nfd-topology-updater.go
  pkg/nfd-worker/nfd-worker.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#1615 nfd-master: fix memory leak in nfd api-controller
  pkg/nfd-master/nfd-api-controller.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1625 [release-0.14] go.mod: bump protobuf deps
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/S, approved

#1624 [release-0.15] go.mod: bump protobuf deps
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/S, approved

#1626 [release-0.14] Update references to release v0.14.5
  Makefile
  README.md
  deployment/base/gc/gc.yaml
  deployment/base/master-worker-combined/master-worker-daemonset.yaml
  deployment/base/master/master-deployment.yaml
  deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
  deployment/base/worker-daemonset/worker-daemonset.yaml
  deployment/base/worker-job/worker-job.yaml
  deployment/helm/node-feature-discovery/Chart.yaml
  deployment/overlays/prune/master-job.yaml
  docs/_config.yml
Labels: lgtm, cncf-cla: yes, size/S, approved

#1627 [release-0.15] Update references to release v0.15.3
  README.md
  deployment/base/gc/gc.yaml
  deployment/base/master/master-deployment.yaml
  deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
  deployment/base/worker-daemonset/worker-daemonset.yaml
  deployment/base/worker-job/worker-job.yaml
  deployment/helm/node-feature-discovery/Chart.yaml
  deployment/overlays/prune/master-job.yaml
  docs/_config.yml
Labels: lgtm, cncf-cla: yes, size/S, approved

#1628 Update readme to v0.15.3 release
  README.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1623 Add FeatureGate framework to handle new features
  cmd/nfd-master/main.go
  cmd/nfd-worker/main.go
  deployment/helm/node-feature-discovery/templates/clusterrole.yaml
  deployment/helm/node-feature-discovery/templates/clusterrolebinding.yaml
  deployment/helm/node-feature-discovery/templates/master.yaml
  deployment/helm/node-feature-discovery/templates/nfd-gc.yaml
  deployment/helm/node-feature-discovery/templates/service.yaml
  deployment/helm/node-feature-discovery/templates/serviceaccount.yaml
  deployment/helm/node-feature-discovery/templates/worker.yaml
  deployment/helm/node-feature-discovery/values.yaml
  docs/deployment/helm.md
  docs/reference/feature-gates.md
  docs/reference/master-commandline-reference.md
  docs/reference/worker-commandline-reference.md
  docs/usage/nfd-gc.md
  docs/usage/nfd-master.md
  pkg/features/features.go
  pkg/nfd-master/nfd-master-internal_test.go
  pkg/nfd-master/nfd-master.go
  pkg/nfd-worker/nfd-worker.go
  pkg/nfd-worker/nfd-worker_test.go
  pkg/utils/featuregate/featuregate.go
  pkg/utils/featuregate/featuregate_test.go
  scripts/test-infra/logcheck.conf
Labels: lgtm, cncf-cla: yes, size/XL, approved

#1630 replace AhmedGrati account with TessaIO as reviewer
  OWNERS
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1585 add swap support in nfd
  deployment/components/common/worker-mounts.yaml
  deployment/helm/node-feature-discovery/templates/worker.yaml
  docs/usage/customization-guide.md
  docs/usage/features.md
  pkg/utils/hostpath/hostpath.go
  source/memory/memory.go
  source/memory/memory_test.go
  source/memory/testdata/noswap
  source/memory/testdata/swap
Labels: lgtm, cncf-cla: yes, size/M, approved

#1595 nfd-master: check if node exists before trying update
  pkg/nfd-master/node-updater-pool.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#1632 Remove references to -enable-nodefeature-api flag
  cmd/nfd-master/main.go
  cmd/nfd-worker/main.go
  docs/deployment/tls.md
  docs/developer-guide/index.md
  docs/reference/master-commandline-reference.md
  docs/reference/master-configuration-reference.md
  docs/reference/worker-commandline-reference.md
  docs/usage/customization-guide.md
  test/e2e/node_feature_discovery_test.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#1602 Add owner reference to NRT object
  deployment/base/rbac-topologyupdater/topologyupdater-clusterrole.yaml
  deployment/helm/node-feature-discovery/templates/clusterrole.yaml
  pkg/nfd-topology-updater/nfd-topology-updater.go
  test/e2e/topology_updater_test.go
  test/e2e/utils/rbac.go
Labels: lgtm, cncf-cla: yes, size/L, approved, ok-to-test

#1596 nfd-master: retry node updates indefinitely
  pkg/nfd-master/node-updater-pool.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#1609 nfd-worker: Add liveness probe
  cmd/nfd-worker/main.go
  deployment/base/worker-daemonset/worker-daemonset.yaml
  deployment/helm/node-feature-discovery/templates/worker.yaml
  deployment/helm/node-feature-discovery/values.yaml
  pkg/nfd-worker/nfd-worker.go
Labels: lgtm, cncf-cla: yes, size/M, approved, ok-to-test

#1634 topology-updater: Set APIVersion, Kind in the OwnerReference explicitly
  pkg/nfd-topology-updater/nfd-topology-updater.go
Labels: lgtm, cncf-cla: yes, size/XS, approved, ok-to-test

#1635 helm: fix invalid name of host-swaps volume
  deployment/helm/node-feature-discovery/templates/worker.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1641 nfd-master: do nfd API scheme registration in an init function
  pkg/nfd-master/nfd-api-controller.go
Labels: lgtm, cncf-cla: yes, size/XS, approved
