Repository kubernetes-sigs/node-feature-discovery, pull requests merged in 2024-05, with the labels that each got.

#1684 build: specify buildx builder name everywhere
  Makefile
  hack/init-buildx.sh
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1694 source/kernel: silence misleading error on selinux detection
  source/kernel/selinux.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1707 nfd-master: add DisableAutoPrefix feature gate
  docs/reference/feature-gates.md
  docs/reference/master-configuration-reference.md
  pkg/features/features.go
  pkg/nfd-master/nfd-master-internal_test.go
  pkg/nfd-master/nfd-master.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#1708 Re-add -enable-nodefeature-api cmdline flag
  cmd/nfd-master/main.go
  cmd/nfd-worker/main.go
  deployment/helm/node-feature-discovery/templates/clusterrole.yaml
  deployment/helm/node-feature-discovery/templates/clusterrolebinding.yaml
  deployment/helm/node-feature-discovery/templates/master.yaml
  deployment/helm/node-feature-discovery/templates/nfd-gc.yaml
  deployment/helm/node-feature-discovery/templates/service.yaml
  deployment/helm/node-feature-discovery/templates/serviceaccount.yaml
  deployment/helm/node-feature-discovery/templates/worker.yaml
  deployment/helm/node-feature-discovery/values.yaml
  docs/deployment/helm.md
  docs/reference/master-commandline-reference.md
  pkg/nfd-master/nfd-master.go
  pkg/nfd-worker/nfd-worker.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#1487 Add NodeFeatureGroup API
  Dockerfile_generator
  api/generated/clientset/versioned/typed/nfd/v1alpha1/fake/fake_nfd_client.go
  api/generated/clientset/versioned/typed/nfd/v1alpha1/fake/fake_nodefeaturegroup.go
  api/generated/clientset/versioned/typed/nfd/v1alpha1/generated_expansion.go
  api/generated/clientset/versioned/typed/nfd/v1alpha1/nfd_client.go
  api/generated/clientset/versioned/typed/nfd/v1alpha1/nodefeaturegroup.go
  api/generated/informers/externalversions/generic.go
  api/generated/informers/externalversions/nfd/v1alpha1/interface.go
  api/generated/informers/externalversions/nfd/v1alpha1/nodefeaturegroup.go
  api/generated/listers/nfd/v1alpha1/expansion_generated.go
  api/generated/listers/nfd/v1alpha1/nodefeaturegroup.go
  api/nfd/v1alpha1/register.go
  api/nfd/v1alpha1/types.go
  api/nfd/v1alpha1/zz_generated.deepcopy.go
  deployment/base/nfd-crds/nfd-api-crds.yaml
  deployment/base/rbac/master-clusterrole.yaml
  deployment/helm/node-feature-discovery/crds/nfd-api-crds.yaml
  deployment/helm/node-feature-discovery/templates/clusterrole.yaml
  deployment/helm/node-feature-discovery/values.yaml
  docs/reference/feature-gates.md
  docs/usage/custom-resources.md
  docs/usage/customization-guide.md
  examples/nodefeaturegroup.yaml
  hack/update_codegen.sh
  pkg/apis/nfd/nodefeaturerule/rule.go
  pkg/features/features.go
  pkg/nfd-master/metrics.go
  pkg/nfd-master/nfd-api-controller.go
  pkg/nfd-master/nfd-master-internal_test.go
  pkg/nfd-master/nfd-master.go
  pkg/nfd-master/node-updater-pool.go
  pkg/nfd-master/updater-pool.go
  pkg/nfd-master/updater-pool_test.go
  pkg/nfd-worker/nfd-worker_test.go
  test/e2e/data/nodefeaturegroup-1.yaml
  test/e2e/node_feature_discovery_test.go
  test/e2e/utils/crd.go
  test/e2e/utils/rbac.go
Labels: lgtm, cncf-cla: yes, size/XXL, approved

#1714 api/nfd: document all undocumented fields in the types
  api/nfd/v1alpha1/types.go
  deployment/base/nfd-crds/nfd-api-crds.yaml
  deployment/helm/node-feature-discovery/crds/nfd-api-crds.yaml
Labels: lgtm, cncf-cla: yes, size/M, approved

#1713 nfd-worker: improved log when creating NodeFeature object
  pkg/nfd-worker/nfd-worker.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1673 cpu: advertise AVX10 version
  deployment/nodefeaturerule/samples/nodefeaturerule-cpu.yaml
  docs/usage/customization-guide.md
  docs/usage/features.md
  source/cpu/cpu.go
  source/cpu/cpuid_amd64.go
  source/cpu/cpuid_linux_arm.go
  source/cpu/cpuid_linux_arm64.go
  source/cpu/cpuid_linux_ppc64le.go
  source/cpu/cpuid_linux_s390x.go
  source/cpu/cpuid_stub.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#1716 docs/helm: document all feature gates
  docs/deployment/helm.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1718 docs: add more cross-references to NodeFeatureGroup API
  docs/usage/custom-resources.md
  docs/usage/customization-guide.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1720 Revert "build(deps): bump actions/checkout from 1 to 4"
  .github/workflows/gh-pages.yml
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1722 Update readme to v0.16.0 release
  README.md
Labels: lgtm, cncf-cla: yes, size/XS, approved
