Repository kubernetes-sigs/node-feature-discovery, pull requests merged in 2025-10, with the labels that each got.

#2309 helm: fixes
  deployment/helm/node-feature-discovery/templates/master-pdb.yaml
  deployment/helm/node-feature-discovery/templates/master.yaml
  deployment/helm/node-feature-discovery/templates/nfd-gc-pdb.yaml
  deployment/helm/node-feature-discovery/values.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved

#2312 scripts/test-infra/push-image: more robust parsing of version
  scripts/test-infra/push-image.sh
Labels: lgtm, cncf-cla: yes, size/XS, approved

#2317 fix(deploy,helm,overlays): use correct port for PodMonitor
  deployment/helm/node-feature-discovery/templates/prometheus.yaml
  deployment/overlays/prometheus/monitor.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved, ok-to-test

#2314 README: release v0.18.0
  README.md
  netlify.toml
Labels: lgtm, cncf-cla: yes, size/XS, approved

#2320 [release-0.16] docs: mark v0.16 EOL
  docs/_includes/templates/content.liquid
Labels: lgtm, cncf-cla: yes, size/S, approved

#2327 [release-0.18] Release v0.18.1
  README.md
  deployment/base/gc/gc.yaml
  deployment/base/master/master-deployment.yaml
  deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
  deployment/base/worker-daemonset/worker-daemonset.yaml
  deployment/base/worker-job/worker-job.yaml
  deployment/helm/node-feature-discovery/Chart.yaml
  deployment/overlays/prune/master-job.yaml
  docs/_config.yml
Labels: lgtm, cncf-cla: yes, size/S, approved

#2330 helm: common documentation in html docs and chart readme
  Makefile
  deployment/helm/node-feature-discovery/.helmignore
  deployment/helm/node-feature-discovery/README.md
  deployment/helm/node-feature-discovery/README.md.gotmpl
  deployment/helm/node-feature-discovery/_metadata-site.gotmpl
  deployment/helm/node-feature-discovery/_metadata.gotmpl
  deployment/helm/node-feature-discovery/_templates.gotmpl
  docs/deployment/helm.md
  docs/deployment/helm.md.gotmpl
  hack/prepare-release.sh
Labels: lgtm, cncf-cla: yes, size/XL, approved
