Repository kubernetes-sigs/node-feature-discovery, pull requests merged in 2025-03, with the labels that each got.

#2056 Introduce memory.hugepages feature
  docs/usage/customization-guide.md
  source/memory/memory.go
  source/memory/memory_test.go
  source/memory/testdata/hugepages/kernel/mm/hugepages/hugepages-1048576kB/nr_hugepages
  source/memory/testdata/hugepages/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages
Labels: lgtm, cncf-cla: yes, size/L, approved, needs-ok-to-test

#2068 Bugfix: handle matchAny and matchFeatures when they appear in one spec
  pkg/apis/nfd/nodefeaturerule/rule.go
  pkg/client-nfd/compat/node-validator/node-validator_test.go
Labels: lgtm, cncf-cla: yes, size/M, approved, needs-ok-to-test

#2069 nodefeaturerule: refactor template handling
  pkg/apis/nfd/nodefeaturerule/rule.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#2070 Remove deprecated toleration/affinity value
  deployment/components/common/master-affinity.yaml
  deployment/helm/node-feature-discovery/values.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved

#2072 Drop gRPC startup probe
  deployment/base/master/master-deployment.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved

#2083 Replace golang.org/x/exp/maps with the standard library's maps package.
  go.mod
  pkg/apis/nfd/nodefeaturerule/expression.go
  pkg/nfd-worker/nfd-worker.go
  pkg/utils/flags.go
  source/pci/pci.go
  source/usb/usb.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#2082 Allow configuration of image pull secrets in post-delete job
  deployment/helm/node-feature-discovery/templates/post-delete-job.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved, ok-to-test

#2084 test: fix erroneous assert
  pkg/apis/nfd/nodefeaturerule/rule_test.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#2085 api/nodefeaturegroup: add vars
  api/nfd/v1alpha1/types.go
  api/nfd/v1alpha1/zz_generated.deepcopy.go
  deployment/base/nfd-crds/nfd-api-crds.yaml
  deployment/helm/node-feature-discovery/crds/nfd-api-crds.yaml
  pkg/apis/nfd/nodefeaturerule/grouprule_test.go
  pkg/apis/nfd/nodefeaturerule/rule.go
  pkg/nfd-master/nfd-master.go
Labels: lgtm, cncf-cla: yes, size/XL, approved

#2071 Add new comparison operators
  api/nfd/v1alpha1/types.go
  docs/usage/customization-guide.md
  pkg/apis/nfd/nodefeaturerule/expression.go
  pkg/apis/nfd/nodefeaturerule/expression_test.go
Labels: lgtm, cncf-cla: yes, size/M, approved, ok-to-test

#2087 compat/api: use GroupRule type
  api/image-compatibility/v1alpha1/spec.go
  docs/usage/image-compatibility.md
  pkg/client-nfd/compat/node-validator/node-validator.go
  pkg/client-nfd/compat/node-validator/node-validator_test.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#2088 Apply modernize analysis improvements
  pkg/apis/nfd/nodefeaturerule/expression.go
  pkg/apis/nfd/template/template.go
  pkg/kubectl-nfd/dryrun.go
  pkg/nfd-gc/nfd-gc_test.go
  pkg/nfd-master/updater-pool.go
  pkg/utils/featuregate/featuregate.go
  pkg/utils/flags.go
  pkg/utils/memory_resources.go
  pkg/utils/memory_resources_test.go
  source/custom/api/expression.go
  source/kernel/kconfig.go
  source/memory/memory.go
  source/usb/utils.go
  test/e2e/node_feature_discovery_test.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#2105 docs: bump docs build deps
  docs/Gemfile.lock
Labels: lgtm, cncf-cla: yes, size/M, approved

#2106 api: bump go to v1.23
  api/nfd/go.mod
Labels: lgtm, cncf-cla: yes, size/XS, approved

#2044 Discover MTU of physical and virtual network devices
  docs/usage/customization-guide.md
  source/network/network.go
Labels: lgtm, cncf-cla: yes, size/XS, approved, ok-to-test

#2098 nfd-master: make the NodeFeatureGroupAPI feature gate effective
  pkg/nfd-master/nfd-master.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#2107 api/nfd: fix broken unit test
  Makefile
  api/nfd/v1alpha1/feature_test.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#2111 Update dependencies
  api/nfd/go.mod
  api/nfd/go.sum
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/L, approved

#2113 [release-0.17] Update dependencies
  api/nfd/go.mod
  api/nfd/go.sum
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/L, approved

#2110 [release-0.16] nfd-master: skip NodeFeatureGroup informers if feature gate disabled
  pkg/nfd-master/nfd-master.go
Labels: lgtm, cncf-cla: yes, size/XS, approved
