Repository kubernetes-sigs/node-feature-discovery, pull requests merged in 2025-01, with the labels that each got.

#2004 Drop setup of grpc logging
  cmd/nfd-master/main.go
  cmd/nfd-topology-updater/main.go
  cmd/nfd-worker/main.go
  pkg/utils/grpc_log.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#2006 Add support running with OwnerReferencesPermissionEnforcement
  deployment/base/rbac/worker-role.yaml
  deployment/helm/node-feature-discovery/templates/role.yaml
  pkg/nfd-worker/nfd-worker.go
  test/e2e/utils/rbac.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#2012 go.mod: update golang.org deps
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/S, approved

#2013 [release-0.16] Add support running with OwnerReferencesPermissionEnforcement
  deployment/base/rbac/worker-role.yaml
  deployment/helm/node-feature-discovery/templates/role.yaml
  pkg/nfd-worker/nfd-worker.go
  test/e2e/utils/rbac.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#2009 [release-0.15] docs: mark v0.15 EOL
  docs/_includes/templates/content.liquid
Labels: lgtm, cncf-cla: yes, size/S, approved

#2015 [release-0.16] go.mod: update golang.org deps
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/M, approved

#2010 Bugfixes for image compatibility feature
  pkg/apis/nfd/nodefeaturerule/rule.go
  pkg/client-nfd/compat/artifact-client/client.go
  pkg/client-nfd/compat/node-validator/node-validator.go
  pkg/client-nfd/compat/node-validator/node-validator_test.go
Labels: lgtm, cncf-cla: yes, size/M, approved, ok-to-test

#2017 [release-0.16] Release v0.16.7
  Makefile
  README.md
  deployment/base/gc/gc.yaml
  deployment/base/master/master-deployment.yaml
  deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
  deployment/base/worker-daemonset/worker-daemonset.yaml
  deployment/base/worker-job/worker-job.yaml
  deployment/helm/node-feature-discovery/Chart.yaml
  deployment/overlays/prune/master-job.yaml
  docs/_config.yml
Labels: lgtm, cncf-cla: yes, size/S, approved

#2018 [release-0.17] Release v0.17.1
  README.md
  deployment/base/gc/gc.yaml
  deployment/base/master/master-deployment.yaml
  deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
  deployment/base/worker-daemonset/worker-daemonset.yaml
  deployment/base/worker-job/worker-job.yaml
  deployment/helm/node-feature-discovery/Chart.yaml
  deployment/overlays/prune/master-job.yaml
  docs/_config.yml
Labels: lgtm, cncf-cla: yes, size/S, approved

#2025 Make DNS Policy configurable in helm chart
  deployment/helm/node-feature-discovery/templates/master.yaml
  deployment/helm/node-feature-discovery/templates/nfd-gc.yaml
  deployment/helm/node-feature-discovery/templates/topologyupdater.yaml
  deployment/helm/node-feature-discovery/templates/worker.yaml
  deployment/helm/node-feature-discovery/values.yaml
  docs/deployment/helm.md
Labels: lgtm, cncf-cla: yes, size/S, approved, tide/merge-method-squash

#2027 deps: bump kubernetes to v0.32.1
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/L, approved

#1990 test: add utility for namespace labels patching and add the test cases for denyNodeFeatureLabels restriction
  pkg/utils/jsonpatch.go
  test/e2e/node_feature_discovery_test.go
  test/e2e/utils/namespace/namespace.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#2035 helm: fix usage of worker.extraArgs
  deployment/helm/node-feature-discovery/templates/worker.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1929 nfd-worker: use single http port for metrics and healthz
  cmd/nfd-worker/main.go
  deployment/base/worker-daemonset/worker-daemonset.yaml
  deployment/helm/node-feature-discovery/templates/worker.yaml
  deployment/helm/node-feature-discovery/values.yaml
  docs/deployment/helm.md
  pkg/nfd-worker/nfd-worker.go
Labels: lgtm, cncf-cla: yes, size/L, approved
