Repository kubernetes-sigs/node-feature-discovery, pull requests merged in 2025-02, with the labels that each got.

#2028 Refactoring of image compatibility node validator
  pkg/client-nfd/compat/node-validator/node-validator.go
  pkg/client-nfd/compat/node-validator/node-validator_test.go
Labels: lgtm, cncf-cla: yes, size/XL, approved, ok-to-test

#2040 Allow DS_PROMETHEUS substitution for grafana dashboard
  examples/grafana-dashboard.json
Labels: lgtm, cncf-cla: yes, size/M, approved, ok-to-test

#2043 Bump go to 1.24
  Makefile
  Tiltfile
  go.mod
  hack/tools.go
  scripts/test-infra/verify.sh
Labels: lgtm, cncf-cla: yes, size/M, approved

#2048 Bump vektra/mockery to v2.52.2
  Dockerfile_generator
  api/generated/clientset/versioned/clientset.go
  api/generated/clientset/versioned/fake/clientset_generated.go
  api/generated/clientset/versioned/fake/doc.go
  api/generated/clientset/versioned/fake/register.go
  api/generated/clientset/versioned/scheme/doc.go
  api/generated/clientset/versioned/scheme/register.go
  api/generated/clientset/versioned/typed/nfd/v1alpha1/doc.go
  api/generated/clientset/versioned/typed/nfd/v1alpha1/fake/doc.go
  api/generated/clientset/versioned/typed/nfd/v1alpha1/fake/fake_nfd_client.go
  api/generated/clientset/versioned/typed/nfd/v1alpha1/fake/fake_nodefeature.go
  api/generated/clientset/versioned/typed/nfd/v1alpha1/fake/fake_nodefeaturegroup.go
  api/generated/clientset/versioned/typed/nfd/v1alpha1/fake/fake_nodefeaturerule.go
  api/generated/clientset/versioned/typed/nfd/v1alpha1/generated_expansion.go
  api/generated/clientset/versioned/typed/nfd/v1alpha1/nfd_client.go
  api/generated/clientset/versioned/typed/nfd/v1alpha1/nodefeature.go
  api/generated/clientset/versioned/typed/nfd/v1alpha1/nodefeaturegroup.go
  api/generated/clientset/versioned/typed/nfd/v1alpha1/nodefeaturerule.go
  api/generated/informers/externalversions/factory.go
  api/generated/informers/externalversions/generic.go
  api/generated/informers/externalversions/internalinterfaces/factory_interfaces.go
  api/generated/informers/externalversions/nfd/interface.go
  api/generated/informers/externalversions/nfd/v1alpha1/interface.go
  api/generated/informers/externalversions/nfd/v1alpha1/nodefeature.go
  api/generated/informers/externalversions/nfd/v1alpha1/nodefeaturegroup.go
  api/generated/informers/externalversions/nfd/v1alpha1/nodefeaturerule.go
  api/generated/listers/nfd/v1alpha1/expansion_generated.go
  api/generated/listers/nfd/v1alpha1/nodefeature.go
  api/generated/listers/nfd/v1alpha1/nodefeaturegroup.go
  api/generated/listers/nfd/v1alpha1/nodefeaturerule.go
  api/nfd/v1alpha1/zz_generated.deepcopy.go
  pkg/client-nfd/compat/artifact-client/mock_ArtifactClient.go
  pkg/podres/mocks/PodResourcesListerClient.go
  source/mock_LabelSource.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#2047 deps: bump k/k to v1.32.2
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/L, approved

#2053 [release-0.17] deps: bump k/k to v1.32.2
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/L, approved

#1946 nfd-master: serve metrics and healthz endpoint on the same port
  cmd/nfd-master/main.go
  deployment/base/master/master-deployment.yaml
  deployment/helm/node-feature-discovery/templates/master.yaml
  deployment/helm/node-feature-discovery/values.yaml
  docs/deployment/helm.md
  pkg/nfd-master/nfd-master.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#1947 nfd-topology-updater: serve metrics and healthz on the same port
  cmd/nfd-topology-updater/main.go
  deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
  deployment/helm/node-feature-discovery/templates/topologyupdater.yaml
  deployment/helm/node-feature-discovery/values.yaml
  docs/deployment/helm.md
  pkg/nfd-topology-updater/nfd-topology-updater.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#2057 [release-0.17] Release 0.17
  Makefile
  README.md
  deployment/base/gc/gc.yaml
  deployment/base/master/master-deployment.yaml
  deployment/base/topologyupdater-daemonset/topologyupdater-daemonset.yaml
  deployment/base/worker-daemonset/worker-daemonset.yaml
  deployment/base/worker-job/worker-job.yaml
  deployment/helm/node-feature-discovery/Chart.yaml
  deployment/overlays/prune/master-job.yaml
  docs/_config.yml
Labels: lgtm, cncf-cla: yes, size/S, approved

#2038 Use Sprig template functions and add asLabelValue function
  docs/usage/customization-guide.md
  go.mod
  go.sum
  pkg/apis/nfd/nodefeaturerule/rule.go
  pkg/apis/nfd/template/template.go
  pkg/apis/nfd/validate/validate.go
Labels: lgtm, cncf-cla: yes, size/L, approved, ok-to-test

#2061 README: update to v0.17.2
  README.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#2062 go.mod: bump cpuid to v2.2.10
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/XS, approved

#2064 source/cpu: suppress cpufreq related error if driver is not enabled
  source/cpu/pstate_amd64.go
Labels: lgtm, cncf-cla: yes, size/XS, approved
