Repository kubernetes-sigs/node-feature-discovery, pull requests merged in 2025-04, with the labels that each got.

#2115 Document AMXCOMPLEX, AMXTF32 cpuid features
  docs/usage/features.md
Labels: lgtm, cncf-cla: yes, size/XS, approved, ok-to-test

#2112 [release-0.16] Update deps
  Makefile
  api/nfd/go.mod
  api/nfd/go.sum
  go.mod
  go.sum
  scripts/test-infra/verify.sh
  test/e2e/utils/noderesourcetopology.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#2116 nfd-master: drop the deprecated autoDefaultNs config option
  deployment/components/master-config/nfd-master.conf.example
  deployment/helm/node-feature-discovery/values.yaml
  docs/reference/master-configuration-reference.md
  docs/usage/customization-guide.md
  pkg/nfd-master/nfd-master.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#2055 feat: add support to differentiate specific hypervisors on s390x
  docs/usage/customization-guide.md
  source/cpu/cpu.go
Labels: lgtm, cncf-cla: yes, size/M, approved, ok-to-test

#2076 Control post-delete hook
  deployment/helm/node-feature-discovery/templates/post-delete-job.yaml
  deployment/helm/node-feature-discovery/values.yaml
  docs/deployment/helm.md
Labels: lgtm, cncf-cla: yes, size/XS, approved, ok-to-test

#2130 nfd-master: cleanup nil checks
  pkg/nfd-master/nfd-master.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#2129 nfd-master: clean up api controller
  pkg/nfd-master/nfd-api-controller.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#2131 nfd-master: fix memory leak when leader election is enabled
  pkg/nfd-master/nfd-master.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#2134 cloudbuild: bump gcb image
  cloudbuild.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved

#2136 [release-0.16] nfd-master: fix memory leak when leader election is enabled
  pkg/nfd-master/nfd-master.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#2135 [release-0.17] nfd-master: fix memory leak when leader election is enabled
  pkg/nfd-master/nfd-master.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#2141 README: bump quickstart snippet to v0.17.3
  README.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#2128 Makefile: Add helm-push target
  Makefile
Labels: lgtm, cncf-cla: yes, size/XS, approved, ok-to-test
