Repository kubernetes-sigs/node-feature-discovery, pull requests merged in 2025-05, with the labels that each got.

#2144 go.mod: bump kubernetes to v1.33
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/L, approved

#2114 Enable unprefixed label setting via feature gate
  docs/reference/feature-gates.md
  pkg/nfd-master/nfd-master-internal_test.go
  pkg/nfd-master/nfd-master.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#2146 helm: Inherit resource limits for prune job
  deployment/helm/node-feature-discovery/templates/post-delete-job.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved, ok-to-test

#2151 scripts: Add helm-push to push-image.sh script
  scripts/test-infra/push-image.sh
Labels: lgtm, cncf-cla: yes, size/XS, approved, ok-to-test

#2148 helm: Add optional PodDisruptionBudget
  deployment/helm/node-feature-discovery/templates/master-pdb.yaml
  deployment/helm/node-feature-discovery/templates/nfd-gc-pdb.yaml
  deployment/helm/node-feature-discovery/values.yaml
  docs/deployment/helm.md
Labels: lgtm, cncf-cla: yes, size/M, approved, ok-to-test

#2000 add configurable pagination to nfd-master
  cmd/nfd-master/main.go
  deployment/components/master-config/nfd-master.conf.example
  deployment/helm/node-feature-discovery/values.yaml
  docs/reference/master-commandline-reference.md
  docs/reference/master-configuration-reference.md
  docs/usage/nfd-master.md
  pkg/nfd-master/nfd-api-controller.go
  pkg/nfd-master/nfd-master.go
Labels: lgtm, cncf-cla: yes, size/M, approved, ok-to-test

#2157 add configurable worker daemonset updateStrategy in Helm chart
  deployment/helm/node-feature-discovery/templates/worker.yaml
  deployment/helm/node-feature-discovery/values.yaml
  docs/deployment/helm.md
Labels: lgtm, cncf-cla: yes, size/S, approved, ok-to-test

#2161 go.mod: bump kubernetes to v1.33.1
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/L, approved

#2162 renamed google group for SIG Node
  .github/ISSUE_TEMPLATE/support.md
  docs/contributing/index.md
Labels: lgtm, cncf-cla: yes, size/XS, approved

#2163 docs: bump build dependencies
  Makefile
  docs/Gemfile
  docs/Gemfile.lock
  netlify.toml
  scripts/test-infra/build-gh-pages.sh
Labels: lgtm, cncf-cla: yes, size/L, approved

#2167 docs: document -port flag
  docs/reference/master-commandline-reference.md
  docs/reference/topology-updater-commandline-reference.md
  docs/reference/worker-commandline-reference.md
Labels: lgtm, cncf-cla: yes, size/M, approved
