Repository kubernetes-sigs/node-feature-discovery, pull requests merged in 2025-09, with the labels that each got.

#2282 scripts/test-infra: temporarily disable logcheck
  scripts/test-infra/verify.sh
Labels: lgtm, cncf-cla: yes, size/XS, approved

#2278 Bump golang to v1.25
  Makefile
  Tiltfile
  go.mod
Labels: lgtm, cncf-cla: yes, size/XS, approved

#2281 Do code generation non-containerized
  Dockerfile_generator
  Makefile
  api/generated/clientset/versioned/fake/clientset_generated.go
  api/generated/clientset/versioned/typed/nfd/v1alpha1/nfd_client.go
  api/generated/informers/externalversions/nfd/v1alpha1/nodefeature.go
  api/generated/informers/externalversions/nfd/v1alpha1/nodefeaturegroup.go
  api/generated/informers/externalversions/nfd/v1alpha1/nodefeaturerule.go
  go.mod
  go.sum
  hack/update_codegen.sh
  pkg/client-nfd/compat/artifact-client/client.go
  pkg/podres/client.go
  source/source.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#2288 [release-0.17] go.mod: bump k8s to v1.32.9
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/L, approved

#2294 Rebase PR 2001: add configurable pagination to nfd-gc
  cmd/nfd-gc/main.go
  docs/reference/gc-commandline-reference.md
  docs/usage/nfd-gc.md
  pkg/nfd-gc/nfd-gc.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#2299 helm: publish rolling staging version of OCI chart
  Makefile
  scripts/test-infra/push-image.sh
Labels: lgtm, cncf-cla: yes, size/XS, approved

#2303 scripts/test-infra/push-image: fix env variable parsing
  scripts/test-infra/push-image.sh
Labels: lgtm, cncf-cla: yes, size/XS, approved

#2301 docs/deployment: instruct users to use the OCI Helm repo
  docs/_config.yml
  docs/deployment/helm.md
  hack/prepare-release.sh
Labels: lgtm, cncf-cla: yes, size/M, approved

#2304 cloudbuild: export _PULL_BASE_REF as an env variable
  cloudbuild.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved

#2305 docs: document export sub-command in the nfd reference
  docs/reference/node-feature-client-reference.md
Labels: lgtm, cncf-cla: yes, size/S, approved
