Repository kubernetes-sigs/node-feature-discovery, pull requests merged in 2025-07, with the labels that each got.

#2199 Bugfix: NFR and NFG rules processing
  pkg/apis/nfd/nodefeaturerule/rule.go
  pkg/client-nfd/compat/node-validator/node-validator_test.go
Labels: lgtm, cncf-cla: yes, size/S, approved, ok-to-test

#2193 tilt: use anonymous, ephemeral image registry
  Tiltfile
Labels: lgtm, cncf-cla: yes, size/XS, approved

#2203 deps: bump Kubernetes to v1.33.3
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/L, approved

#2206 [release-0.14] docs: switch to jekyll-theme-read-the-docs
  docs/Gemfile.lock
  docs/_config.yml
Labels: lgtm, cncf-cla: yes, size/XS, approved

#2207 [release-0.13] docs: switch to jekyll-theme-read-the-docs
  docs/_config.yml
Labels: lgtm, cncf-cla: yes, size/XS, approved

#2211 [release-0.9] docs: switch to jekyll-theme-read-the-docs
  docs/_config.yml
  docs/_includes/templates/addons.liquid
  docs/_includes/templates/content.liquid
  docs/_includes/templates/sidebar.liquid
Labels: lgtm, cncf-cla: yes, size/M, approved

#2221 [release-0.8] docs: switch to jekyll-theme-read-the-docs
  .github/workflows/gh-pages.yml
  docs/_config.yml
  docs/_includes/templates/addons.liquid
  docs/_includes/templates/content.liquid
  docs/_includes/templates/sidebar.liquid
Labels: lgtm, cncf-cla: yes, size/M, approved

#2222 [release-0.7] docs: switch to jekyll-theme-read-the-docs
  .github/workflows/gh-pages.yml
  docs/_config.yml
  docs/_includes/templates/addons.liquid
  docs/_includes/templates/content.liquid
  docs/_includes/templates/sidebar.liquid
Labels: lgtm, cncf-cla: yes, size/M, approved

#2230 docs: bump docs build deps
  docs/Gemfile.lock
Labels: lgtm, cncf-cla: yes, size/S, approved

#2233 docs: customize favicon
  docs/_includes/common/links.liquid
  docs/assets/images/nfd/apple-touch-icon.png
  docs/assets/images/nfd/favicon-96x96.png
  docs/assets/images/nfd/favicon.ico
  docs/assets/images/nfd/favicon.svg
  docs/assets/images/nfd/site.webmanifest
  docs/assets/images/nfd/web-app-manifest-192x192.png
  docs/assets/images/nfd/web-app-manifest-512x512.png
Labels: lgtm, cncf-cla: yes, size/M, approved

#2189 logging: refine logging level in pod resources scanner
  pkg/resourcemonitor/podresourcesscanner.go
Labels: lgtm, cncf-cla: yes, size/XS, approved
